import Link from "next/link";
import type { Metadata } from "next";
import { SchoolSearch } from "@/components/school-search";
import { StudentSavingsCalculator } from "@/components/student-savings-calculator";
import { ArrowIcon, CheckIcon } from "@/components/icons";
import { StatusBadge } from "@/components/status-badge";
import { benefits, getSchoolBenefits, schools } from "@/data/seed";
export const metadata: Metadata={title:{absolute:"UnlockED — Everything your student status unlocks"},description:"UnlockED helps students find verified benefits, free software, AI tools, student discounts, and campus resources."};
export default function Home(){const popular=[...benefits].filter(i=>i.status==="verified_recently").sort((a,b)=>b.annualValue-a.annualValue||Number(Boolean(b.featured))-Number(Boolean(a.featured))).slice(0,6);return <>
  <section className="border-b-2 border-ink bg-paper"><div className="mx-auto grid max-w-7xl border-x border-ink/20 lg:grid-cols-[1.15fr_.85fr]"><div className="px-5 py-14 sm:px-8 sm:py-20 lg:border-r lg:border-ink/20 lg:py-24"><p className="rule-label text-forest">The verified student benefit index</p><h1 className="mt-5 max-w-3xl font-editorial text-5xl font-bold leading-[.98] tracking-[-.045em] sm:text-7xl">Everything your student status unlocks.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-ink/60">UnlockED helps students find verified benefits, free software, AI tools, student discounts, and campus resources available through their student status.</p><a href="#school-search" className="mt-8 inline-flex items-center gap-2 border-b-2 border-ink pb-1 text-xs font-bold uppercase tracking-widest hover:border-forest hover:text-forest">Explore my benefits <ArrowIcon /></a></div><div className="flex flex-col justify-end bg-white px-5 py-12 sm:px-8"><p className="rule-label text-ink/40">Search the directory</p><div id="school-search" className="mt-4 scroll-mt-24"><SchoolSearch /></div><p className="mt-3 text-xs text-ink/40">Search by full name, abbreviation, or .edu domain.</p></div></div></section>
  <section className="border-b-2 border-ink bg-white"><div className="mx-auto grid max-w-7xl border-x border-ink/20 sm:grid-cols-3">{[["01","Verified benefits","Every listing is checked against a provider source."],["02","Regularly updated","Dates and eligibility details are shown clearly."],["03","Free to use","No account, subscription, or hidden access fee."]].map(([n,t,c])=><div key={n} className="border-b border-ink/20 p-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0 sm:p-6"><span className="font-mono text-xs text-forest">{n}</span><h2 className="mt-5 font-editorial text-xl font-bold">{t}</h2><p className="mt-2 text-sm leading-6 text-ink/50">{c}</p></div>)}</div></section>
  <StudentSavingsCalculator />
  <section className="border-y-2 border-ink bg-white"><div className="mx-auto max-w-7xl border-x border-ink/20 px-5 py-14 sm:px-8 sm:py-20"><div className="flex flex-col justify-between gap-4 border-b-2 border-ink pb-5 sm:flex-row sm:items-end"><div><p className="rule-label text-forest">Popular benefits</p><h2 className="mt-2 font-editorial text-4xl font-bold">Where students save first</h2></div><Link href="/schools/university-of-michigan" className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider">View full index <ArrowIcon /></Link></div><div>{popular.map((item,i)=><Link href={`/benefits/${item.slug}`} key={item.slug} className="group grid gap-3 border-b border-ink/20 py-5 hover:bg-paper sm:grid-cols-[40px_1fr_150px_150px] sm:items-center"><span className="hidden font-mono text-xs text-ink/30 sm:block">{String(i+1).padStart(2,"0")}</span><div><div className="mb-1 flex items-center gap-3"><span className="rule-label text-forest">{item.category}</span><StatusBadge status={item.status}/></div><h3 className="font-editorial text-xl font-bold group-hover:underline">{item.name}</h3><p className="mt-1 text-sm text-ink/45">{item.provider}</p></div><p className="text-sm font-bold text-forest">{item.value}</p><span className="flex items-center justify-end gap-2 text-xs font-bold uppercase tracking-wider">View details <ArrowIcon /></span></Link>)}</div></div></section>
  <section className="mx-auto max-w-7xl border-x border-ink/20 px-5 py-14 sm:px-8 sm:py-20"><div className="border-b-2 border-ink pb-4"><p className="rule-label text-forest">Institution index</p><h2 className="mt-2 font-editorial text-4xl font-bold">Popular schools</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-4">{schools.slice(0,4).map((school)=><Link href={`/schools/${school.slug}`} key={school.slug} className="group border-b border-r border-ink/20 p-5 hover:bg-white"><span className="font-mono text-xs text-ink/35">{school.domain}</span><h3 className="mt-6 font-editorial text-xl font-bold group-hover:text-forest">{school.name}</h3><p className="mt-3 flex items-center gap-2 text-xs text-ink/45"><CheckIcon className="h-3 w-3 text-forest"/>{getSchoolBenefits(school).length} verified benefits</p></Link>)}</div></section>
</>}
