import Link from "next/link";
import type { CareerGrade, CareerGradeDimension, CareerRecord } from "@/data/careers";
import type { Opportunity } from "@/data/opportunities";
import { careerBySlug } from "@/data/careers";
import styles from "./career-detail.module.css";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const gradeLabels: Record<CareerGradeDimension, string> = { compensation: "Compensation", jobMarket: "Job market", workLife: "Work-life balance", entryAccessibility: "Entry accessibility", stability: "Stability", aiResilience: "AI resilience", aiUpside: "AI upside", longTermOutlook: "Long-term outlook" };

function Grade({ value, label }: { value: CareerGrade; label: string }) { return <span className={styles.grade} aria-label={`${label}: ${value}`}><b>{value}</b><small>{label}</small></span>; }
function ListSection({ title, items }: { title: string; items: string[] }) { return <section className={styles.panel}><h2>{title}</h2><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></section>; }

export function CareerDetail({ career, opportunities }: { career: CareerRecord; opportunities: Opportunity[] }) {
  const related = career.relatedCareerIds.map((id) => careerBySlug(id.replace(/^career:/, ""))).filter((item): item is CareerRecord => Boolean(item));
  const discoverQuery = encodeURIComponent(career.opportunityTerms.slice(0, 2).join(" "));
  return <main className={`${styles.page} application-studio-theme`} data-career-detail={career.slug}><div className={styles.shell}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/careers">Careers</Link><span aria-hidden="true">/</span><span>{career.name}</span></nav>
    <header className={styles.hero}><div><p className="rule-label text-forest">{career.category} · United States</p><h1>{career.name}</h1><p>{career.description} {career.summary}</p><div className={styles.actions}><Link href={`/opportunities?query=${discoverQuery}`}>Find related opportunities</Link><a href="#sources">Review sources</a></div></div><div className={styles.heroGrades}><Grade value={career.grades.longTermOutlook.grade} label="Future"/><Grade value={career.grades.aiResilience.grade} label="AI resilience"/><Grade value={career.grades.aiUpside.grade} label="AI upside"/></div></header>
    <section className={styles.snapshot} aria-label="Career snapshot"><div><span>Representative U.S. pay</span><strong>{career.salary.median ? money.format(career.salary.median) : "Not reliably available"}</strong><small>{career.salary.basisTitle}</small></div><div><span>Typical week</span><strong>{career.hours.minimum}–{career.hours.maximum} hours</strong><small>Employer and season vary</small></div><div><span>Common education</span><strong>{career.education.level}</strong><small>Not the only route</small></div><div><span>Remote potential</span><strong>{career.remotePotential}</strong><small>Role and employer dependent</small></div></section>
    <div className={styles.layout}><div className={styles.main}>
      <section className={styles.panel}><p className="rule-label text-forest">The work</p><h2>What {career.name.toLowerCase()}s do</h2><ul>{career.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul><h3>A typical week</h3><p>{career.typicalWeek}</p></section>
      <section className={styles.panel}><p className="rule-label text-forest">Pay & preparation</p><h2>A grounded starting point</h2><div className={styles.twoCol}><div><h3>Compensation</h3><p>{career.salary.median ? <>The mapped occupation’s U.S. median is <strong>{money.format(career.salary.median)}</strong>. A broad orientation range is {money.format(career.salary.entryRange?.[0] ?? career.salary.median * .65)}–{money.format(career.salary.experiencedRange?.[1] ?? career.salary.median * 1.45)}.</> : "A reliable national median was not available for this exact role."}</p><small>{career.salary.note}</small></div><div><h3>Education</h3><p><strong>{career.education.level}</strong></p><p>{career.education.note}</p><p>Relevant majors: {career.majors.join(", ")}.</p></div></div></section>
      <section className={`${styles.panel} ${styles.ai}`}><p className="rule-label">AI & the next 5–10 years</p><h2>{career.ai.impact}</h2><p>{career.ai.currentEffect}</p><div className={styles.twoCol}><div><h3>Tasks AI may change first</h3><ul>{career.ai.automatableTasks.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h3>Human value likely to endure</h3><ul>{career.ai.durableTasks.map((item) => <li key={item}>{item}</li>)}</ul></div></div><h3>How to position yourself</h3><ul>{career.ai.positioning.map((item) => <li key={item}>{item}</li>)}</ul><p className={styles.caution}>{career.ai.uncertainty}</p></section>
      <section className={styles.panel}><p className="rule-label text-forest">Transparent grading</p><h2>Eight lenses, with reasons</h2><p>These letter grades compress directional evidence. They are not rankings of personal worth or guarantees.</p><div className={styles.gradeGrid}>{Object.entries(career.grades).map(([key, result]) => <article key={key}><Grade value={result.grade} label={gradeLabels[key as CareerGradeDimension]}/><h3>{result.label}</h3><p>{result.explanation}</p><ul>{result.factors.map((factor) => <li key={factor}>{factor}</li>)}</ul></article>)}</div></section>
      <div className={styles.twoCol}><ListSection title="Advantages" items={career.advantages}/><ListSection title="Tradeoffs" items={career.tradeoffs}/><ListSection title="You may enjoy this if…" items={career.mayEnjoyIf}/><ListSection title="Prepare in college" items={career.collegePreparation}/></div>
      <section className={styles.panel}><h2>Skills to build</h2><div className={styles.skillGrid}>{Object.entries(career.skills).map(([group, skills]) => <div key={group}><h3>{group}</h3><p>{skills.join(" · ")}</p></div>)}</div></section>
      <section className={styles.panel}><h2>Entry and progression</h2><div className={styles.twoCol}><div><h3>Early roles</h3><ol>{career.entryRoles.map((item) => <li key={item}>{item}</li>)}</ol></div><div><h3>Possible progression</h3><ol>{career.progression.map((item) => <li key={item}>{item}</li>)}</ol></div></div></section>
    </div><aside className={styles.side}>
      <section className={styles.sidePanel}><h2>Related careers</h2>{related.map((item) => <Link key={item.id} href={`/careers/${item.slug}`}><span>{item.category}</span><strong>{item.name}</strong><small>{item.grades.longTermOutlook.grade} future · {item.grades.aiResilience.grade} resilience</small></Link>)}</section>
      <section className={styles.sidePanel}><h2>Safe opportunities</h2><p>Verified Discover records related by field—not personalized recommendations.</p>{opportunities.length ? opportunities.map((item) => <Link key={item.id} href={`/opportunities/${encodeURIComponent(item.id)}`}><span>{item.category}</span><strong>{item.title}</strong><small>{item.organization}</small></Link>) : <p>No recommendation-safe matches are available right now.</p>}<Link className={styles.allLink} href={`/opportunities?query=${discoverQuery}`}>Search all related opportunities →</Link></section>
    </aside></div>
    <section id="sources" className={styles.sources}><p className="rule-label text-forest">Sources & methodology</p><h2>Where this profile comes from</h2><p>Pay and labor-market figures are U.S. national orientation, not an offer forecast. Specialized titles may use a broader occupation as a proxy. AI outlooks describe task exposure and possible augmentation separately from job elimination.</p><div>{career.sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer"><strong>{source.name}</strong><span>{source.year} · {source.supports.join(", ")}</span></a>)}</div><small>Profile updated {new Date(`${career.updatedAt}T12:00:00Z`).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" })}.</small></section>
  </div></main>;
}
