import Link from "next/link";
import type { CareerGrade, CareerGradeDimension, CareerRecord } from "@/data/careers";
import type { Opportunity } from "@/data/opportunities";
import { careerBySlug } from "@/data/careers";
import styles from "./career-detail.module.css";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const gradeLabels: Record<CareerGradeDimension, string> = { compensation: "Compensation", jobMarket: "Job market", workLife: "Work-life balance", entryAccessibility: "Entry accessibility", stability: "Stability", aiResilience: "AI resilience", aiUpside: "AI upside", longTermOutlook: "Long-term outlook" };

function Grade({ value, label }: { value: CareerGrade; label: string }) { return <span className={styles.grade} aria-label={`${label}: ${value}`}><b>{value}</b><small>{label}</small></span>; }
function entryDifficulty(grade: CareerGrade) { return grade.startsWith("A") ? "Accessible" : grade.startsWith("B") ? "Moderately competitive" : grade.startsWith("C") ? "Competitive" : "Highly competitive"; }
function ListSection({ title, items }: { title: string; items: string[] }) { return <section className={styles.panel}><h2>{title}</h2><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></section>; }
function relationship(from: CareerRecord, to: CareerRecord) {
  if (from.category === to.category) return `Nearby path in ${from.category.toLowerCase()}, with a different mix of daily responsibilities and progression.`;
  if (to.intensity.research === "High") return "More research-oriented, with greater emphasis on evidence, experiments, and uncertain questions.";
  if (to.intensity.coding === "Very High") return "More engineering-oriented, with greater emphasis on building and operating technical systems.";
  if (to.intensity.people === "High") return "More people-centered, with greater emphasis on clients, teams, or public responsibility.";
  return `Uses related skills in ${to.category.toLowerCase()} rather than ${from.category.toLowerCase()}.`;
}

export function CareerDetail({ career, opportunities }: { career: CareerRecord; opportunities: Opportunity[] }) {
  const related = career.relatedCareerIds.map((id) => careerBySlug(id.replace(/^career:/, ""))).filter((item): item is CareerRecord => Boolean(item));
  const discoverQuery = encodeURIComponent(career.opportunityTerms.slice(0, 2).join(" "));
  return <main className={`${styles.page} application-studio-theme`} data-career-detail={career.slug}><div className={styles.shell}>
    <nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/careers">Careers</Link><span aria-hidden="true">/</span><span>{career.name}</span></nav>
    <header className={styles.hero}><div><p className="rule-label text-forest">{career.category} · United States</p><h1>{career.name}</h1><p>{career.description} {career.summary}</p><div className={styles.actions}><Link href={`/opportunities?query=${discoverQuery}`}>Find related opportunities</Link><a href="#sources">Review sources</a></div></div><div className={styles.heroGrades}><Grade value={career.grades.longTermOutlook.grade} label="Future"/><Grade value={career.grades.aiResilience.grade} label="AI resilience"/><Grade value={career.grades.aiUpside.grade} label="AI upside"/></div></header>
    <section className={styles.snapshot} aria-label="Career at a glance"><div><span>{career.salary.structure.includes("bonus") ? "BLS occupation median—not total compensation" : "Typical U.S. compensation"}</span><strong>{career.salary.median ? money.format(career.salary.median) : "Not reliably available"}</strong><small>{career.salary.basisTitle}</small></div><div><span>Typical week</span><strong>{career.hours.minimum}–{career.hours.maximum} hours</strong><small>{career.hours.schedule}</small></div><div><span>Common education</span><strong>{career.education.level}</strong><small>Not the only route</small></div><div><span>Entry difficulty</span><strong>{entryDifficulty(career.grades.entryAccessibility.grade)}</strong><small>{career.grades.entryAccessibility.grade} accessibility</small></div><div><span>Work-life balance</span><strong>{career.grades.workLife.grade}</strong><small>{career.grades.workLife.label}</small></div><div><span>Job market</span><strong>{career.grades.jobMarket.grade}</strong><small>{career.grades.jobMarket.label}</small></div><div><span>Remote flexibility</span><strong>{career.remotePotential}</strong><small>Employer dependent</small></div></section>
    <section className={styles.meaning}><p className="rule-label text-forest">What this means</p><p>{career.summary} The mapped data is a starting point: specialty, employer, geography, and seniority can materially change the experience.</p></section>
    <div className={styles.layout}><div className={styles.main}>
      <section className={styles.panel}><p className="rule-label text-forest">What you actually do</p><h2>Picture the work</h2><ul>{career.responsibilities.map((item) => <li key={item}>{item}</li>)}</ul><h3>A typical week</h3><p>{career.typicalWeek}</p><h3>Work environment</h3><div className={styles.environment}><p><strong>Settings</strong>{career.workEnvironment.settings.join(" · ")}</p><p><strong>Working style</strong>{career.workEnvironment.collaboration}</p><p><strong>Schedule</strong>{career.workEnvironment.predictability}</p><p><strong>Travel</strong>{career.workEnvironment.travel}</p><p><strong>Physical demands</strong>{career.workEnvironment.physicalDemands}</p><p><strong>Interaction</strong>{career.workEnvironment.interaction}</p></div></section>
      <section className={styles.panel}><p className="rule-label text-forest">Compensation & lifestyle</p><h2>How pay works</h2><div className={styles.payLevels}><div><span>Early career</span><strong>{career.salary.entryRange ? `${money.format(career.salary.entryRange[0])}–${money.format(career.salary.entryRange[1])}` : "Insufficient data"}</strong></div><div><span>Mapped median</span><strong>{career.salary.median ? money.format(career.salary.median) : "Not available"}</strong></div><div><span>Experienced orientation</span><strong>{career.salary.experiencedRange ? `${money.format(career.salary.experiencedRange[0])}–${money.format(career.salary.experiencedRange[1])}` : "Insufficient data"}</strong></div></div><p>{career.salary.structure}. {career.salary.highEndPotential}.</p><small>{career.salary.note}</small><h3>What tends to increase pay</h3><ul className={styles.inlineList}>{career.salary.drivers.map((item)=><li key={item}>{item}</li>)}</ul></section>
      <section className={`${styles.panel} ${styles.ai}`}><p className="rule-label">AI & the next 5–10 years</p><h2>{career.ai.impact}</h2><p>{career.ai.currentEffect}</p><div className={styles.aiLesson}><div><strong>Task automation</strong><span>AI performs part of the workflow.</span></div><div><strong>Productivity augmentation</strong><span>A person completes or improves work faster.</span></div><div><strong>Job displacement</strong><span>Employers reduce or replace whole roles. This does not automatically follow from task automation.</span></div></div><h3>AI today</h3><ul className={styles.inlineList}>{career.ai.today.map((item)=><li key={item}>{item}</li>)}</ul><div className={styles.taskMap}><div><p className="rule-label">More exposed</p><ul>{career.ai.automatableTasks.map((item)=><li key={item}>{item}</li>)}</ul></div><div><p className="rule-label">Less exposed</p><ul>{career.ai.durableTasks.map((item)=><li key={item}>{item}</li>)}</ul></div></div><div className={styles.twoCol}><div><h3>How the job may change</h3><p>{career.ai.workflowChange}</p><h3>AI upside</h3><p>{career.ai.upside}</p></div><div><h3>AI risk</h3><p>{career.ai.risk}</p><h3>Skills gaining value</h3><p>{career.ai.valuableSkills.join(" · ")}</p></div></div><h3>How to position yourself</h3><ul>{career.ai.positioning.map((item) => <li key={item}>{item}</li>)}</ul><p className={styles.caution}>{career.ai.uncertainty}</p></section>
      <section className={styles.panel}><p className="rule-label text-forest">Transparent grading</p><h2>Eight lenses, with reasons</h2><p>These letter grades compress directional evidence. They are not rankings of personal worth or guarantees.</p><div className={styles.gradeGrid}>{Object.entries(career.grades).map(([key, result]) => <article key={key}><Grade value={result.grade} label={gradeLabels[key as CareerGradeDimension]}/><h3>{result.label}</h3><p>{result.explanation}</p><ul>{result.factors.map((factor) => <li key={factor}>{factor}</li>)}</ul></article>)}</div></section>
      <section className={styles.panel}><p className="rule-label text-forest">Long-term outlook</p><h2>Forces that could shape this path</h2><div className={styles.twoCol}><div><h3>Outlook drivers</h3><ul>{career.outlook.drivers.map((item)=><li key={item}>{item}</li>)}</ul></div><div><h3>Outlook risks</h3><ul>{career.outlook.risks.map((item)=><li key={item}>{item}</li>)}</ul></div></div></section>
      <div className={styles.twoCol}><ListSection title="Advantages" items={career.advantages}/><ListSection title="Tradeoffs" items={career.tradeoffs}/><ListSection title="You may enjoy this if…" items={career.mayEnjoyIf}/><ListSection title="What surprises people" items={career.surprises}/></div>
      <section className={styles.panel}><h2>Skills to build</h2><div className={styles.skillGrid}>{Object.entries(career.skills).map(([group, skills]) => <div key={group}><h3>{group}</h3><p>{skills.join(" · ")}</p></div>)}</div></section>
      <section className={styles.panel}><p className="rule-label text-forest">How people break in</p><h2>College preparation</h2><p>These are useful ways to explore—not a required checklist or one perfect route.</p><div className={styles.prepGrid}>{Object.entries(career.collegePlan).map(([label,items])=><div key={label}><h3>{label}</h3><ul>{items.map((item)=><li key={item}>{item}</li>)}</ul></div>)}</div></section>
      <section className={styles.panel}><h2>Career trajectory</h2><p>Careers branch; this is a map of common possibilities, not a ladder everyone follows.</p><div className={styles.trajectory}><div><h3>Common starting positions</h3>{career.entryRoles.map((item)=><span key={item}>{item}</span>)}</div><div><h3>Possible progression</h3>{career.progression.map((item)=><span key={item}>{item}</span>)}</div><div><h3>Branches</h3>{career.careerBranches.map((item)=><span key={item}>{item}</span>)}</div><div><h3>Adjacent exits</h3>{career.adjacentExits.map((item)=><span key={item}>{item}</span>)}</div></div></section>
      <ListSection title="Try this career before committing" items={career.tryBeforeCommitting}/>
    </div><aside className={styles.side}>
      <section className={styles.sidePanel}><p className="rule-label text-forest">Discovery map</p><h2>Careers like this</h2>{related.map((item) => <Link key={item.id} href={`/careers/${item.slug}`}><span>{item.category}</span><strong>{item.name}</strong><small>{relationship(career,item)}</small></Link>)}</section>
      <section className={styles.sidePanel}><h2>Safe opportunities</h2><p>Verified Discover records related by field—not personalized recommendations.</p>{opportunities.length ? opportunities.map((item) => <Link key={item.id} href={`/opportunities/${encodeURIComponent(item.id)}`}><span>{item.category}</span><strong>{item.title}</strong><small>{item.organization}</small></Link>) : <p>No recommendation-safe matches are available right now.</p>}<Link className={styles.allLink} href={`/opportunities?query=${discoverQuery}`}>Search all related opportunities →</Link></section>
    </aside></div>
    <section id="sources" className={styles.sources}><p className="rule-label text-forest">Sources & methodology</p><h2>Where this profile comes from</h2><p>Pay and labor-market figures are U.S. national orientation, not an offer forecast. Specialized titles may use a broader occupation as a proxy. AI outlooks describe task exposure and possible augmentation separately from job elimination.</p><div>{career.sources.map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer"><strong>{source.name}</strong><span>{source.year} · {source.supports.join(", ")}</span></a>)}</div><small>Profile updated {new Date(`${career.updatedAt}T12:00:00Z`).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" })}.</small></section>
  </div></main>;
}
