import type { College } from "@/lib/colleges";
import { collegeCdsSources } from "@/data/college-cds";
import { verifiedCollegeAdmissions, verifiedCollegeTestingPolicies } from "@/data/college-admissions";
import { cdsImportanceLabels, derivedRate, groupedCdsFactors, latestCollegeCds } from "@/lib/college-admissions-insights";

const number = new Intl.NumberFormat("en-US");
const percent = new Intl.NumberFormat("en-US", { style: "percent", maximumFractionDigits: 1 });

function Metric({ label, value, note }: { label: string; value: string; note?: string }) {
  return <div className="border-t border-ink/10 py-4"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-ink/38">{label}</dt><dd className="mt-1 text-lg font-semibold text-[var(--unlocked-text)]">{value}</dd>{note ? <p className="mt-1 text-xs leading-5 text-ink/42">{note}</p> : null}</div>;
}

const value = (input?: number) => input === undefined ? "Not reported" : number.format(input);
const rate = (input?: number) => input === undefined ? "Not reported" : percent.format(input);
const scoreRange = (input?: [number, number]) => input ? `${input[0]}–${input[1]}` : "Not reported";

function ScoreContext({ label, score, range, cohort }: { label: string; score: number; range: [number, number]; cohort: string }) {
  const minimum = label === "SAT" ? 400 : 1;
  const maximum = label === "SAT" ? 1600 : 36;
  const position = Math.max(0, Math.min(100, ((score - minimum) / (maximum - minimum)) * 100));
  const low = ((range[0] - minimum) / (maximum - minimum)) * 100;
  const high = ((range[1] - minimum) / (maximum - minimum)) * 100;
  const relation = score < range[0] ? "below" : score > range[1] ? "above" : "within";
  return <div className="rounded-xl border border-ink/10 p-5"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.11em] text-forest">Your recorded {label}</p><p className="mt-1 font-editorial text-3xl font-semibold">{score}</p></div><p className="text-right text-xs text-ink/45">Middle 50%<br/><strong className="text-[var(--unlocked-text)]">{range[0]}–{range[1]}</strong></p></div><div className="relative mt-5 h-2 rounded-full bg-ink/8"><span className="absolute top-0 h-2 rounded-full bg-forest/28" style={{ left: `${low}%`, width: `${Math.max(2, high - low)}%` }}/><span className="absolute top-1/2 h-3 w-1 -translate-x-1/2 -translate-y-1/2 rounded-full bg-forest" style={{ left: `${position}%` }}/></div><p className="mt-4 text-xs leading-5 text-ink/48">Your recorded score falls {relation} this institution&apos;s recently reported middle 50% range for {cohort}. This is not a required score or an admission prediction.</p></div>;
}

export function CollegeAdmissionsInsights({ college, studentTesting }: { college: College; studentTesting?: { sat?: number; act?: number } }) {
  const snapshot = latestCollegeCds(college.id);
  const source = collegeCdsSources[college.id];
  const current = verifiedCollegeAdmissions[college.id];
  const testingPolicy = verifiedCollegeTestingPolicies[college.id];

  if (!snapshot) return <section className="grid gap-6 border-t border-ink/10 py-10 md:grid-cols-[15rem_minmax(0,1fr)] md:py-14"><div><p className="rule-label text-forest">Admissions insights</p><h2 className="mt-2 font-editorial text-3xl font-semibold text-[var(--unlocked-text)]">What the college reports</h2></div><div className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-6"><p className="text-sm font-bold text-[var(--unlocked-text)]">Common Data Set details are not available here yet.</p><p className="mt-2 max-w-2xl text-sm leading-6 text-ink/52">We only publish institutional admissions factors and cohort details after verifying the college’s own report. The rest of this college profile remains available.</p>{source ? <a href={source.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex text-sm font-bold text-forest hover:underline">Check the institutional source →</a> : null}</div></section>;

  const admissions = snapshot.admissions;
  const acceptance = derivedRate(admissions?.admitted, admissions?.applicants);
  const yieldRate = derivedRate(admissions?.enrolled, admissions?.admitted);
  const groups = groupedCdsFactors(snapshot);

  return <section className="grid gap-6 border-t border-ink/10 py-10 md:grid-cols-[15rem_minmax(0,1fr)] md:py-14">
    <div><p className="rule-label text-forest">Admissions insights</p><h2 className="mt-2 font-editorial text-3xl font-semibold text-[var(--unlocked-text)]">What the college reports</h2><p className="mt-3 text-xs leading-5 text-ink/42">{snapshot.academicYear} Common Data Set · {snapshot.cohortLabel}</p></div>
    <div className="space-y-8">
      <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-sm font-bold text-[var(--unlocked-text)]">Recent admissions profile</h3><p className="mt-1 text-xs leading-5 text-ink/45">Institution-reported counts. Rates are calculated directly from those counts.</p></div><span className="rounded-full border border-ink/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-ink/45">{snapshot.cohortLabel}</span></div><dl className="mt-4 grid gap-x-7 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Applicants" value={value(admissions?.applicants)} /><Metric label="Admitted" value={value(admissions?.admitted)} /><Metric label="Enrolled" value={value(admissions?.enrolled)} /><Metric label="Acceptance rate" value={rate(acceptance)} note="Admitted ÷ applicants" /><Metric label="Enrollment yield" value={rate(yieldRate)} note="Enrolled ÷ admitted" /><Metric label="Waitlist admitted" value={value(admissions?.waitlistAdmitted)} note={admissions?.waitlistOffered === undefined ? undefined : `${value(admissions.waitlistAccepted)} accepted a place of ${value(admissions.waitlistOffered)} offered`} /></dl></div>

      {groups.length ? <div><h3 className="text-sm font-bold text-[var(--unlocked-text)]">Factors in admission decisions</h3><p className="mt-1 max-w-2xl text-xs leading-5 text-ink/45">The institution’s exact C7 categories are shown as reported. They are not a score, order of importance, or prediction.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{groups.map((group) => <div key={group.importance} className="rounded-xl border border-ink/10 bg-[var(--unlocked-surface)] p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-forest">{cdsImportanceLabels[group.importance]}</p><ul className="mt-3 space-y-2">{group.factors.map((factor) => <li key={factor} className="flex gap-2 text-sm leading-5 text-ink/62"><span aria-hidden="true" className="mt-[.42rem] h-1 w-1 shrink-0 rounded-full bg-forest/55" />{factor}</li>)}</ul></div>)}</div></div> : null}

      {snapshot.testing ? <div><h3 className="text-sm font-bold text-[var(--unlocked-text)]">Testing, historically reported</h3><p className="mt-1 text-xs leading-5 text-ink/45">Score ranges and submission shares describe {snapshot.testing.cohortLabel}. They do not establish the current testing policy.</p><dl className="mt-4 grid gap-x-7 sm:grid-cols-2 lg:grid-cols-3"><Metric label="SAT composite, middle 50%" value={scoreRange(snapshot.testing.satComposite)} /><Metric label="SAT reading, middle 50%" value={scoreRange(snapshot.testing.satReading)} /><Metric label="SAT math, middle 50%" value={scoreRange(snapshot.testing.satMath)} /><Metric label="ACT composite, middle 50%" value={scoreRange(snapshot.testing.actComposite)} /><Metric label="Submitted SAT" value={snapshot.testing.satSubmittingPercent === undefined ? "Not reported" : `${snapshot.testing.satSubmittingPercent}%`} /><Metric label="Submitted ACT" value={snapshot.testing.actSubmittingPercent === undefined ? "Not reported" : `${snapshot.testing.actSubmittingPercent}%`} /></dl>{studentTesting && (snapshot.testing.satComposite || snapshot.testing.actComposite) ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{studentTesting.sat && snapshot.testing.satComposite ? <ScoreContext label="SAT" score={studentTesting.sat} range={snapshot.testing.satComposite} cohort={snapshot.testing.cohortLabel}/> : null}{studentTesting.act && snapshot.testing.actComposite ? <ScoreContext label="ACT" score={studentTesting.act} range={snapshot.testing.actComposite} cohort={snapshot.testing.cohortLabel}/> : null}</div> : null}</div> : null}

      {snapshot.classRank || snapshot.gpa ? <div><h3 className="text-sm font-bold text-[var(--unlocked-text)]">Class rank and GPA</h3><p className="mt-1 text-xs leading-5 text-ink/45">Only reported cohorts and denominators are shown.</p><dl className="mt-4 grid gap-x-7 sm:grid-cols-2 lg:grid-cols-3">{snapshot.classRank ? <><Metric label="Top tenth" value={`${snapshot.classRank.topTenth}%`} note={`${snapshot.classRank.reportingPercent}% of the entering class reported rank`} /><Metric label="Top quarter" value={`${snapshot.classRank.topQuarter}%`} note={snapshot.classRank.cohortLabel} /><Metric label="Top half" value={`${snapshot.classRank.topHalf}%`} note={snapshot.classRank.cohortLabel} /></> : null}{snapshot.gpa ? <><Metric label="Average high school GPA" value={snapshot.gpa.average?.toFixed(1) ?? "Not reported"} note={`${snapshot.gpa.reportingPercent}% reported GPA on a ${snapshot.gpa.scale} scale`} />{Object.entries(snapshot.gpa.distribution ?? {}).slice(0, 5).map(([range, share]) => <Metric key={range} label={`GPA ${range}`} value={`${share}%`} note={snapshot.gpa!.cohortLabel} />)}</> : null}</dl></div> : null}

      <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-mint/50 p-5"><p className="text-xs font-bold uppercase tracking-[.11em] text-forest">Current testing policy</p>{testingPolicy ? <><p className="mt-2 text-sm font-bold text-[var(--unlocked-text)]">{testingPolicy.label} · {testingPolicy.cycle}</p><p className="mt-1 text-xs leading-5 text-ink/50">Verified from the institution&apos;s current admissions guidance, independently of its older CDS.</p><a href={testingPolicy.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-sm font-bold text-forest hover:underline">View official testing policy →</a></> : <><p className="mt-2 text-sm font-bold text-[var(--unlocked-text)]">Policy needs verification</p><p className="mt-1 text-xs leading-5 text-ink/50">Do not infer the current policy from a historical CDS.</p></>}</div><div className="rounded-xl border border-ink/10 p-5"><p className="text-xs font-bold uppercase tracking-[.11em] text-ink/42">Source</p><p className="mt-2 text-sm font-bold text-[var(--unlocked-text)]">Common Data Set {snapshot.academicYear}</p><p className="mt-1 text-xs leading-5 text-ink/48">Institutional report · verified {snapshot.verifiedAt}</p><a href={snapshot.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-sm font-bold text-forest hover:underline">Open source PDF →</a>{current ? <a href={current.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 block text-sm font-bold text-forest hover:underline">Current application requirements →</a> : null}</div></div>
    </div>
  </section>;
}
