"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Opportunity } from "@/data/opportunities";
import { schoolDirectory as schools, type School } from "@/data/school-directory";
import { SearchIcon } from "./icons";
import { trackProductEvent } from "@/data/product-analytics";

type SearchResult = { id: string; title: string; subtitle: string; href: string; group: Group; score: number };
type Group = "Universities" | "Opportunities" | "AI Tools" | "Scholarships" | "Career" | "Research";
const groups: Group[] = ["Universities", "Opportunities", "AI Tools", "Scholarships", "Career", "Research"];

const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9.+# ]/g," ").replace(/\s+/g," ").trim();
const expansions: Record<string,string[]> = { internships:["internship"], internship:["career"], freshman:["first year","freshman programs"], sophomore:["second year"], junior:["third year"], senior:["fourth year"], free:["no cost","student offer"], coding:["software","computer science","developer"], quant:["quantitative","finance","mathematics"], scholarships:["scholarship"] };
function scoreText(query:string,text:string){const normalized=normalize(text),queryText=normalize(query),terms=queryText.split(" ").filter(Boolean);if(!queryText||!terms.length)return-1;let score=normalized.includes(queryText)?80:0;const matches=terms.filter((term)=>[term,...(expansions[term]??[])].some((candidate)=>normalized.includes(candidate)));if(matches.length<Math.ceil(terms.length*.6))return-1;score+=matches.length*12;if(normalized.startsWith(queryText))score+=30;return score}
function groupFor(item:Opportunity):Group { if(item.type==="AI")return"AI Tools";if(item.type==="Scholarship")return"Scholarships";if(item.type==="Career")return"Career";if(item.type==="Research")return"Research";return"Opportunities" }
function schoolText(school:School){return[school.name,school.domain,school.slug,school.location,school.initials,...school.aliases].join(" ")}
function opportunityText(item:Opportunity){const schoolNames=item.schools.map((slug)=>schools.find((school)=>school.slug===slug)?.name??slug);return[item.title,item.organization,item.description,item.category,item.eligibility,item.location,...item.majors,...item.academic_years,...item.tags,...item.schools,...schoolNames].join(" ")}

export function GlobalSearch(){
  const[open,setOpen]=useState(false);const[query,setQuery]=useState("");const[active,setActive]=useState(0);const[opportunities,setOpportunities]=useState<Opportunity[]>([]);const[loading,setLoading]=useState(false);const inputRef=useRef<HTMLInputElement>(null);const router=useRouter();
  useEffect(()=>{const trimmed=query.trim();if(!open||trimmed.length<2){setOpportunities([]);setLoading(false);return}const controller=new AbortController();const timer=window.setTimeout(async()=>{setLoading(true);try{const params=new URLSearchParams({view:"discover",query:trimmed,limit:"32",sort:"Relevant"});const response=await fetch(`/api/opportunities?${params}`,{signal:controller.signal});if(!response.ok)throw new Error(`search_${response.status}`);const body=await response.json() as {opportunities:Opportunity[]};setOpportunities(body.opportunities)}catch(error){if(!(error instanceof DOMException&&error.name==="AbortError"))setOpportunities([])}finally{if(!controller.signal.aborted)setLoading(false)}},140);return()=>{window.clearTimeout(timer);controller.abort()}},[open,query]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(true)}if(event.key==="Escape")setOpen(false)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
  useEffect(()=>{if(open){requestAnimationFrame(()=>inputRef.current?.focus());document.body.style.overflow="hidden"}else{document.body.style.overflow="";setQuery("");setActive(0)}return()=>{document.body.style.overflow=""}},[open]);
  const results=useMemo<SearchResult[]>(()=>{if(!query.trim())return[];const schoolResults=schools.map((school)=>({id:`school-${school.slug}`,title:school.name,subtitle:`${school.domain} · ${school.location}`,href:`/schools/${school.slug}`,group:"Universities" as const,score:scoreText(query,schoolText(school))})).filter((item)=>item.score>=0);const opportunityResults=opportunities.filter((item)=>item.verification_status!=="expired").map((item)=>({id:item.id,title:item.title,subtitle:`${item.organization} · ${item.category}`,href:`/opportunities/${item.id}`,group:groupFor(item),score:scoreText(query,opportunityText(item))})).filter((item)=>item.score>=0);const combined=[...schoolResults,...opportunityResults];return groups.flatMap((group)=>combined.filter((item)=>item.group===group).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title)).slice(0,4))},[opportunities,query]);
  useEffect(()=>setActive(0),[query]);
  function recordSearch(result:SearchResult){trackProductEvent("search",{searchType:result.group==="Universities"?"school":"global",searchValue:result.group==="Universities"?result.id.replace("school-",""):result.group})}
  function go(result:SearchResult){recordSearch(result);setOpen(false);router.push(result.href)}
  function onKeyDown(event:React.KeyboardEvent<HTMLInputElement>){if(event.key==="ArrowDown"){event.preventDefault();setActive((value)=>Math.min(results.length-1,value+1))}if(event.key==="ArrowUp"){event.preventDefault();setActive((value)=>Math.max(0,value-1))}if(event.key==="Enter"&&results[active]){event.preventDefault();go(results[active])}}
  return <>
    <button type="button" onClick={()=>setOpen(true)} aria-label="Search UnlockED" className="flex h-10 w-full items-center gap-2 border border-ink/15 bg-white px-3 text-left text-sm text-ink/40 hover:border-ink/35 md:w-48 lg:w-56"><SearchIcon className="h-4 w-4 shrink-0"/><span className="min-w-0 flex-1 truncate">Search UnlockED</span><kbd className="hidden text-[10px] font-bold text-ink/30 lg:block">⌘ K</kbd></button>
    {open&&<div className="fixed inset-0 z-50 bg-ink/30 px-4 pt-[8vh] sm:pt-[12vh]" role="presentation" onMouseDown={(event)=>{if(event.currentTarget===event.target)setOpen(false)}}><section role="dialog" aria-modal="true" aria-label="Search UnlockED" className="mx-auto max-h-[78vh] max-w-2xl overflow-hidden bg-white shadow-[0_24px_80px_rgba(43,33,26,.24)]"><label className="flex h-16 items-center gap-3 border-b border-ink/15 px-5"><SearchIcon className="h-5 w-5 shrink-0 text-forest"/><span className="sr-only">Search opportunities and universities</span><input ref={inputRef} value={query} onChange={(event)=>setQuery(event.target.value)} onKeyDown={onKeyDown} placeholder="Search internships, AI tools, schools, scholarships…" className="min-w-0 flex-1 bg-transparent text-base outline-none placeholder:text-ink/30"/><button type="button" onClick={()=>setOpen(false)} className="text-xs font-bold uppercase tracking-wider text-ink/35">Esc</button></label><div className="max-h-[calc(78vh-4rem)] overflow-y-auto p-2">{!query.trim()&&<div className="px-4 py-10 text-center"><p className="font-editorial text-2xl font-bold">Find anything in UnlockED</p><p className="mt-2 text-sm text-ink/45">Try “computer science internships,” “free AI,” or “UChicago.”</p></div>}{query.trim()&&!results.length&&<div className="px-4 py-10 text-center"><p className="font-editorial text-2xl font-bold">{loading ? "Searching" : "No matches found"}</p><p className="mt-2 text-sm text-ink/45">{loading ? "Looking across schools and opportunities…" : "Try a broader school, major, organization, or opportunity type."}</p></div>}{groups.map((group)=>{const items=results.filter((item)=>item.group===group);if(!items.length)return null;return <div key={group} className="mb-2 last:mb-0"><p className="rule-label px-3 py-2 text-ink/35">{group}</p>{items.map((item)=>{const index=results.indexOf(item);return <Link key={item.id} href={item.href} onMouseEnter={()=>setActive(index)} onClick={()=>{recordSearch(item);setOpen(false)}} className={`flex items-center justify-between gap-4 px-3 py-3 ${index===active?"bg-paper":"hover:bg-paper"}`}><div className="min-w-0"><p className="truncate text-sm font-bold">{item.title}</p><p className="mt-1 truncate text-xs text-ink/40">{item.subtitle}</p></div>{index===active&&<span className="shrink-0 text-[10px] font-bold uppercase tracking-wider text-forest">Open ↵</span>}</Link>})}</div>})}</div></section></div>}
  </>
}
