"use client";

import Link from "next/link";
import { useState } from "react";
import { authenticatedFetch } from "@/data/authenticated-request";
import {
  bestAct,
  bestSat,
  courseLevelLabels,
  gradeSystemLabels,
  satSuperscore,
  type AcademicCourse,
  type ActAttempt,
  type HighSchoolAcademicStore,
  type SatAttempt,
} from "@/data/high-school-academics";

type View = "overview" | "coursework" | "testing";
type Profile = { schoolName?: string; graduationYear?: string; year?: string };
type Mutation = (body: Record<string, unknown>) => Promise<boolean>;
type CollegeContext = { id: string; name: string; slug: string; policy: string; policyVerified: boolean; satRange?: [number, number]; actRange?: [number, number]; cohort?: string };

const inputClass = "min-h-11 w-full rounded-xl border border-ink/12 bg-white/55 px-3 text-sm text-[var(--unlocked-text)] outline-none transition focus:border-forest focus:ring-2 focus:ring-forest/15 dark:bg-white/[.04]";
const dateLabel = (date: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T12:00:00Z`));
const profileGrade = (year?: string) => /12|senior/i.test(year ?? "") ? 12 : /11|junior/i.test(year ?? "") ? 11 : /10|sophomore/i.test(year ?? "") ? 10 : 9;

function Fact({ label, value, note }: { label: string; value: string; note?: string }) {
  return <div className="border-t border-ink/10 py-4"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-ink/38">{label}</dt><dd className="mt-1 font-editorial text-2xl font-semibold text-[var(--unlocked-text)]">{value}</dd>{note ? <p className="mt-1 text-xs leading-5 text-ink/42">{note}</p> : null}</div>;
}

function EmptyScore({ test, open }: { test: string; open: () => void }) {
  return <div className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-5"><p className="font-editorial text-2xl font-semibold">No official {test} recorded</p><p className="mt-2 text-sm leading-6 text-ink/48">Official results and future practice work remain separate.</p><button type="button" onClick={open} className="mt-4 min-h-11 text-sm font-bold text-forest">Open Testing →</button></div>;
}

export function HighSchoolAcademics({ initialStore, profile, academicHonors, collegeContexts }: { initialStore: HighSchoolAcademicStore; profile: Profile; academicHonors: Array<{ id: string; title: string; outcome: string; date: string }>; collegeContexts: CollegeContext[] }) {
  const [store, setStore] = useState(initialStore);
  const [view, setView] = useState<View>("overview");
  const [pending, setPending] = useState(false);
  const [error, setError] = useState("");
  const sat = bestSat(store);
  const act = bestAct(store);
  const superscore = satSuperscore(store);
  const courses = Object.values(store.courses).sort((a, b) => b.gradeLevel - a.gradeLevel || a.subject.localeCompare(b.subject));
  const gpas = Object.values(store.gpas).filter(Boolean);
  const school = store.school?.name ?? profile.schoolName;
  const graduation = store.graduationYear ?? profile.graduationYear;
  const grade = store.gradeLevel ?? profileGrade(profile.year);
  const nextPlan = [...store.testing.plans].filter((plan) => plan.registrationStatus !== "completed" && plan.date >= new Date().toISOString().slice(0, 10)).sort((a, b) => a.date.localeCompare(b.date))[0];

  async function mutate(body: Record<string, unknown>) {
    setPending(true);
    setError("");
    try {
      const response = await authenticatedFetch("/api/academics", { method: "POST", credentials: "same-origin", cache: "no-store", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...body, expectedVersion: store.version }) });
      const result = await response.json().catch(() => null) as { academics?: HighSchoolAcademicStore; error?: string } | null;
      if (!response.ok || !result?.academics) throw new Error(result?.error ?? "Academic record could not be saved.");
      setStore(result.academics);
      return true;
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Academic record could not be saved.");
      return false;
    } finally {
      setPending(false);
    }
  }

  const gpaDisplay = gpas[0] ? `${gpas[0].value} / ${gpas[0].scale}` : store.gpaStatus === "school_does_not_calculate" ? "School does not calculate GPA" : "Not recorded";

  return <main className="min-h-screen px-5 pb-28 pt-10 sm:px-8 sm:pt-14"><div className="mx-auto max-w-6xl">
    <header className="grid gap-8 border-b border-ink/10 pb-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="rule-label text-forest">Private academic record</p><h1 className="mt-3 font-editorial text-5xl font-semibold leading-[1.03] sm:text-6xl">Academics &amp; Testing</h1><p className="mt-5 max-w-2xl text-base leading-7 text-ink/52">A factual record of what you have studied and the official tests you have taken. UnlockED does not turn it into an admissions score.</p></div><div className="rounded-xl border border-ink/10 px-4 py-3 text-xs leading-5 text-ink/48"><strong className="block text-forest">Private by default</strong>Not shown on Passport or public profiles.</div></header>
    <nav aria-label="Academic sections" className="mt-6 flex gap-1 overflow-x-auto rounded-full border border-ink/8 bg-white/40 p-1 sm:w-fit dark:bg-white/[.03]">{(["overview", "coursework", "testing"] as View[]).map((item) => <button key={item} type="button" aria-current={view === item ? "page" : undefined} onClick={() => setView(item)} className={`min-h-11 whitespace-nowrap rounded-full px-5 text-sm font-bold capitalize transition ${view === item ? "bg-white text-forest shadow-sm dark:bg-white/10" : "text-ink/48 hover:text-forest"}`}>{item}</button>)}</nav>
    {error ? <p role="alert" className="mt-5 rounded-xl border border-red-700/15 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</p> : null}
    {view === "overview" ? <Overview store={store} courses={courses} gpaDisplay={gpaDisplay} school={school} graduation={graduation} grade={grade} sat={sat} act={act} superscore={superscore} nextPlan={nextPlan} academicHonors={academicHonors} open={setView} /> : null}
    {view === "coursework" ? <Coursework store={store} courses={courses} school={school} graduation={graduation} grade={grade} pending={pending} mutate={mutate} /> : null}
    {view === "testing" ? <Testing store={store} pending={pending} mutate={mutate} collegeContexts={collegeContexts} /> : null}
  </div></main>;
}

function Overview({ courses, gpaDisplay, school, graduation, grade, sat, act, superscore, nextPlan, academicHonors, open }: { store: HighSchoolAcademicStore; courses: AcademicCourse[]; gpaDisplay: string; school?: string; graduation?: string; grade: number; sat?: SatAttempt; act?: ActAttempt; superscore?: { total: number; readingWriting: number; math: number }; nextPlan?: HighSchoolAcademicStore["testing"]["plans"][number]; academicHonors: Array<{ id: string; title: string; outcome: string; date: string }>; open: (view: View) => void }) {
  return <div className="mt-8 space-y-6"><section className="rounded-[1.75rem] border border-ink/10 bg-[var(--unlocked-surface)] p-6 shadow-soft sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="rule-label text-ink/38">Academic profile</p><h2 className="mt-2 font-editorial text-3xl font-semibold">Your record at a glance</h2></div><button type="button" onClick={() => open("coursework")} className="min-h-11 text-sm font-bold text-forest">View academic record →</button></div><dl className="mt-6 grid gap-x-8 sm:grid-cols-2 lg:grid-cols-5"><Fact label="High school" value={school ?? "Not recorded"}/><Fact label="Graduation" value={graduation ?? "Not recorded"}/><Fact label="Grade" value={`${grade}th grade`}/><Fact label="GPA" value={gpaDisplay}/><Fact label="Coursework" value={`${courses.length} course${courses.length === 1 ? "" : "s"}`}/></dl></section>
    <div className="grid gap-5 lg:grid-cols-3"><div className="grid gap-4 sm:grid-cols-2 lg:col-span-2">{sat ? <ScoreCard title="Best official SAT" score={sat.total} parts={`R&W ${sat.readingWriting} · Math ${sat.math}`} note={superscore && superscore.total > sat.total ? `Potential superscore ${superscore.total}; college policies vary.` : `Recorded ${dateLabel(sat.testDate)}.`}/> : <EmptyScore test="SAT" open={() => open("testing")}/>} {act ? <ScoreCard title="Best official ACT" score={act.composite} parts={`English ${act.english} · Math ${act.math} · Reading ${act.reading}${act.science ? ` · Science ${act.science}` : ""}`} note="Science and Writing are optional and are not part of the current Composite."/> : <EmptyScore test="ACT" open={() => open("testing")}/>}</div><aside className="rounded-2xl bg-ink p-6 text-white"><p className="rule-label text-mint">Next test</p>{nextPlan ? <><h2 className="mt-4 font-editorial text-3xl font-semibold uppercase">{nextPlan.test}</h2><p className="mt-2 text-sm text-white/60">{dateLabel(nextPlan.date)} · {nextPlan.registrationStatus}</p>{nextPlan.preparationDate ? <p className="mt-2 text-xs text-white/45">Preparation date you added: {dateLabel(nextPlan.preparationDate)}</p> : null}</> : <><h2 className="mt-4 font-editorial text-2xl font-semibold">Nothing scheduled</h2><p className="mt-2 text-sm leading-6 text-white/55">Add a test date only when it is useful to your plan.</p></>}<button type="button" onClick={() => open("testing")} className="mt-5 min-h-11 text-sm font-bold text-mint">Manage testing →</button></aside></div>
    <section className="grid gap-5 rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="rule-label text-ink/38">Academic honors</p><h2 className="mt-2 font-editorial text-2xl font-semibold">{academicHonors.length ? `${academicHonors.length} recorded` : "No honors recorded yet"}</h2><p className="mt-2 text-sm leading-6 text-ink/50">Academic recognition stays in Accomplishments, so the same achievement is never duplicated.</p>{academicHonors.slice(0, 3).map((honor) => <p key={honor.id} className="mt-2 text-sm font-semibold">{honor.title} <span className="font-normal text-ink/40">· {dateLabel(honor.date)}</span></p>)}</div><Link href="/accomplishments" className="inline-flex min-h-11 items-center font-bold text-forest">Open Accomplishments →</Link></section>
  </div>;
}

function ScoreCard({ title, score, parts, note }: { title: string; score: number; parts: string; note: string }) {
  return <div className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-5"><p className="rule-label text-forest">{title}</p><p className="mt-3 font-editorial text-4xl font-semibold">{score}</p><p className="mt-3 text-sm font-semibold">{parts}</p><p className="mt-3 text-xs leading-5 text-ink/42">{note}</p></div>;
}

function Coursework({ store, courses, school, graduation, grade, pending, mutate }: { store: HighSchoolAcademicStore; courses: AcademicCourse[]; school?: string; graduation?: string; grade: number; pending: boolean; mutate: Mutation }) {
  const [context, setContext] = useState({ schoolName: school ?? "", graduationYear: graduation ?? "", gradeLevel: String(grade) });
  const [gpa, setGpa] = useState({ status: store.gpaStatus, kind: "unweighted", value: "", scale: "4.0" });
  const [rank, setRank] = useState({ kind: store.classRank?.kind ?? "unknown", rank: "", classSize: "", percentile: "" });
  const blankCourse = { id: "", version: "", name: "", subject: "", gradeLevel: String(grade), level: "standard", levelLabel: "", gradeSystem: "letter", grade: "", credits: "", inProgress: true };
  const [course, setCourse] = useState(blankCourse);
  return <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_21rem] lg:items-start"><section><div className="flex items-end justify-between gap-4 border-b border-ink/10 pb-4"><div><p className="rule-label text-ink/38">Course history</p><h2 className="mt-2 font-editorial text-3xl font-semibold">What you have studied</h2></div><span className="text-sm font-bold text-forest">{courses.length} recorded</span></div>{[12,11,10,9].map((year) => { const items = courses.filter((item) => item.gradeLevel === year); return items.length ? <section key={year} className="mt-7"><h3 className="rule-label text-forest">{year}th grade</h3><div className="mt-3 divide-y divide-ink/10 border-y border-ink/10">{items.map((item) => <div key={item.id} className="grid gap-3 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-editorial text-xl font-semibold">{item.name}</p><p className="mt-1 text-xs text-ink/45">{item.subject} · {item.levelLabel || courseLevelLabels[item.level]} · {item.inProgress ? "In progress" : item.grade || "Grade not recorded"}</p></div><div className="flex gap-3 text-xs font-bold"><button type="button" onClick={() => setCourse({ id: item.id, version: String(item.version), name: item.name, subject: item.subject, gradeLevel: String(item.gradeLevel), level: item.level, levelLabel: item.levelLabel ?? "", gradeSystem: item.gradeSystem, grade: item.grade ?? "", credits: item.credits ?? "", inProgress: item.inProgress })} className="min-h-10 text-forest">Edit</button><button type="button" disabled={pending} onClick={() => void mutate({ action: "delete_course", courseId: item.id, expectedRecordVersion: item.version })} className="min-h-10 text-ink/40">Remove</button></div></div>)}</div></section> : null; })}{!courses.length ? <p className="mt-6 rounded-2xl border border-ink/10 p-6 text-sm leading-6 text-ink/50">No courses recorded yet.</p> : null}</section>
    <aside className="space-y-4 lg:sticky lg:top-28"><details open className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-5"><summary className="cursor-pointer font-bold">Add or edit a course</summary><form className="mt-5 grid gap-3" onSubmit={async (event) => { event.preventDefault(); if (await mutate({ action: "save_course", idempotencyKey: crypto.randomUUID(), courseId: course.id || undefined, expectedRecordVersion: course.id ? Number(course.version) : undefined, ...course, gradeLevel: Number(course.gradeLevel) })) setCourse(blankCourse); }}><input required placeholder="Course name" value={course.name} onChange={(e) => setCourse({...course,name:e.target.value})} className={inputClass}/><input required placeholder="Subject" value={course.subject} onChange={(e) => setCourse({...course,subject:e.target.value})} className={inputClass}/><div className="grid grid-cols-2 gap-2"><select value={course.gradeLevel} onChange={(e)=>setCourse({...course,gradeLevel:e.target.value})} className={inputClass}>{[9,10,11,12].map(y=><option key={y} value={y}>{y}th grade</option>)}</select><select value={course.level} onChange={(e)=>setCourse({...course,level:e.target.value})} className={inputClass}>{Object.entries(courseLevelLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{["other","advanced_school_specific"].includes(course.level) ? <input placeholder="School-specific level" value={course.levelLabel} onChange={(e)=>setCourse({...course,levelLabel:e.target.value})} className={inputClass}/> : null}<div className="grid grid-cols-2 gap-2"><select value={course.gradeSystem} onChange={(e)=>setCourse({...course,gradeSystem:e.target.value})} className={inputClass}>{Object.entries(gradeSystemLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input placeholder="Grade" disabled={course.inProgress} value={course.grade} onChange={(e)=>setCourse({...course,grade:e.target.value})} className={inputClass}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={course.inProgress} onChange={(e)=>setCourse({...course,inProgress:e.target.checked})}/> Currently in progress</label><button disabled={pending} className="min-h-11 rounded-xl bg-forest text-sm font-bold text-white">{pending ? "Saving…" : course.id ? "Save changes" : "Add course"}</button></form></details>
      <details className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-5"><summary className="cursor-pointer font-bold">School &amp; GPA context</summary><form className="mt-5 grid gap-3" onSubmit={(e)=>{e.preventDefault();void mutate({action:"save_context",...context,gradeLevel:Number(context.gradeLevel)});}}><input placeholder="High school" value={context.schoolName} onChange={e=>setContext({...context,schoolName:e.target.value})} className={inputClass}/><div className="grid grid-cols-2 gap-2"><input inputMode="numeric" placeholder="Graduation year" value={context.graduationYear} onChange={e=>setContext({...context,graduationYear:e.target.value})} className={inputClass}/><select value={context.gradeLevel} onChange={e=>setContext({...context,gradeLevel:e.target.value})} className={inputClass}>{[9,10,11,12].map(y=><option key={y} value={y}>{y}th grade</option>)}</select></div><button disabled={pending} className="min-h-11 rounded-xl border border-forest/20 text-sm font-bold text-forest">Save school context</button></form><form className="mt-6 grid gap-3 border-t border-ink/10 pt-5" onSubmit={(e)=>{e.preventDefault();void mutate({action:"save_gpa",gpaStatus:gpa.status,kind:gpa.kind,value:gpa.value,scale:gpa.scale});}}><select value={gpa.status} onChange={e=>setGpa({...gpa,status:e.target.value as typeof gpa.status})} className={inputClass}><option value="unknown">GPA not reported</option><option value="reported">Record a GPA</option><option value="school_does_not_calculate">School does not calculate GPA</option></select>{gpa.status === "reported" ? <><select value={gpa.kind} onChange={e=>setGpa({...gpa,kind:e.target.value})} className={inputClass}><option value="unweighted">Unweighted</option><option value="weighted">Weighted</option><option value="school_reported">School-reported / unspecified</option></select><div className="grid grid-cols-2 gap-2"><input required inputMode="decimal" placeholder="GPA" value={gpa.value} onChange={e=>setGpa({...gpa,value:e.target.value})} className={inputClass}/><input required inputMode="decimal" placeholder="Scale" value={gpa.scale} onChange={e=>setGpa({...gpa,scale:e.target.value})} className={inputClass}/></div></> : null}<button disabled={pending} className="min-h-11 rounded-xl border border-forest/20 text-sm font-bold text-forest">Save GPA context</button></form></details>
      <details className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-5"><summary className="cursor-pointer font-bold">Class rank</summary><form className="mt-5 grid gap-3" onSubmit={(e)=>{e.preventDefault();void mutate({action:"save_rank",...rank,rank:Number(rank.rank),classSize:Number(rank.classSize),percentile:Number(rank.percentile)});}}><select value={rank.kind} onChange={e=>setRank({...rank,kind:e.target.value as typeof rank.kind})} className={inputClass}><option value="unknown">Unknown</option><option value="exact">Exact rank</option><option value="percentile">Percentile</option><option value="school_does_not_rank">School does not rank</option></select>{rank.kind === "exact" ? <div className="grid grid-cols-2 gap-2"><input placeholder="Rank" inputMode="numeric" value={rank.rank} onChange={e=>setRank({...rank,rank:e.target.value})} className={inputClass}/><input placeholder="Class size" inputMode="numeric" value={rank.classSize} onChange={e=>setRank({...rank,classSize:e.target.value})} className={inputClass}/></div> : rank.kind === "percentile" ? <input placeholder="Top percentile" inputMode="decimal" value={rank.percentile} onChange={e=>setRank({...rank,percentile:e.target.value})} className={inputClass}/> : null}<button disabled={pending} className="min-h-11 rounded-xl border border-forest/20 text-sm font-bold text-forest">Save rank context</button></form></details></aside>
  </div>;
}

function Testing({ store, pending, mutate, collegeContexts }: { store: HighSchoolAcademicStore; pending: boolean; mutate: Mutation; collegeContexts: CollegeContext[] }) {
  const [sat, setSat] = useState({ testDate:"",total:"",readingWriting:"",math:"",source:"student_reported" });
  const [act, setAct] = useState({ testDate:"",composite:"",english:"",math:"",reading:"",science:"",writing:"",source:"student_reported" });
  const [plan, setPlan] = useState({ test:"sat",date:"",registrationStatus:"planning",preparationDate:"" });
  const [satGoal, setSatGoal] = useState(String(store.testing.sat.goal ?? ""));
  const [actGoal, setActGoal] = useState(String(store.testing.act.goal ?? ""));
  return <div className="mt-8 space-y-6"><section className="grid gap-5 rounded-[1.75rem] bg-ink p-6 text-white sm:p-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="rule-label text-mint">SAT Practice</p><h2 className="mt-3 font-editorial text-3xl font-semibold">Practice, understand, review.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/55">Target current Digital SAT skills without mixing practice performance into your official score history.</p></div><Link href="/academics/sat" className="inline-flex min-h-11 items-center justify-center rounded-full bg-white px-5 text-sm font-bold text-forest">Open SAT Practice →</Link></section><section className="grid gap-5 lg:grid-cols-2"><AttemptPanel title="SAT" subtitle="Digital SAT · Reading and Writing + Math" attempts={store.testing.sat.officialAttempts} render={(item: SatAttempt) => `${item.total} · R&W ${item.readingWriting} · Math ${item.math}`} remove={(item: SatAttempt) => mutate({action:"delete_sat_attempt",attemptId:item.id,expectedRecordVersion:item.version})}/><AttemptPanel title="ACT" subtitle="Composite · English + Math + Reading" attempts={store.testing.act.officialAttempts} render={(item: ActAttempt) => `${item.composite} · E ${item.english} · M ${item.math} · R ${item.reading}${item.science ? ` · S ${item.science}` : ""}`} remove={(item: ActAttempt) => mutate({action:"delete_act_attempt",attemptId:item.id,expectedRecordVersion:item.version})}/></section>
    <section className="grid gap-5 lg:grid-cols-3"><details className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-5"><summary className="cursor-pointer font-bold">Record official SAT</summary><form className="mt-5 grid gap-3" onSubmit={async(e)=>{e.preventDefault();if(await mutate({action:"save_sat_attempt",idempotencyKey:crypto.randomUUID(),...sat,total:Number(sat.total),readingWriting:Number(sat.readingWriting),math:Number(sat.math)}))setSat({testDate:"",total:"",readingWriting:"",math:"",source:"student_reported"});}}><input required type="date" aria-label="SAT test date" value={sat.testDate} onChange={e=>setSat({...sat,testDate:e.target.value})} className={inputClass}/><div className="grid grid-cols-3 gap-2"><input required inputMode="numeric" placeholder="Total" value={sat.total} onChange={e=>setSat({...sat,total:e.target.value})} className={inputClass}/><input required inputMode="numeric" placeholder="R&W" value={sat.readingWriting} onChange={e=>setSat({...sat,readingWriting:e.target.value})} className={inputClass}/><input required inputMode="numeric" placeholder="Math" value={sat.math} onChange={e=>setSat({...sat,math:e.target.value})} className={inputClass}/></div><SourceSelect value={sat.source} set={(source)=>setSat({...sat,source})}/><button disabled={pending} className="min-h-11 rounded-xl bg-forest text-sm font-bold text-white">Save SAT attempt</button></form></details>
      <details className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-5"><summary className="cursor-pointer font-bold">Record official ACT</summary><form className="mt-5 grid gap-3" onSubmit={async(e)=>{e.preventDefault();if(await mutate({action:"save_act_attempt",idempotencyKey:crypto.randomUUID(),...act,composite:Number(act.composite),english:Number(act.english),math:Number(act.math),reading:Number(act.reading)}))setAct({testDate:"",composite:"",english:"",math:"",reading:"",science:"",writing:"",source:"student_reported"});}}><input required type="date" aria-label="ACT test date" value={act.testDate} onChange={e=>setAct({...act,testDate:e.target.value})} className={inputClass}/><div className="grid grid-cols-2 gap-2">{(["composite","english","math","reading","science","writing"] as const).map(key=><input key={key} required={!(["science","writing"] as string[]).includes(key)} inputMode="numeric" placeholder={key[0].toUpperCase()+key.slice(1)} value={act[key]} onChange={e=>setAct({...act,[key]:e.target.value})} className={inputClass}/>)}</div><p className="text-xs leading-5 text-ink/42">Science and Writing are optional. The current Composite uses English, Math, and Reading.</p><SourceSelect value={act.source} set={(source)=>setAct({...act,source})}/><button disabled={pending} className="min-h-11 rounded-xl bg-forest text-sm font-bold text-white">Save ACT attempt</button></form></details>
      <div className="space-y-5"><details open className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-5"><summary className="cursor-pointer font-bold">Plan a test date</summary><form className="mt-5 grid gap-3" onSubmit={(e)=>{e.preventDefault();void mutate({action:"save_test_plan",...plan});}}><div className="grid grid-cols-2 gap-2"><select value={plan.test} onChange={e=>setPlan({...plan,test:e.target.value})} className={inputClass}><option value="sat">SAT</option><option value="act">ACT</option></select><select value={plan.registrationStatus} onChange={e=>setPlan({...plan,registrationStatus:e.target.value})} className={inputClass}><option value="planning">Planning</option><option value="registered">Registered</option><option value="completed">Completed</option></select></div><input required type="date" aria-label="Test date" value={plan.date} onChange={e=>setPlan({...plan,date:e.target.value})} className={inputClass}/><label className="text-xs font-bold text-ink/45">Personal preparation date<input type="date" value={plan.preparationDate} onChange={e=>setPlan({...plan,preparationDate:e.target.value})} className={`${inputClass} mt-1`}/></label><button disabled={pending} className="min-h-11 rounded-xl border border-forest/20 text-sm font-bold text-forest">Save test plan</button></form></details><div className="rounded-2xl border border-ink/10 bg-mint/35 p-5"><p className="text-sm font-bold">Official resources</p><div className="mt-3 grid gap-2 text-sm font-bold text-forest"><a href="https://satsuite.collegeboard.org/sat" target="_blank" rel="noreferrer">College Board SAT →</a><a href="https://www.act.org/content/act/en/products-and-services/the-act.html" target="_blank" rel="noreferrer">ACT registration and resources →</a></div></div></div></section>
    <section className="grid gap-5 rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-6 sm:grid-cols-2"><GoalForm test="sat" value={satGoal} set={setSatGoal} pending={pending} mutate={mutate}/><GoalForm test="act" value={actGoal} set={setActGoal} pending={pending} mutate={mutate}/><p className="text-xs leading-5 text-ink/42 sm:col-span-2">These are goals you choose—not scores UnlockED says a college requires.</p></section>
    {collegeContexts.length ? <section className="rounded-2xl border border-ink/10 bg-[var(--unlocked-surface)] p-6"><p className="rule-label text-ink/38">My colleges</p><h2 className="mt-2 font-editorial text-2xl font-semibold">Verified testing context</h2><p className="mt-2 text-xs leading-5 text-ink/45">Policies are current only when verified from an institution. Score ranges describe a reported cohort, not a required score.</p><div className="mt-5 divide-y divide-ink/10 border-y border-ink/10">{collegeContexts.map((college) => <Link key={college.id} href={`/colleges/${college.slug}`} className="grid gap-2 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><span><strong className="block text-sm">{college.name}</strong><small className="mt-1 block text-xs text-ink/42">{college.policy}{college.policyVerified ? " · Verified" : ""}</small></span><small className="text-xs font-semibold text-ink/48">{college.satRange ? `SAT ${college.satRange[0]}–${college.satRange[1]}` : college.actRange ? `ACT ${college.actRange[0]}–${college.actRange[1]}` : "No score range available"}</small></Link>)}</div></section> : null}
    <section className="rounded-2xl border border-dashed border-ink/15 p-6"><p className="rule-label text-ink/35">Practice foundation</p><h2 className="mt-2 font-editorial text-2xl font-semibold">Practice will live here later.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-ink/48">Practice questions, tests, and review will remain separate from official score history. No generated question bank has been added.</p></section>
  </div>;
}

function SourceSelect({ value, set }: { value: string; set: (value: string) => void }) { return <select value={value} onChange={e=>set(e.target.value)} className={inputClass}><option value="student_reported">Student-reported</option><option value="official_score_report">Copied from official score report</option></select>; }

function GoalForm({ test, value, set, pending, mutate }: { test: "sat" | "act"; value: string; set: (value: string) => void; pending: boolean; mutate: Mutation }) { return <form onSubmit={(e)=>{e.preventDefault();void mutate({action:"save_test_goal",test,goal:value});}}><label className="rule-label text-ink/38">{test.toUpperCase()} goal<input inputMode="numeric" placeholder="Optional" value={value} onChange={e=>set(e.target.value)} className={`${inputClass} mt-3`}/></label><button disabled={pending} className="mt-3 min-h-11 rounded-xl bg-ink px-5 text-sm font-bold text-white">Save {test.toUpperCase()} goal</button></form>; }

function AttemptPanel<T extends { id: string; testDate: string; source: string }>({ title, subtitle, attempts, render, remove }: { title: string; subtitle: string; attempts: T[]; render: (item: T) => string; remove: (item: T) => Promise<boolean> }) { return <section className="rounded-[1.75rem] border border-ink/10 bg-[var(--unlocked-surface)] p-6"><p className="rule-label text-forest">Official scores</p><div className="mt-2 flex items-end justify-between"><div><h2 className="font-editorial text-3xl font-semibold">{title}</h2><p className="mt-1 text-xs text-ink/42">{subtitle}</p></div><span className="text-xs font-bold text-ink/35">{attempts.length} attempt{attempts.length === 1 ? "" : "s"}</span></div><div className="mt-5 divide-y divide-ink/10 border-y border-ink/10">{attempts.map(item=><div key={item.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-bold">{render(item)}</p><p className="mt-1 text-xs text-ink/40">{dateLabel(item.testDate)} · {item.source === "official_score_report" ? "Copied from official report" : "Student-reported"}</p></div><button type="button" onClick={()=>void remove(item)} className="min-h-10 text-xs font-bold text-ink/38 hover:text-red-700">Remove</button></div>)}{!attempts.length ? <p className="py-5 text-sm text-ink/45">No official attempts recorded.</p> : null}</div></section>; }
