import Link from "next/link";
import type { HighSchoolHomeItem, HighSchoolHomeSummary } from "@/lib/high-school-home";

const dateLabel=(value:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${value}T12:00:00Z`));

export function HighSchoolHome({summary}:{summary:HighSchoolHomeSummary}) {
  if(summary.empty)return <EmptyHighSchoolHome firstName={summary.firstName}/>;
  return <main id="main-content" className="min-h-[calc(100vh-5rem)] px-5 pb-28 pt-10 sm:px-8 sm:pb-16 sm:pt-14">
    <div className="mx-auto max-w-6xl">
      <header className="max-w-3xl"><p className="rule-label text-forest">High school</p><h1 className="mt-4 font-editorial text-5xl font-semibold leading-[1.02] sm:text-6xl">{summary.greeting}, {summary.firstName}.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-ink/52">{summary.context}</p></header>
      <section aria-labelledby="home-next" className="relative mt-9 overflow-hidden rounded-[1.75rem] bg-ink px-6 py-7 text-white sm:px-9 sm:py-9"><div aria-hidden="true" className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-mint/50 to-transparent"/><p className="rule-label text-mint">Your next step</p><div className="mt-4 grid gap-6 sm:grid-cols-[1fr_auto] sm:items-end"><div><h2 id="home-next" className="font-editorial text-3xl font-semibold sm:text-4xl">{summary.next.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">{summary.next.detail}</p></div><Link href={summary.next.href} className="inline-flex min-h-11 items-center justify-center rounded-full bg-white px-5 text-sm font-bold text-forest transition hover:bg-mint focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-mint">Open next step →</Link></div></section>
      {summary.comingUp.length?<section aria-labelledby="coming-up" className="mt-10"><div className="flex items-end justify-between border-b border-ink/10 pb-3"><div><p className="rule-label text-ink/38">Coming up</p><h2 id="coming-up" className="sr-only">Coming up</h2></div><Link href="/admissions" className="min-h-10 text-sm font-bold text-forest">View Journey →</Link></div><div className="divide-y divide-ink/10">{summary.comingUp.map(item=><DatedRow key={item.id} item={item}/>)}</div></section>:null}
      {summary.continuing.length?<section aria-labelledby="continue" className="mt-10"><p className="rule-label text-ink/38">Continue</p><h2 id="continue" className="sr-only">Continue recent work</h2><div className="mt-3 grid border-y border-ink/10 sm:grid-cols-3">{summary.continuing.map((item,index)=><Link key={item.id} href={item.href} className={`group py-5 sm:px-5 ${index?"border-t border-ink/10 sm:border-l sm:border-t-0":""}`}><p className="text-[10px] font-bold uppercase tracking-[.12em] text-forest/70">{item.label}</p><h3 className="mt-2 font-editorial text-xl font-semibold group-hover:text-forest">{item.title}</h3><p className="mt-2 text-xs leading-5 text-ink/45">{item.detail}</p></Link>)}</div></section>:null}
      <div className="mt-12 grid gap-x-10 gap-y-9 lg:grid-cols-2">
        {summary.decisionSeason?<QuietSection label="Decision Season" title={`${summary.decisionSeason.accepted} accepted · ${summary.decisionSeason.waitlisted} waitlisted · ${summary.decisionSeason.pending} pending`} detail={summary.decisionSeason.notAdmitted?`${summary.decisionSeason.notAdmitted} not admitted · your complete history remains private.`:"Compare facts, aid, visits, and your own priorities."} href={summary.decisionSeason.href} action="Open Decision Season"/>:null}
        {summary.colleges?<QuietSection label="Colleges" title={`${summary.colleges.saved} saved · ${summary.colleges.planning} planning to apply`} detail={`${summary.colleges.active} ${summary.colleges.active===1?'application needs':'applications need'} attention`} href="/colleges/saved" action="Open My College List" rows={summary.colleges.attention}/>:null}
        {summary.sat?<QuietSection label="SAT" title={summary.sat.nextTest?`Next test ${dateLabel(summary.sat.nextTest)}`:"Preparation in progress"} detail={[summary.sat.latestBluebook?`Latest Bluebook ${summary.sat.latestBluebook}`:null,summary.sat.focus?`Recent focus: ${summary.sat.focus}`:null,summary.sat.mistakes?`${summary.sat.mistakes} mistakes to review`:null].filter(Boolean).join(" · ")||"Your practice history and resources are ready."} href="/academics/sat" action="Continue SAT"/>:null}
        {summary.opportunities?<QuietSection label="Opportunities" title={`${summary.opportunities.active} active ${summary.opportunities.active===1?'pursuit':'pursuits'}`} detail={summary.opportunities.next?.date?`${summary.opportunities.next.title} · deadline ${dateLabel(summary.opportunities.next.date)}`:"Continue from your Journey when you are ready."} href="/advisor" action="Open For You"/>:null}
        {summary.build?<QuietSection label="Build" title={`${summary.build.count} ${summary.build.count===1?'experience':'experiences'} recorded`} detail={summary.build.reason} href={summary.build.href} action="Open experience"/>:null}
        {summary.financialAid?<QuietSection label="Cost & Aid" title={`${summary.financialAid.offers} offers · ${summary.financialAid.estimates} calculator estimates`} detail={summary.financialAid.formsToReview?`${summary.financialAid.formsToReview} FAFSA preparation items to review`:"Your FAFSA preparation list is reviewed."} href={summary.financialAid.href} action="Open Cost & Aid"/>:null}
      </div>
    </div>
  </main>;
}

function DatedRow({item}:{item:HighSchoolHomeItem}) { return <Link href={item.href} className="grid grid-cols-[4.5rem_1fr_auto] items-center gap-3 py-4 hover:text-forest"><time className="font-editorial text-lg font-semibold text-forest">{dateLabel(item.date!)}</time><span><strong className="block text-sm">{item.title}</strong><small className="mt-1 block text-xs text-ink/45">{item.detail}</small></span><small className="hidden rounded-full bg-ink/[.04] px-2 py-1 text-[10px] font-bold text-ink/42 sm:block">{item.provenance}</small></Link>; }

function QuietSection({label,title,detail,href,action,rows=[]}:{label:string;title:string;detail:string;href:string;action:string;rows?:Array<{name:string;detail:string;href:string}>}) { return <section className="border-t border-ink/10 pt-5"><p className="rule-label text-forest">{label}</p><h2 className="mt-3 font-editorial text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-ink/50">{detail}</p>{rows.length?<div className="mt-4 divide-y divide-ink/10">{rows.map(row=><Link key={row.href} href={row.href} className="flex justify-between gap-3 py-3 text-sm"><strong>{row.name}</strong><span className="text-right text-xs text-ink/45">{row.detail}</span></Link>)}</div>:null}<Link href={href} className="mt-3 inline-flex min-h-11 items-center text-sm font-bold text-forest">{action} →</Link></section>; }

function EmptyHighSchoolHome({firstName}:{firstName:string}) { return <main id="main-content" className="min-h-[calc(100vh-5rem)] px-5 py-12 sm:px-8 sm:py-20"><div className="mx-auto max-w-5xl"><p className="rule-label text-forest">Welcome to UnlockED</p><h1 className="mt-4 max-w-3xl font-editorial text-5xl font-semibold leading-[1.02] sm:text-6xl">Start somewhere useful, {firstName}.</h1><p className="mt-5 max-w-xl text-base leading-7 text-ink/52">You do not need a complete plan. Choose the question that feels most useful today.</p><div className="mt-10 grid border-y border-ink/10 sm:grid-cols-3"><StartPath label="Explore colleges" detail="Understand schools, programs, cost, and admissions context." href="/colleges"/><StartPath label="Find opportunities" detail="Discover programs and experiences available to high-school students." href="/opportunities"/><StartPath label="Set up academics" detail="Record coursework, testing plans, or learn how the SAT works." href="/academics"/></div><p className="mt-8 text-sm text-ink/45">Not sure yet? Browse freely. UnlockED becomes more specific as you save real work.</p></div></main>; }
function StartPath({label,detail,href}:{label:string;detail:string;href:string}) { return <Link href={href} className="group py-6 sm:px-6 sm:first:pl-0"><h2 className="font-editorial text-2xl font-semibold group-hover:text-forest">{label}</h2><p className="mt-2 text-sm leading-6 text-ink/50">{detail}</p><span className="mt-4 inline-flex min-h-10 items-center text-sm font-bold text-forest">Open →</span></Link>; }
