"use client";

import { useMemo, useState } from "react";
import { filterOpportunities, opportunities, opportunityTypes, type OpportunityType } from "@/data/opportunities";
import { schools, type School } from "@/data/seed";
import { findSchoolMatches, normalizeSchoolQuery } from "@/data/school-search";
import { OpportunityCard } from "./opportunity-card";
import { SearchIcon } from "./icons";

export function OpportunityFilter() {
  const [query,setQuery]=useState(""); const [type,setType]=useState<OpportunityType|"All">("All"); const [major,setMajor]=useState("All"); const [school,setSchool]=useState("All"); const [year,setYear]=useState("All"); const [paid,setPaid]=useState("All"); const [remote,setRemote]=useState("All"); const [deadline,setDeadline]=useState("All"); const [featured,setFeatured]=useState(false); const [hiddenGem,setHiddenGem]=useState(false); const [showAll,setShowAll]=useState(false);
  const majors=["All",...new Set(opportunities.flatMap((item)=>item.majors).filter((item)=>item!=="Any Major"))];
  const years=["All",...new Set(opportunities.flatMap((item)=>item.academic_years).filter((item)=>item!=="Any Year"))];
  const visible=useMemo(()=>filterOpportunities({query,types:type==="All"?undefined:[type],major,school:school==="All"?undefined:school,academicYear:year,paid:paid==="All"?undefined:paid==="Paid",remote:remote==="All"?undefined:remote==="Remote",deadline:deadline==="All"?undefined:deadline as "published"|"upcoming"|"rolling"|"not_announced",featured:featured?true:undefined,hiddenGem:hiddenGem?true:undefined}),[deadline,featured,hiddenGem,major,paid,query,remote,school,type,year]);
  const displayed=showAll?visible:visible.slice(0,18);
  return <>
    <div className="border-2 border-ink bg-white"><label className="flex h-14 items-center gap-3 px-4"><SearchIcon className="h-4 w-4 text-ink/40"/><span className="sr-only">Search all opportunities</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search titles, organizations, or skills" className="min-w-0 flex-1 bg-transparent outline-none"/></label><div className="grid border-t border-ink/20 sm:grid-cols-2 lg:grid-cols-4"><Select label="Type" value={type} setValue={(value)=>setType(value as OpportunityType|"All")} options={["All",...opportunityTypes]}/><Select label="Major" value={major} setValue={setMajor} options={majors}/><SchoolFilter value={school} setValue={setSchool}/><Select label="Year" value={year} setValue={setYear} options={years}/><Select label="Paid" value={paid} setValue={setPaid} options={["All","Paid","Unpaid"]}/><Select label="Remote" value={remote} setValue={setRemote} options={["All","Remote","In Person"]}/><Select label="Deadline" value={deadline} setValue={setDeadline} options={["All","published","upcoming","rolling","not_announced"]}/><div className="flex min-h-14 flex-wrap items-center gap-5 border-t border-ink/20 px-4 sm:border-l"><label className="py-3 text-xs font-bold"><input type="checkbox" checked={featured} onChange={(event)=>setFeatured(event.target.checked)} className="mr-2"/>Featured</label><label className="py-3 text-xs font-bold"><input type="checkbox" checked={hiddenGem} onChange={(event)=>setHiddenGem(event.target.checked)} className="mr-2"/>Hidden gems</label></div></div></div>
    <div className="mt-8 flex items-end justify-between gap-4 border-b-2 border-ink pb-4"><div><p className="rule-label text-forest">Verified directory</p><h2 className="mt-2 font-editorial text-3xl font-bold">Opportunities matching your criteria</h2></div><p className="shrink-0 text-sm font-bold text-ink/45">{visible.length} results</p></div><div className="border-b-2 border-ink">{displayed.map((item)=><OpportunityCard key={item.id} opportunity={item}/>)}</div>{visible.length>displayed.length&&<div className="border-b-2 border-ink bg-white py-6 text-center"><button onClick={()=>setShowAll(true)} className="min-h-11 border-2 border-ink px-6 text-xs font-bold uppercase tracking-wider hover:bg-ink hover:text-white">View all {visible.length} opportunities</button></div>}{!visible.length&&<div className="border-b-2 border-ink bg-white py-12 text-center"><p className="font-editorial text-2xl font-bold">No verified matches yet</p><p className="mt-2 text-sm text-ink/45">Try clearing one filter or using a broader search term.</p></div>}
  </>;
}

function SchoolFilter({value,setValue}:{value:string;setValue:(value:string)=>void}){
  const selected=schools.find((item)=>item.slug===value);const[query,setQuery]=useState(selected?.name??"");const[open,setOpen]=useState(false);const matches=useMemo(()=>findSchoolMatches(schools,query,6),[query]);const normalized=normalizeSchoolQuery(query);
  function choose(item:School){setValue(item.slug);setQuery(item.name);setOpen(false)}
  return <div className="relative border-t border-ink/20 px-4 sm:border-l"><label className="flex h-14 items-center justify-between gap-3"><span className="rule-label text-ink/40">School</span><input value={query} onFocus={()=>setOpen(true)} onChange={(event)=>{setQuery(event.target.value);setValue("All");setOpen(true)}} placeholder="All schools" className="min-w-0 max-w-[70%] bg-transparent text-right text-sm font-bold outline-none placeholder:text-ink/35"/></label>{open&&normalized&&<div className="absolute left-0 right-0 z-30 border-2 border-ink bg-white shadow-[4px_4px_0_#10243e]">{matches.length?matches.map((item)=><button key={item.slug} type="button" onMouseDown={(event)=>event.preventDefault()} onClick={()=>choose(item)} className="block w-full border-b border-ink/15 px-3 py-2 text-left text-sm font-bold last:border-b-0 hover:bg-paper">{item.name}<span className="block text-[11px] font-normal text-ink/40">{item.domain}</span></button>):<p className="px-3 py-3 text-xs text-ink/50">School not found</p>}</div>}</div>
}

function Select({label,value,setValue,options}:{label:string;value:string;setValue:(value:string)=>void;options:readonly string[]}){const allLabels:Record<string,string>={Type:"All types",Major:"All majors",Year:"All years",Paid:"Any compensation",Remote:"Any format",Deadline:"Any deadline"};return <label className="flex h-14 items-center justify-between gap-3 border-t border-ink/20 px-4 sm:border-l"><span className="rule-label text-ink/40">{label}</span><select value={value} onChange={(event)=>setValue(event.target.value)} className="min-w-0 max-w-[70%] bg-transparent text-sm font-bold outline-none">{options.map((option)=><option key={option} value={option}>{option==="All"?allLabels[label]:option.replaceAll("_"," ")}</option>)}</select></label>}
