"use client";

import { useEffect, useMemo, useState } from "react";
import type { OpportunityPassport, PassportManualEvent } from "@/data/passport";
import type { PassportView } from "@/lib/passport";
import { PassportDocument } from "./passport-view";
import { ArrowIcon } from "./icons";
import styles from "./opportunity-passport.module.css";

type Choice = { id: string; title: string; organization?: string; source: "accomplishment" | "experience" };
type OpportunityChoice = { id: string; title: string; organization: string; type: string };

export function OpportunityPassportWorkspace({ initialModel, initialConfig, opportunityChoices }: { initialModel: PassportView; initialConfig: OpportunityPassport; opportunityChoices: OpportunityChoice[] }) {
  const [config, setConfig] = useState(initialConfig); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [shareOpen, setShareOpen] = useState(false); const [cardItem, setCardItem] = useState(initialModel.highlights[0]?.id || initialModel.accomplishments[0]?.id || ""); const [cardFormat, setCardFormat] = useState<"square" | "story" | "landscape">("square"); const [cardTheme, setCardTheme] = useState<"light" | "dark" | "editorial">("light");
  const [stats, setStats] = useState({ views: 0, opportunityClicks: 0 });
  useEffect(() => { if (!config.sharingEnabled) return; void fetch("/api/passport", { credentials: "same-origin" }).then((response) => response.ok ? response.json() : null).then((result) => { if (result?.stats) setStats({ views: result.stats.views ?? 0, opportunityClicks: result.stats.opportunityClicks ?? 0 }); }).catch(() => undefined); }, [config.sharingEnabled]);
  const choices: Choice[] = useMemo(() => [...initialModel.accomplishments.map((item) => ({ id: item.id, title: item.title, organization: item.organization, source: "accomplishment" as const })), ...[...initialModel.projects, ...initialModel.experiences].map((item) => ({ id: item.id, title: item.title, organization: item.organization, source: "experience" as const }))], [initialModel]);
  const previewModel = useMemo((): PassportView => {
    const manual = config.manualEvents.map((item) => ({ id: item.id, source: "student" as const, kind: item.kind, title: item.title, organization: item.organization, date: item.date, description: item.description, skills: item.skills }));
    const candidates = [...initialModel.accomplishments, ...initialModel.projects, ...initialModel.experiences, ...manual];
    return { ...initialModel, identity: { ...initialModel.identity, headline: config.headline, school: config.showSchool ? initialModel.identity.school : undefined, major: config.showAcademicDetails ? initialModel.identity.major : undefined, secondaryMajor: config.showAcademicDetails ? initialModel.identity.secondaryMajor : undefined, minor: config.showAcademicDetails ? initialModel.identity.minor : undefined, graduationYear: config.showAcademicDetails ? initialModel.identity.graduationYear : undefined, careerInterests: config.showCareerInterests ? initialModel.identity.careerInterests : [] }, highlights: config.highlightIds.flatMap((id) => candidates.find((item) => item.id === id) ?? []).slice(0, 6), timeline: [...initialModel.timeline, ...manual].sort((a, b) => b.date.localeCompare(a.date)), updatedAt: config.updatedAt };
  }, [config, initialModel]);
  const selectedCard = [...initialModel.accomplishments, ...initialModel.projects, ...initialModel.experiences, ...config.manualEvents.map((item) => ({ ...item, source: "student" as const }))].find((item) => item.id === cardItem);
  const patch = (value: Partial<OpportunityPassport>) => setConfig((current) => ({ ...current, ...value }));
  const toggle = (field: "visibleAccomplishmentIds" | "visibleExperienceIds" | "highlightIds", id: string, maximum = 100) => setConfig((current) => ({ ...current, [field]: current[field].includes(id) ? current[field].filter((item) => item !== id) : [...current[field], id].slice(0, maximum) }));
  async function save(nextConfig = config) { setSaving(true); setMessage(""); try { const response = await fetch("/api/passport", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ passport: nextConfig }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Passport could not be saved."); setConfig(result.passport); setMessage(nextConfig.sharingEnabled ? "Passport published. Your privacy choices are live." : "Passport saved privately."); } catch (error) { setMessage(error instanceof Error ? error.message : "Passport could not be saved."); } finally { setSaving(false); } }
  async function copy(value: string) { await navigator.clipboard.writeText(new URL(value, window.location.origin).toString()); setMessage("Share link copied."); }
  function addEvent(form: FormData) { const title = String(form.get("title") || "").trim(); const date = String(form.get("date") || ""); if (!title || !date) return; const now = new Date().toISOString(); const event: PassportManualEvent = { id: `manual:${crypto.randomUUID()}`, title, organization: String(form.get("organization") || "").trim() || undefined, date, kind: String(form.get("kind") || "milestone") as PassportManualEvent["kind"], description: String(form.get("description") || "").trim() || undefined, skills: String(form.get("skills") || "").split(",").map((item) => item.trim()).filter(Boolean), visibility: form.get("visibility") === "passport" ? "passport" : "private", createdAt: now }; patch({ manualEvents: [...config.manualEvents, event] }); }
  function addCollection(form: FormData) { const title = String(form.get("title") || "").trim(); if (!title) return; const now = new Date().toISOString(); patch({ collections: [...config.collections, { id: `collection:${crypto.randomUUID()}`, title, description: String(form.get("description") || "").trim() || undefined, opportunityIds: [], sharingEnabled: false, createdAt: now, updatedAt: now }] }); }
  const selectedCardOutcome = selectedCard && "outcome" in selectedCard ? selectedCard.outcome : undefined;
  return <main className={styles.workspace} data-opportunity-passport=""><header className={styles.workspaceHeader}><div><p className={styles.eyebrow}>Opportunity Passport</p><h1>Your college journey, in one place.</h1><p>A private, living record of what you’ve explored, pursued, done, and built. You decide what leaves this page.</p>{config.sharingEnabled ? <p className={styles.helper}>{stats.views} public views · {stats.opportunityClicks} opportunity clicks · No visitor identities</p> : null}</div><div className={styles.topActions}><button type="button" onClick={() => setShareOpen(true)}>Preview & share</button><button type="button" className={styles.primary} disabled={saving} onClick={() => void save()}>{saving ? "Saving…" : "Save Passport"}</button></div></header>{message ? <p className={styles.status} role="status">{message}</p> : null}
    <div className={styles.workspaceGrid}><aside className={styles.editor} aria-label="Passport controls">
      <section><p className={styles.editorLabel}>Identity</p><label>Personal headline<input value={config.headline || ""} maxLength={160} placeholder="What are you curious about or building toward?" onChange={(event) => patch({ headline: event.target.value })}/></label><Toggle label="Show school" checked={config.showSchool} onChange={(checked) => patch({ showSchool: checked })}/><Toggle label="Show major and graduation year" checked={config.showAcademicDetails} onChange={(checked) => patch({ showAcademicDetails: checked })}/><Toggle label="Show saved career interests" checked={config.showCareerInterests} onChange={(checked) => patch({ showCareerInterests: checked })}/></section>
      <section><p className={styles.editorLabel}>Choose what appears</p><p className={styles.helper}>Nothing is public until you select it and enable sharing.</p>{choices.length ? choices.map((item) => { const field = item.source === "accomplishment" ? "visibleAccomplishmentIds" : "visibleExperienceIds"; return <div className={styles.choice} key={`${item.source}-${item.id}`}><label><input type="checkbox" checked={config[field].includes(item.id)} onChange={() => toggle(field, item.id)}/><span><strong>{item.title}</strong><small>{item.organization || item.source}</small></span></label><button type="button" data-selected={config.highlightIds.includes(item.id)} onClick={() => toggle("highlightIds", item.id, 6)}>{config.highlightIds.includes(item.id) ? "Highlighted" : "Highlight"}</button></div> }) : <p className={styles.helper}>Confirmed accomplishments and Experience Bank records will appear here.</p>}</section>
      <section><p className={styles.editorLabel}>Add a meaningful moment</p><form action={addEvent} className={styles.form}><input name="title" required placeholder="Project, role, publication, or milestone"/><input name="organization" placeholder="Organization (optional)"/><div><input name="date" required type="date"/><select name="kind" defaultValue="project"><option value="project">Project</option><option value="experience">Experience</option><option value="publication">Publication</option><option value="leadership">Leadership</option><option value="service">Service</option><option value="milestone">Other milestone</option></select></div><textarea name="description" placeholder="A short factual description"/><input name="skills" placeholder="Skills, separated by commas"/><label className={styles.visibility}><input type="checkbox" name="visibility" value="passport"/> Visible on shared Passport</label><button type="submit">Add to Passport</button></form>{config.manualEvents.map((item) => <div className={styles.manualRow} key={item.id}><span><strong>{item.title}</strong><small>{item.visibility === "passport" ? "Visible when shared" : "Private"}</small></span><button type="button" data-selected={config.highlightIds.includes(item.id)} onClick={() => toggle("highlightIds", item.id, 6)}>{config.highlightIds.includes(item.id) ? "Highlighted" : "Highlight"}</button><button type="button" onClick={() => patch({ manualEvents: config.manualEvents.filter((candidate) => candidate.id !== item.id), highlightIds: config.highlightIds.filter((id) => id !== item.id) })}>Remove</button></div>)}</section>
      <section><p className={styles.editorLabel}>Opportunity collections</p><form action={addCollection} className={styles.form}><input name="title" required placeholder="Freshman Quant Opportunities"/><textarea name="description" placeholder="Why this collection is useful"/><button type="submit">Create collection</button></form>{config.collections.map((collection) => <div className={styles.collectionEditor} key={collection.id}><input value={collection.title} aria-label="Collection title" onChange={(event) => patch({ collections: config.collections.map((item) => item.id === collection.id ? { ...item, title: event.target.value } : item) })}/><div className={styles.collectionChoices}>{opportunityChoices.map((opportunity) => <label key={opportunity.id}><input type="checkbox" checked={collection.opportunityIds.includes(opportunity.id)} onChange={() => patch({ collections: config.collections.map((item) => item.id === collection.id ? { ...item, opportunityIds: item.opportunityIds.includes(opportunity.id) ? item.opportunityIds.filter((id) => id !== opportunity.id) : [...item.opportunityIds, opportunity.id] } : item) })}/><span>{opportunity.title}</span></label>)}</div><Toggle label="Create a share link" checked={collection.sharingEnabled} onChange={(checked) => patch({ collections: config.collections.map((item) => item.id === collection.id ? { ...item, sharingEnabled: checked } : item) })}/>{collection.sharingEnabled && collection.shareToken ? <button type="button" onClick={() => void copy(`/c/${collection.shareToken}`)}>Copy collection link</button> : null}</div>)}</section>
    </aside><div className={styles.preview}><div className={styles.previewBar}><span>Private preview</span><span>{config.highlightIds.length}/6 highlights selected</span></div><PassportDocument model={previewModel}/></div></div>
    {shareOpen ? <div className={styles.modalBackdrop} role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setShareOpen(false); }}><section className={styles.shareModal} role="dialog" aria-modal="true" aria-labelledby="share-title"><button className={styles.close} type="button" onClick={() => setShareOpen(false)} aria-label="Close">×</button><p className={styles.eyebrow}>Privacy check</p><h2 id="share-title">Share only what you chose.</h2><p>{config.visibleAccomplishmentIds.length} accomplishments, {config.visibleExperienceIds.length} experiences, and {config.manualEvents.filter((item) => item.visibility === "passport").length} student-added moments will appear. Notes, drafts, tasks, recommendations, and private dates stay private.</p><Toggle label="Enable public Passport" checked={config.sharingEnabled} onChange={(checked) => patch({ sharingEnabled: checked })}/><div className={styles.shareActions}><button type="button" className={styles.primary} onClick={() => void save()}>{config.sharingEnabled ? "Publish changes" : "Save as private"}</button>{config.sharingEnabled && config.shareToken ? <button type="button" onClick={() => void copy(`/p/${config.shareToken}`)}>Copy Passport link</button> : null}</div><hr/><p className={styles.editorLabel}>Milestone share card</p><select value={cardItem} onChange={(event) => setCardItem(event.target.value)}><option value="">Choose a milestone</option>{choices.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><div className={styles.segmented}>{(["square", "story", "landscape"] as const).map((item) => <button type="button" data-active={cardFormat === item} onClick={() => setCardFormat(item)} key={item}>{item}</button>)}</div><div className={styles.segmented}>{(["light", "dark", "editorial"] as const).map((item) => <button type="button" data-active={cardTheme === item} onClick={() => setCardTheme(item)} key={item}>{item}</button>)}</div>{selectedCard ? <div className={styles.shareCard} data-format={cardFormat} data-theme={cardTheme}><p>{selectedCardOutcome || selectedCard.kind}</p><h3>{selectedCard.title}</h3>{selectedCard.organization ? <strong>{selectedCard.organization}</strong> : null}<span>{initialModel.identity.firstName}’s Journey</span><small>UnlockED</small></div> : null}{selectedCard && config.sharingEnabled && config.shareToken && (config.visibleAccomplishmentIds.includes(selectedCard.id) || config.visibleExperienceIds.includes(selectedCard.id)) ? <button type="button" onClick={() => void copy(`/p/${config.shareToken}?moment=${encodeURIComponent(selectedCard.id)}`)}>Copy milestone link</button> : <p className={styles.helper}>Publish this item on your Passport to create its safe milestone link.</p>}</section></div> : null}
  </main>;
}

function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className={styles.toggle}><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)}/><i aria-hidden="true"/></label>; }
