import Link from "next/link";
import { deadlineLabel, type Opportunity } from "@/data/opportunities";
import { ArrowIcon } from "./icons";
import { ConfidenceBadge, StatusBadge } from "./status-badge";

export function OpportunityCard({ opportunity, reasons }: { opportunity: Opportunity; reasons?: string[] }) {
  const secondary = opportunity.type === "Career" || opportunity.type === "Research" ? deadlineLabel(opportunity) : opportunity.type === "Scholarship" ? opportunity.metadata.awardAmountLabel ?? "Amount varies" : opportunity.type === "Benefit" ? opportunity.metadata.valueLabel ?? "Value unknown" : opportunity.metadata.studentOffer ?? "See official source";
  const secondaryLabel = opportunity.type === "Career" || opportunity.type === "Research" ? "Deadline" : opportunity.type === "Scholarship" ? "Award amount" : opportunity.type === "Benefit" ? "Estimated value" : "Student access";
  return <article className="grid gap-4 border-b border-ink/20 bg-white p-5 md:grid-cols-[minmax(0,1fr)_210px_150px] md:items-center">
    <div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><span className="rule-label text-forest">{opportunity.type}</span><span className="rule-label border-l border-ink/20 pl-3 text-ink/40">{opportunity.category}</span><StatusBadge status={opportunity.verification_status}/><ConfidenceBadge status={opportunity.verification_status}/></div><h3 className="mt-2 font-editorial text-xl font-bold">{opportunity.title}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wider text-ink/35">{opportunity.organization}</p><p className="mt-3 text-sm leading-6 text-ink/55">{opportunity.description}</p>{reasons?.length ? <details className="mt-4 border-l-2 border-gold pl-3"><summary className="cursor-pointer text-xs font-bold uppercase tracking-wider text-ink/55">Why am I seeing this?</summary><ul className="mt-2 space-y-1 text-xs text-ink/55">{reasons.map((reason)=><li key={reason}>✓ {reason}</li>)}</ul></details> : null}</div>
    <div className="border-t border-ink/15 pt-4 md:border-l md:border-t-0 md:pl-4 md:pt-0"><p className="rule-label text-ink/35">{secondaryLabel}</p><p className="mt-2 text-sm font-bold text-forest">{secondary}</p><p className="mt-3 text-xs text-ink/40">{opportunity.school_scope} · {opportunity.location}</p><p className="mt-2 text-[11px] text-ink/35">Last verified {opportunity.last_verified}</p></div>
    <div className="flex items-center gap-4 md:flex-col md:items-end"><Link href={`/opportunities/${opportunity.id}`} className="inline-flex min-h-11 items-center gap-2 text-xs font-bold uppercase tracking-wider hover:text-forest">View details <ArrowIcon /></Link><a href={opportunity.official_source} target="_blank" rel="noreferrer" className="text-xs font-bold text-forest underline decoration-forest/30 underline-offset-4 hover:decoration-forest">Official source</a></div>
  </article>;
}
