"use client";

import { useMemo, useState } from "react";
import { filterOpportunities, opportunities, opportunityTypes, type OpportunityType } from "@/data/opportunities";
import { schools } from "@/data/seed";
import { OpportunityCard } from "./opportunity-card";
import { SearchIcon } from "./icons";

export function OpportunityFilter() {
  const [query,setQuery]=useState(""); const [type,setType]=useState<OpportunityType|"All">("All"); const [major,setMajor]=useState("All"); const [school,setSchool]=useState("All"); const [year,setYear]=useState("All"); const [paid,setPaid]=useState("All"); const [remote,setRemote]=useState("All"); const [deadline,setDeadline]=useState("All"); const [featured,setFeatured]=useState(false); const [hiddenGem,setHiddenGem]=useState(false);
  const majors=["All",...new Set(opportunities.flatMap((item)=>item.majors).filter((item)=>item!=="Any Major"))];
  const years=["All",...new Set(opportunities.flatMap((item)=>item.academic_years).filter((item)=>item!=="Any Year"))];
  const visible=useMemo(()=>filterOpportunities({query,types:type==="All"?undefined:[type],major,school:school==="All"?undefined:school,academicYear:year,paid:paid==="All"?undefined:paid==="Paid",remote:remote==="All"?undefined:remote==="Remote",deadline:deadline==="All"?undefined:deadline as "published"|"upcoming"|"rolling"|"not_announced",featured:featured?true:undefined,hiddenGem:hiddenGem?true:undefined}),[deadline,featured,hiddenGem,major,paid,query,remote,school,type,year]);
  return <>
    <div className="border-2 border-ink bg-white"><label className="flex h-14 items-center gap-3 px-4"><SearchIcon className="h-4 w-4 text-ink/40"/><span className="sr-only">Search all opportunities</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search all opportunities" className="min-w-0 flex-1 bg-transparent outline-none"/></label><div className="grid border-t border-ink/20 sm:grid-cols-2 lg:grid-cols-4"><Select label="Type" value={type} setValue={(value)=>setType(value as OpportunityType|"All")} options={["All",...opportunityTypes]}/><Select label="Major" value={major} setValue={setMajor} options={majors}/><Select label="School" value={school} setValue={setSchool} options={["All",...schools.map((item)=>item.slug)]} labels={new Map(schools.map((item)=>[item.slug,item.name]))}/><Select label="Year" value={year} setValue={setYear} options={years}/><Select label="Paid" value={paid} setValue={setPaid} options={["All","Paid","Unpaid"]}/><Select label="Remote" value={remote} setValue={setRemote} options={["All","Remote","In Person"]}/><Select label="Deadline" value={deadline} setValue={setDeadline} options={["All","published","upcoming","rolling","not_announced"]}/><div className="flex h-14 items-center gap-5 border-t border-ink/20 px-4 sm:border-l"><label className="text-xs font-bold"><input type="checkbox" checked={featured} onChange={(event)=>setFeatured(event.target.checked)} className="mr-2"/>Featured</label><label className="text-xs font-bold"><input type="checkbox" checked={hiddenGem} onChange={(event)=>setHiddenGem(event.target.checked)} className="mr-2"/>Hidden gems</label></div></div></div>
    <div className="mt-8 flex items-end justify-between border-b-2 border-ink pb-4"><h2 className="font-editorial text-3xl font-bold">Opportunity results</h2><p className="text-sm font-bold text-ink/45">{visible.length}</p></div><div className="border-b-2 border-ink">{visible.map((item)=><OpportunityCard key={item.id} opportunity={item}/>)}</div>{!visible.length&&<p className="border-b-2 border-ink bg-white py-12 text-center font-bold">No matching opportunities</p>}
  </>;
}

function Select({label,value,setValue,options,labels}:{label:string;value:string;setValue:(value:string)=>void;options:readonly string[];labels?:Map<string,string>}){return <label className="flex h-14 items-center justify-between gap-3 border-t border-ink/20 px-4 sm:border-l"><span className="rule-label text-ink/40">{label}</span><select value={value} onChange={(event)=>setValue(event.target.value)} className="min-w-0 max-w-[70%] bg-transparent text-sm font-bold outline-none">{options.map((option)=><option key={option} value={option}>{option==="All"?"All":labels?.get(option)??option.replaceAll("_"," ")}</option>)}</select></label>}
