import Link from "next/link";
import { deadlineLabel, type Opportunity } from "@/data/opportunities";
import { ArrowIcon } from "./icons";
import { SaveOpportunityButton } from "./opportunity-activity";
import { StatusBadge } from "./status-badge";

export function OpportunityCard({ opportunity, reasons }: { opportunity: Opportunity; reasons?: string[] }) {
  const secondary = opportunity.type === "Career" || opportunity.type === "Research" ? deadlineLabel(opportunity) : opportunity.type === "Scholarship" ? opportunity.metadata.awardAmountLabel ?? "Amount varies" : opportunity.type === "Benefit" ? opportunity.metadata.valueLabel ?? "See official source" : opportunity.metadata.studentOffer ?? "See official source";
  const secondaryLabel = opportunity.type === "Career" || opportunity.type === "Research" ? "Deadline" : opportunity.type === "Scholarship" ? "Award amount" : opportunity.type === "Benefit" ? "Estimated value" : "Student access";
  return <article className="my-4 grid gap-6 rounded-[1.5rem] bg-white/92 p-5 shadow-[0_16px_42px_rgba(43,33,26,.055)] ring-1 ring-ink/7 transition duration-200 hover:-translate-y-0.5 hover:bg-white hover:shadow-[0_22px_55px_rgba(43,33,26,.095)] md:grid-cols-[minmax(0,1fr)_230px_150px] md:items-center motion-reduce:hover:translate-y-0">
    <div className="min-w-0"><div className="flex flex-wrap items-center gap-2.5"><span className="rule-label text-forest">{opportunity.type}</span><span className="rule-label text-ink/35">{opportunity.category}</span><StatusBadge status={opportunity.verification_status}/></div><h3 className="mt-3 font-editorial text-2xl font-bold leading-[1.08] tracking-[-.025em]"><Link href={`/opportunities/${opportunity.id}`} className="rounded-sm hover:text-forest focus:outline-none focus:ring-2 focus:ring-forest/30">{opportunity.title}</Link></h3><p className="mt-2 text-xs font-bold uppercase tracking-[.08em] text-ink/35">{opportunity.organization}</p><p className="mt-3 line-clamp-2 max-w-3xl text-sm leading-6 text-ink/55">{opportunity.description}</p>{reasons?.length ? <details className="mt-4 rounded-2xl bg-paper/70 px-4 py-3"><summary className="cursor-pointer text-xs font-bold text-ink/58">Why this matches</summary><ul className="mt-2 space-y-1 text-xs leading-5 text-ink/55">{reasons.map((reason)=><li key={reason}>{reason}</li>)}</ul></details> : null}</div>
    <div className="rounded-[1.25rem] bg-paper/80 px-4 py-4 ring-1 ring-ink/6"><p className="rule-label text-ink/35">{secondaryLabel}</p><p className="mt-2 text-sm font-black text-forest">{secondary}</p><p className="mt-3 text-xs text-ink/45">{opportunity.school_scope} · {opportunity.location}</p><p className="mt-2 text-[11px] text-ink/35">Verified {opportunity.last_verified}</p></div>
    <div className="flex items-center gap-3 md:flex-col md:items-stretch"><SaveOpportunityButton opportunityId={opportunity.id} className="rounded-full border border-ink/15 px-4 text-ink/55 hover:border-forest hover:text-forest"/><Link href={`/opportunities/${opportunity.id}`} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-ink px-4 text-sm font-bold text-white shadow-[0_12px_26px_rgba(43,33,26,.12)] hover:bg-forest">Open <ArrowIcon /></Link><a href={opportunity.official_source} target="_blank" rel="noreferrer" className="text-center text-xs font-bold text-forest underline decoration-forest/30 underline-offset-4 hover:decoration-forest">Official source</a></div>
  </article>;
}
