"use client";

import { useMemo, useState } from "react";
import { deadlineLabel, researchOpportunities, type Opportunity } from "@/data/opportunities";
import { schools, type School } from "@/data/seed";
import { ArrowIcon, SearchIcon } from "./icons";
import { SaveOpportunityButton } from "./opportunity-activity";
import { ConfidenceBadge, StatusBadge } from "./status-badge";

function majorTags(major:string){const value=major.toLowerCase();const tags:string[]=[];if(/computer|software|informatics|coding/.test(value))tags.push("Computer Science");if(/math|statistic|actuar/.test(value))tags.push("Mathematics","Data Science");if(/data|analytics|machine learning|artificial intelligence|\bai\b/.test(value))tags.push("Data Science","Computer Science");if(/engineer/.test(value))tags.push("Engineering");if(/physics/.test(value))tags.push("Physics","Mathematics");if(/biology|chemistry|neuro|science/.test(value))tags.push("Natural Sciences");if(/social|politic|psychology|sociology/.test(value))tags.push("Social Sciences");return[...new Set(tags)]}
function relevance(item:Opportunity,school:School,major:string,year:string){let score=item.school_scope==="National"?1:item.schools.includes(school.slug)?12:-20;score+=majorTags(major).filter((tag)=>item.majors.includes(tag)).length*6;if(item.majors.includes("Any Major"))score+=2;if(item.academic_years.includes(year))score+=4;return score}

export function ResearchSection({school,major,year}:{school:School;major:string;year:string}){
  const [query,setQuery]=useState("");const [schoolFilter,setSchoolFilter]=useState("All");const [majorFilter,setMajorFilter]=useState("All");const [paidFilter,setPaidFilter]=useState("All");const [termFilter,setTermFilter]=useState("All");const [deadlineFilter,setDeadlineFilter]=useState("All");const [scopeFilter,setScopeFilter]=useState("All");
  const majors=["All",...new Set(researchOpportunities.flatMap((item)=>item.majors).filter((item)=>item!=="Any Major"))];
  const recommended=useMemo(()=>researchOpportunities.filter((item)=>item.school_scope==="National"||item.schools.includes(school.slug)).sort((a,b)=>relevance(b,school,major,year)-relevance(a,school,major,year)).slice(0,6),[major,school,year]);
  const visible=useMemo(()=>{const search=query.toLowerCase().trim();return researchOpportunities.filter((item)=>{const schoolMatches=schoolFilter==="All"||(schoolFilter==="National"&&item.school_scope==="National")||item.schools.includes(schoolFilter);const deadlineMatches=deadlineFilter==="All"||(deadlineFilter==="Published"&&Boolean(item.application_deadline))||(deadlineFilter==="Rolling or varies"&&["rolling","varies"].includes(item.metadata.deadlineType??""))||(deadlineFilter==="Not announced"&&item.metadata.deadlineType==="not_announced");return(!search||`${item.title} ${item.organization} ${item.description} ${item.metadata.researchArea}`.toLowerCase().includes(search))&&schoolMatches&&(majorFilter==="All"||item.majors.includes("Any Major")||item.majors.includes(majorFilter))&&(paidFilter==="All"||(paidFilter==="Paid"?item.paid===true:paidFilter==="Unpaid"?item.paid===false:item.paid===null))&&(termFilter==="All"||item.metadata.semesters?.includes(termFilter))&&deadlineMatches&&(scopeFilter==="All"||item.school_scope===scopeFilter)}).sort((a,b)=>relevance(b,school,major,year)-relevance(a,school,major,year))},[deadlineFilter,major,majorFilter,paidFilter,query,school,schoolFilter,scopeFilter,termFilter,year]);
  const row=(item:Opportunity,index:number)=><article key={item.id} className="grid gap-4 border-b border-ink/20 bg-white px-4 py-5 last:border-b-0 lg:grid-cols-[36px_1fr_210px_150px]"><span className="hidden pt-1 font-mono text-xs text-ink/30 lg:block">{String(index+1).padStart(2,"0")}</span><div><div className="flex flex-wrap gap-3"><span className="rule-label text-forest">{item.category}</span><StatusBadge status={item.verification_status}/><ConfidenceBadge status={item.verification_status}/><span className="rule-label border-l border-ink/20 pl-3 text-ink/40">{item.school_scope}</span></div><h3 className="mt-2 font-editorial text-xl font-bold">{item.title}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wider text-ink/35">{item.organization}</p><p className="mt-3 text-sm leading-6 text-ink/55">{item.description}</p><p className="mt-3 text-xs text-ink/45">{item.metadata.department} · {item.metadata.researchArea}</p><p className="mt-2 text-xs leading-5 text-ink/45"><span className="font-bold">Eligibility:</span> {item.eligibility}</p></div><div className="border-t-2 border-forest pt-4 lg:border-l-2 lg:border-t-0 lg:pl-4 lg:pt-0"><p className="rule-label text-ink/35">Application deadline</p><p className="mt-2 font-editorial text-xl font-bold text-forest">{deadlineLabel(item)}</p><p className="mt-4 text-xs font-bold">{item.metadata.semesters?.join(" · ")}</p><p className="mt-2 text-xs text-ink/45">{item.paid===null?"Compensation varies":item.paid?"Paid":"Unpaid"} · {item.remote===null?"Format varies":item.remote?"Remote":"In person"}</p></div><div className="lg:text-right"><p className="text-xs"><span className="font-bold">Difficulty:</span> {item.difficulty}</p><p className="mt-1 text-xs"><span className="font-bold">Prestige:</span> {item.prestige}</p><p className="mt-3 text-[11px] text-ink/35">Verified {item.last_verified}</p><SaveOpportunityButton opportunityId={item.id} className="mt-4 w-full border border-ink/15 px-4 text-ink/55 hover:border-forest hover:text-forest lg:w-auto"/><a href={item.official_source} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center gap-2 border-b border-ink pb-1 text-xs font-bold uppercase tracking-wider hover:border-forest hover:text-forest">Official source <ArrowIcon/></a></div></article>;
  return <section className="border-t-2 border-ink px-5 py-10 sm:px-8" aria-labelledby="research-title"><div className="border-b-2 border-ink pb-4"><p className="rule-label text-forest">Personalized by school, major, and year</p><h2 id="research-title" className="mt-2 font-editorial text-3xl font-bold">Recommended Research</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-ink/50">National programs and verified {school.name} opportunities ranked for {major} · {year}.</p></div><div className="border-b-2 border-ink">{recommended.map(row)}</div><div className="mt-12 flex items-end justify-between border-b-2 border-ink pb-4"><div><p className="rule-label text-forest">Research directory</p><h2 className="mt-2 font-editorial text-3xl font-bold">Undergraduate research opportunities</h2></div><p className="text-sm font-bold text-ink/45">{visible.length} of {researchOpportunities.length}</p></div><div className="grid border-b border-ink/20 bg-white lg:grid-cols-[1fr_230px_220px]"><label className="flex h-14 items-center gap-3 px-4"><SearchIcon className="h-4 w-4 text-ink/40"/><span className="sr-only">Search research</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search research areas or institutions" className="min-w-0 flex-1 bg-transparent outline-none"/></label><Select label="School" value={schoolFilter} setValue={setSchoolFilter} options={["All","National",...schools.filter((item)=>researchOpportunities.some((opportunity)=>opportunity.schools.includes(item.slug))).map((item)=>item.slug)]} labels={new Map(schools.map((item)=>[item.slug,item.name]))}/><Select label="Major" value={majorFilter} setValue={setMajorFilter} options={majors}/></div><div className="grid border-b-2 border-ink bg-white sm:grid-cols-2 lg:grid-cols-4"><Select label="Paid" value={paidFilter} setValue={setPaidFilter} options={["All","Paid","Unpaid","Varies"]}/><Select label="Term" value={termFilter} setValue={setTermFilter} options={["All","Summer","Fall","Spring"]}/><Select label="Deadline" value={deadlineFilter} setValue={setDeadlineFilter} options={["All","Published","Rolling or varies","Not announced"]}/><Select label="Scope" value={scopeFilter} setValue={setScopeFilter} options={["All","National","School Specific"]}/></div><div className="border-b-2 border-ink">{visible.map(row)}</div>{!visible.length&&<p className="border-b-2 border-ink bg-white py-12 text-center font-bold">No matching research opportunities</p>}</section>
}

function Select({label,value,setValue,options,labels}:{label:string;value:string;setValue:(value:string)=>void;options:readonly string[];labels?:Map<string,string>}){return <label className="flex h-14 items-center justify-between gap-3 border-t border-ink/20 px-4 sm:border-l"><span className="rule-label text-ink/40">{label}</span><select value={value} onChange={(event)=>setValue(event.target.value)} className="min-w-0 max-w-[70%] bg-transparent text-sm font-bold outline-none">{options.map((option)=><option key={option} value={option}>{labels?.get(option)??option}</option>)}</select></label>}
