import Link from "next/link";
import type { Benefit, School } from "@/data/seed";
import { ArrowIcon } from "./icons";

const categorySlug = (category: string) => category.toLowerCase();

export function SchoolSeoSections({ school, benefits, relatedSchools }: { school: School; benefits: Benefit[]; relatedSchools: School[] }) {
  const best = [...benefits].sort((a, b) => b.annualValue - a.annualValue || Number(Boolean(b.featured)) - Number(Boolean(a.featured)) || a.name.localeCompare(b.name)).slice(0, 5);
  const groups = [
    { title: "Free software", category: "Software", description: "Verified software and education plans available to eligible students." },
    { title: "AI tools", category: "AI", description: "Verified AI research, study, and problem-solving offers." },
    { title: "Shopping discounts", category: "Shopping", description: "Education pricing and verified student shopping programs." },
    { title: "Finance benefits", category: "Finance", description: "Verified financial tools and student-specific programs." },
  ];
  return <section className="mt-16 border-t-2 border-ink" aria-labelledby="school-guide-title">
    <div className="grid gap-8 border-b border-ink/20 py-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="rule-label text-forest">Eligibility guide</p><h2 id="school-guide-title" className="mt-2 font-editorial text-4xl font-bold">Top benefits available to eligible {school.name} students</h2><p className="mt-3 text-sm leading-6 text-ink/50">National offers are not institutional benefits from {school.name}; school-specific listings are identified separately.</p></div><div className="divide-y divide-ink/15 border-y border-ink/20">{best.map((item, index) => <Link key={item.slug} href={`/benefits/${item.slug}`} className="grid grid-cols-[34px_1fr_auto] items-center gap-3 py-3 hover:text-forest"><span className="font-mono text-xs text-ink/30">{String(index + 1).padStart(2, "0")}</span><span><span className="font-bold">{item.name}</span><span className="ml-2 text-[10px] font-bold uppercase tracking-wider text-ink/35">{item.scope === "national" ? "National" : "School-specific"}</span></span><span className="hidden text-xs text-ink/45 sm:block">{item.value}</span></Link>)}</div></div>
    <div className="grid border-b-2 border-ink md:grid-cols-2">{groups.map((group) => { const items = benefits.filter((item) => item.category === group.category); return <section key={group.category} className="border-b border-r border-ink/20 p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="rule-label text-forest">{group.category}</p><h2 className="mt-2 font-editorial text-2xl font-bold">{group.title}</h2></div><Link href={`/categories/${categorySlug(group.category)}`} className="text-xs font-bold uppercase tracking-wider text-forest">All {group.category}</Link></div><p className="mt-3 text-sm leading-6 text-ink/50">{group.description}</p>{items.length ? <ul className="mt-5 space-y-2">{items.slice(0, 4).map((item) => <li key={item.slug}><Link href={`/benefits/${item.slug}`} className="flex items-center justify-between gap-4 border-t border-ink/15 pt-2 text-sm font-bold hover:text-forest"><span>{item.name}</span><ArrowIcon className="h-3.5 w-3.5 shrink-0" /></Link></li>)}</ul> : <p className="mt-5 text-sm italic text-ink/40">No verified offers in this category.</p>}</section>; })}</div>
    <div className="grid gap-10 border-b-2 border-ink py-10 lg:grid-cols-2"><section><p className="rule-label text-forest">Claim guide</p><h2 className="mt-2 font-editorial text-3xl font-bold">How to claim student benefits</h2><ol className="mt-6 space-y-4">{["Open the benefit detail page and confirm the current eligibility requirements.", "Follow the official provider link—UnlockED never processes a claim.", "Verify enrollment using your .edu email, campus ID, or the provider’s verification service.", "Review renewal and expiration terms before activating a paid or recurring offer."].map((step, index) => <li key={step} className="flex gap-4 text-sm leading-6 text-ink/60"><span className="font-mono text-xs text-forest">0{index + 1}</span>{step}</li>)}</ol></section><section><p className="rule-label text-forest">Related institutions</p><h2 className="mt-2 font-editorial text-3xl font-bold">Explore other schools</h2><div className="mt-6 divide-y divide-ink/15 border-y border-ink/20">{relatedSchools.map((item) => <Link key={item.slug} href={`/schools/${item.slug}`} className="flex items-center justify-between py-3 font-bold hover:text-forest"><span>{item.name}</span><span className="font-mono text-xs text-ink/35">{item.domain}</span></Link>)}</div></section></div>
  </section>;
}
