"use client";

import { useMemo, useState } from "react";
import { deadlineLabel, scholarshipOpportunities, type Opportunity } from "@/data/opportunities";
import { schools, type School } from "@/data/seed";
import { ArrowIcon, SearchIcon } from "./icons";
import { AddToJourneyButton } from "./opportunity-activity";
import { ConfidenceBadge, StatusBadge } from "./status-badge";

function majorTags(major:string){const value=major.toLowerCase();const tags:string[]=[];if(/computer|software|informatics/.test(value))tags.push("Computer Science");if(/math|statistic/.test(value))tags.push("Mathematics","Data Science");if(/data|analytics|artificial intelligence|\bai\b/.test(value))tags.push("Data Science","Computer Science");if(/engineer/.test(value))tags.push("Engineering");if(/physics/.test(value))tags.push("Physics","Mathematics");if(/biology|chemistry|neuro|science/.test(value))tags.push("Natural Sciences");if(/finance|econom|business/.test(value))tags.push("Finance","Business");if(/design|art/.test(value))tags.push("Design");if(/social|politic|psychology/.test(value))tags.push("Social Sciences");return[...new Set(tags)]}
function relevance(item:Opportunity,school:School,major:string,year:string){let score=item.school_scope==="National"?2:item.schools.includes(school.slug)?14:-30;score+=majorTags(major).filter((tag)=>item.majors.includes(tag)).length*6;if(item.majors.includes("Any Major"))score+=2;if(item.academic_years.includes(year))score+=5;if(year==="First year"&&item.category==="First-Year Scholarships")score+=8;return score}

export function ScholarshipSection({school,major,year}:{school:School;major:string;year:string}){
  const [query,setQuery]=useState("");const [majorFilter,setMajorFilter]=useState("All");const [yearFilter,setYearFilter]=useState("All");const [amountFilter,setAmountFilter]=useState("All");const [deadlineFilter,setDeadlineFilter]=useState("All");const [scopeFilter,setScopeFilter]=useState("All");const [renewableFilter,setRenewableFilter]=useState("All");const [difficultyFilter,setDifficultyFilter]=useState("All");
  const majors=["All",...new Set(scholarshipOpportunities.flatMap((item)=>item.majors).filter((item)=>item!=="Any Major"))];
  const years=["All","First year","Second year","Third year","Fourth year","Graduate student"];
  const recommended=useMemo(()=>scholarshipOpportunities.filter((item)=>item.school_scope==="National"||item.schools.includes(school.slug)).sort((a,b)=>relevance(b,school,major,year)-relevance(a,school,major,year)).slice(0,6),[major,school,year]);
  const visible=useMemo(()=>{const search=query.trim().toLowerCase();return scholarshipOpportunities.filter((item)=>{const amountMatches=amountFilter==="All"||(amountFilter==="$10,000+"&&(item.estimated_value??0)>=10000)||(amountFilter==="$25,000+"&&(item.estimated_value??0)>=25000)||(amountFilter==="Amount varies"&&item.estimated_value===null);const deadlineMatches=deadlineFilter==="All"||(deadlineFilter==="Published"&&Boolean(item.application_deadline))||(deadlineFilter==="Deadline varies"&&!item.application_deadline);const renewableMatches=renewableFilter==="All"||(renewableFilter==="Renewable"&&item.metadata.renewable===true)||(renewableFilter==="One-Time"&&item.metadata.renewable===false)||(renewableFilter==="Varies"&&item.metadata.renewable===null);return(!search||`${item.title} ${item.organization} ${item.description} ${item.tags.join(" ")}`.toLowerCase().includes(search))&&(majorFilter==="All"||item.majors.includes("Any Major")||item.majors.includes(majorFilter))&&(yearFilter==="All"||item.academic_years.includes(yearFilter))&&amountMatches&&deadlineMatches&&(scopeFilter==="All"||item.school_scope===scopeFilter)&&renewableMatches&&(difficultyFilter==="All"||item.difficulty===difficultyFilter)}).sort((a,b)=>relevance(b,school,major,year)-relevance(a,school,major,year))},[amountFilter,deadlineFilter,difficultyFilter,major,majorFilter,query,renewableFilter,school,scopeFilter,year,yearFilter]);
  const row=(item:Opportunity,index:number)=><article key={item.id} className="grid gap-4 border-b border-ink/20 bg-white px-4 py-5 last:border-b-0 lg:grid-cols-[36px_1fr_210px_150px]"><span className="hidden pt-1 font-mono text-xs text-ink/30 lg:block">{String(index+1).padStart(2,"0")}</span><div><div className="flex flex-wrap gap-3"><span className="rule-label text-forest">{item.category}</span><StatusBadge status={item.verification_status}/><ConfidenceBadge status={item.verification_status}/><span className="rule-label border-l border-ink/20 pl-3 text-ink/40">{item.school_scope}</span></div><h3 className="mt-2 font-editorial text-xl font-bold">{item.title}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wider text-ink/35">{item.organization}</p><p className="mt-3 text-sm leading-6 text-ink/55">{item.description}</p><p className="mt-3 text-xs leading-5 text-ink/45"><span className="font-bold">Eligibility:</span> {item.eligibility}</p><p className="mt-2 text-xs text-ink/45">{item.majors.join(" · ")} · {item.academic_years.join(" · ")}</p></div><div className="border-t-2 border-forest pt-4 lg:border-l-2 lg:border-t-0 lg:pl-4 lg:pt-0"><p className="rule-label text-ink/35">Award amount</p><p className="mt-2 font-editorial text-xl font-bold text-forest">{item.metadata.awardAmountLabel}</p><p className="mt-5 rule-label text-ink/35">Application deadline</p><p className="mt-2 font-bold">{deadlineLabel(item)}</p><p className="mt-3 text-xs text-ink/45">{item.metadata.renewable===null?"Renewal varies":item.metadata.renewable?"Renewable":"One-time award"}</p></div><div className="lg:text-right"><p className="text-xs"><span className="font-bold">Difficulty:</span> {item.difficulty}</p><p className="mt-3 text-[11px] text-ink/35">Verified {item.last_verified}</p><AddToJourneyButton opportunityId={item.id} className="mt-4 w-full border border-ink/15 px-4 text-ink/55 hover:border-forest hover:text-forest lg:w-auto"/><a href={item.official_source} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center gap-2 border-b border-ink pb-1 text-xs font-bold uppercase tracking-wider hover:border-forest hover:text-forest">Official source <ArrowIcon/></a></div></article>;
  return <section className="border-t-2 border-ink px-5 py-10 sm:px-8" aria-labelledby="scholarships-title"><div className="border-b-2 border-ink pb-4"><p className="rule-label text-forest">Personalized by school, major, and year</p><h2 id="scholarships-title" className="mt-2 font-editorial text-3xl font-bold">Scholarships For You</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-ink/50">National scholarships and verified {school.name} aid opportunities ranked for {major} · {year}. Unknown dates are shown as “Deadline varies.”</p></div><div className="border-b-2 border-ink">{recommended.map(row)}</div><div className="mt-12 flex items-end justify-between border-b-2 border-ink pb-4"><div><p className="rule-label text-forest">Scholarship directory</p><h2 className="mt-2 font-editorial text-3xl font-bold">Verified scholarship opportunities</h2></div><p className="text-sm font-bold text-ink/45">{visible.length} of {scholarshipOpportunities.length}</p></div><div className="grid border-b border-ink/20 bg-white lg:grid-cols-[1fr_220px_200px]"><label className="flex h-14 items-center gap-3 px-4"><SearchIcon className="h-4 w-4 text-ink/40"/><span className="sr-only">Search scholarships</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search scholarships or organizations" className="min-w-0 flex-1 bg-transparent outline-none"/></label><Select label="Major" value={majorFilter} setValue={setMajorFilter} options={majors}/><Select label="Year" value={yearFilter} setValue={setYearFilter} options={years}/></div><div className="grid border-b-2 border-ink bg-white sm:grid-cols-2 lg:grid-cols-5"><Select label="Amount" value={amountFilter} setValue={setAmountFilter} options={["All","$10,000+","$25,000+","Amount varies"]}/><Select label="Deadline" value={deadlineFilter} setValue={setDeadlineFilter} options={["All","Published","Deadline varies"]}/><Select label="Scope" value={scopeFilter} setValue={setScopeFilter} options={["All","National","School Specific"]}/><Select label="Renewal" value={renewableFilter} setValue={setRenewableFilter} options={["All","Renewable","One-Time","Varies"]}/><Select label="Difficulty" value={difficultyFilter} setValue={setDifficultyFilter} options={["All","Competitive","Highly Competitive"]}/></div><div className="border-b-2 border-ink">{visible.map(row)}</div>{!visible.length&&<p className="border-b-2 border-ink bg-white py-12 text-center font-bold">No matching scholarships</p>}</section>
}
function Select({label,value,setValue,options}:{label:string;value:string;setValue:(value:string)=>void;options:readonly string[]}){return <label className="flex h-14 items-center justify-between gap-3 border-t border-ink/20 px-4 sm:border-l"><span className="rule-label text-ink/40">{label}</span><select value={value} onChange={(event)=>setValue(event.target.value)} className="min-w-0 max-w-[70%] bg-transparent text-sm font-bold outline-none">{options.map((option)=><option key={option}>{option}</option>)}</select></label>}
