import Link from "next/link";
import { ArrowIcon } from "./icons";
import { StatusBadge } from "./status-badge";
import type { Benefit } from "@/data/seed";

export function SeoLanding({ eyebrow, title, intro, benefits, guideTitle, guide }: { eyebrow: string; title: string; intro: string; benefits: Benefit[]; guideTitle: string; guide: string[] }) {
  return (
    <>
      <section className="border-b-2 border-ink bg-white px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto grid max-w-6xl gap-8 border-x border-ink/20 px-5 sm:px-8 lg:grid-cols-[1fr_260px]"><div className="pb-10 lg:border-r lg:border-ink/20 lg:pr-12"><p className="rule-label text-forest">{eyebrow}</p><h1 className="mt-4 max-w-3xl font-editorial text-4xl font-bold tracking-[-0.04em] sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-ink/60">{intro}</p></div><div className="flex items-end pb-10"><Link href="/schools/university-of-michigan" className="inline-flex items-center gap-2 border-b-2 border-ink pb-1 text-xs font-bold uppercase tracking-widest hover:border-forest hover:text-forest">Browse all student perks <ArrowIcon /></Link></div></div></section>
      <section className="px-5 py-14 sm:px-8 sm:py-20"><div className="mx-auto max-w-6xl"><div className="mb-8 flex items-end justify-between gap-4 border-b-2 border-ink pb-5"><div><p className="rule-label text-forest">Editor’s shortlist</p><h2 className="mt-2 font-editorial text-3xl font-bold">Top offers to check first</h2></div><p className="hidden text-sm text-ink/40 sm:block">Updated July 6, 2026</p></div><div className="border-b-2 border-ink">{benefits.slice(0, 6).map((item, index) => <Link href={`/benefits/${item.slug}`} key={item.slug} className="group grid gap-3 border-b border-ink/20 py-5 last:border-b-0 sm:grid-cols-[36px_1fr_180px] sm:items-center"><span className="hidden font-mono text-xs text-ink/30 sm:block">{String(index + 1).padStart(2, "0")}</span><div><div className="flex items-center gap-3"><span className="rule-label text-forest">{item.category}</span><StatusBadge status={item.status} /></div><h3 className="mt-2 font-editorial text-xl font-bold group-hover:text-forest">{item.name}</h3><p className="mt-1 text-sm text-ink/50">{item.description}</p></div><div className="sm:text-right"><p className="rule-label text-ink/35">Offer value</p><p className="mt-2 font-bold text-forest">{item.value}</p></div></Link>)}</div></div></section>
      <section className="bg-ink px-5 py-14 text-white sm:px-8 sm:py-20"><div className="mx-auto grid max-w-5xl gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-wider text-lime">How it works</p><h2 className="mt-3 text-3xl font-black">{guideTitle}</h2></div><ol className="space-y-5">{guide.map((item, index) => <li key={item} className="flex gap-4 border-b border-white/10 pb-5"><span className="font-mono text-sm text-lime">0{index + 1}</span><p className="leading-7 text-white/70">{item}</p></li>)}</ol></div></section>
    </>
  );
}
