"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { formatValueTotal, getSchoolBenefits, schools } from "@/data/seed";
import { ArrowIcon } from "./icons";
export function StudentSavingsCalculator() {
  const [slug,setSlug]=useState(""); const school=schools.find((s)=>s.slug===slug);
  const stats=useMemo(()=>{if(!school)return null;const items=getSchoolBenefits(school).filter((i)=>i.status==="verified_recently");const count=(c:string)=>items.filter((i)=>i.category===c).length;return{total:items.reduce((s,i)=>s+i.annualValue,0),benefits:items.length,ai:count("AI"),software:count("Software"),shopping:count("Shopping"),finance:count("Finance"),excluded:items.filter((i)=>i.annualValue===0).length}},[school]);
  return <section id="savings-calculator" className="mx-auto max-w-7xl scroll-mt-24 border-x border-ink/20 px-5 py-14 sm:px-8 sm:py-16"><div className="grid gap-8 border-y-2 border-ink py-6 lg:grid-cols-[1fr_380px] lg:items-end"><div><p className="rule-label text-forest">Student savings calculator</p><h2 className="mt-2 font-editorial text-3xl font-bold sm:text-4xl">Your benefits, by the numbers.</h2></div><label><span className="mb-2 block rule-label text-ink/45">Select institution</span><select value={slug} onChange={(e)=>setSlug(e.target.value)} className="h-12 w-full border-2 border-ink bg-white px-3 font-bold outline-none focus:bg-lime/20"><option value="">Choose a school</option>{schools.map((s)=><option key={s.slug} value={s.slug}>{s.name}</option>)}</select></label></div>{stats&&school?<><div className="grid border-b-2 border-ink sm:grid-cols-3 lg:grid-cols-6">{[["Verified benefits",stats.benefits],["Known annual value",formatValueTotal(stats.total)],["AI tools",stats.ai],["Software",stats.software],["Shopping",stats.shopping],["Finance",stats.finance]].map(([label,value],i)=><div key={label} className={`border-b border-r border-ink/20 p-4 sm:p-5 ${i<2?"bg-ink text-white":"bg-white"}`}><p className={`rule-label ${i<2?"text-white/50":"text-ink/40"}`}>{label}</p><p className="mt-3 font-editorial text-3xl font-bold">{value}</p></div>)}</div><div className="flex flex-col gap-3 border-b border-ink/20 py-4 text-xs text-ink/50 sm:flex-row sm:justify-between"><p>Estimate uses documented fixed values only; {stats.excluded} variable-value offers are excluded.</p><Link href={`/schools/${school.slug}`} className="flex items-center gap-2 font-bold uppercase tracking-wider text-forest">Open school index <ArrowIcon /></Link></div></>:<p className="border-b-2 border-ink py-8 font-editorial text-xl text-ink/45">Select a school to generate a verified savings summary.</p>}</section>;
}
