import type { ApplicationCounselorState, CollegeListRecord, CounselorReadinessStatus } from "@/data/college-admissions";
import { verifiedCollegeAdmissions, verifiedCollegeTestingPolicies } from "@/data/college-admissions";
import { getCollege } from "./colleges";

export const emptyCounselorState=():ApplicationCounselorState=>({commonApp:{},recommenders:[],schoolDocuments:[],schoolProcesses:[],bragSheet:{selectedExperienceIds:[],selectedAccomplishmentIds:[],tailoredNotes:{},version:0},version:0});
const complete=(status:string|undefined)=>["ready","submitted","not_required","received_confirmed"].includes(status??"");
export type CounselorCollege={id:string;slug:string;name:string;state:string;record:CollegeListRecord;deadline?:{date:string;label:string;cycle:string;sourceUrl:string};usesCommonApp:boolean;verifiedUrl?:string;testing?:{label:string;sourceUrl:string;verifiedAt:string};writing:Array<{id:string;title:string;status:string}>};
export function buildCounselorModel(records:CollegeListRecord[], counselor:ApplicationCounselorState, writing:Array<{id:string;collegeId?:string;title:string;status:string}>, today=new Date()){
  const todayKey=today.toISOString().slice(0,10);
  const colleges:CounselorCollege[]=records.filter((record)=>record.application&&record.interestState!=="exploring").map((record)=>{
    const college=getCollege(record.collegeId)!; const verified=verifiedCollegeAdmissions[record.collegeId]; const selected=verified?.deadlines.find((item)=>item.plan===record.application!.plan);
    const testing=verifiedCollegeTestingPolicies[record.collegeId];
    return{id:college.id,slug:college.slug,name:college.name,state:college.state,record,deadline:selected?{date:selected.date,label:selected.label,cycle:selected.cycle,sourceUrl:selected.sourceUrl}:undefined,usesCommonApp:verified?.applicationPlatforms?.includes("common_app")??false,verifiedUrl:verified?.applicationUrl,testing:testing?{label:testing.label,sourceUrl:testing.sourceUrl,verifiedAt:testing.verifiedAt}:undefined,writing:writing.filter((item)=>item.collegeId===record.collegeId)};
  }).sort((a,b)=>(a.deadline?.date??"9999").localeCompare(b.deadline?.date??"9999"));
  const upcoming=[...colleges.flatMap((college)=>college.deadline?[{id:`deadline:${college.id}`,date:college.deadline.date,title:`${college.name} · ${college.deadline.label}`,href:`/colleges/${college.slug}/application`,source:`Official · ${college.deadline.cycle}`}]:[]),...counselor.recommenders.filter((item)=>item.deadline&&!complete(item.status)).map((item)=>({id:`rec:${item.id}`,date:item.deadline!,title:`${item.name} recommendation`,href:"#recommendations",source:"Date you added"})),...counselor.schoolProcesses.filter((item)=>item.internalDeadline&&item.status!=="ready").map((item)=>({id:`school:${item.id}`,date:item.internalDeadline!,title:item.title,href:"#school",source:"School deadline you added"}))].filter((item)=>item.date>=todayKey).sort((a,b)=>a.date.localeCompare(b.date));
  const actions:Array<{rank:number;date:string;title:string;detail:string;href:string}>=[];
  for(const recommender of counselor.recommenders){if(["considering","plan_to_ask"].includes(recommender.status))actions.push({rank:0,date:recommender.deadline??"9999",title:`Ask ${recommender.name} for a recommendation`,detail:`Assigned to ${recommender.collegeIds.length} college${recommender.collegeIds.length===1?"":"s"}. Prepare the request before the earliest deadline.`,href:"#recommendations"}); if(["asked","no_response"].includes(recommender.status)&&recommender.followUpAt&&recommender.followUpAt<=todayKey)actions.push({rank:1,date:recommender.deadline??"9999",title:`Consider a polite follow-up with ${recommender.name}`,detail:"You set this follow-up date. Check the official system before updating the status.",href:"#recommendations"});}
  for(const process of counselor.schoolProcesses)if(process.status!=="ready")actions.push({rank:2,date:process.internalDeadline??"9999",title:process.title,detail:`School process${process.system?` · ${process.system}`:""}`,href:"#school"});
  const activities=counselor.commonApp.activities as CounselorReadinessStatus|undefined;
  if(colleges.some((item)=>item.usesCommonApp)&&activities!=="ready")actions.push({rank:3,date:"9999",title:"Review your Common App activities",detail:"The existing Activities Builder is linked here; no entries are duplicated.",href:"/resume-lab/activities"});
  for(const college of colleges){const app=college.record.application!;for(const requirement of app.requirements)if(!complete(requirement.status))actions.push({rank:requirement.status==="not_started"?4:5,date:college.deadline?.date??"9999",title:`${college.name}: ${requirement.title}`,detail:`${college.deadline?`Due ${college.deadline.date} · `:""}${requirement.provenance==="official_verified"?"Official verified requirement":"Student-added or unverified requirement"}`,href:`/colleges/${college.slug}/application`});}
  actions.sort((a,b)=>a.date.localeCompare(b.date)||a.rank-b.rank||a.title.localeCompare(b.title));
  return{colleges,upcoming,nextAction:actions[0]??{rank:9,date:"9999",title:colleges.length?"Review your application workspace":"Choose colleges you plan to apply to",detail:colleges.length?"Nothing urgent is recorded. Check official portals for changes.":"Start in My College List, then choose an application plan.",href:colleges.length?`/colleges/${colleges[0].slug}/application`:"/colleges/saved"},thisWeek:actions.filter((item)=>item.date!=="9999"&&item.date<=new Date(today.getTime()+7*86400000).toISOString().slice(0,10)).slice(0,5)};
}
