import { opportunityTypes, type Opportunity, type OpportunityScope, type VerificationStatus } from "@/data/opportunities";
import type { OpportunityLifecycleConfidence, OpportunityLifecycleReason, OpportunityLifecycleState, OpportunityRecurrenceType } from "@/data/opportunity-lifecycle-types";

export type OpportunityInput = Pick<Opportunity,"title"|"organization"|"type"|"category"|"description"|"eligibility"|"school_scope"|"schools"|"verification_status"|"last_verified"|"tags"> & {
  official_source_url:string;
  deadline:string|null;
  estimated_value:number|null;
  lifecycle_state: OpportunityLifecycleState;
  lifecycle_confidence: OpportunityLifecycleConfidence;
  lifecycle_reason: OpportunityLifecycleReason;
  lifecycle_review_note: string;
  opening_date: string | null;
  recurrence_type: OpportunityRecurrenceType | null;
};
const statuses:VerificationStatus[]=["verified","needs_review","temporarily_closed","expired","broken_source","archived","incomplete","community_reported"];
const lifecycleStates:OpportunityLifecycleState[]=["unknown","upcoming","open","rolling","temporarily_closed","closed","canceled","archived"];
const lifecycleConfidence:OpportunityLifecycleConfidence[]=["confirmed","strong","limited","estimated","unknown"];
const lifecycleReasons:OpportunityLifecycleReason[]=["official_status_open","official_status_closed","deadline_future","deadline_passed","opening_date_future","opening_date_reached","rolling_confirmed","manually_verified","recurring_pattern","insufficient_current_evidence","source_removed","canceled_by_organization","record_archived","conflicting_evidence"];
const recurrenceTypes:OpportunityRecurrenceType[]=["annual","semester","quarterly","monthly","irregular","rolling_cohort","seasonal"];
const date=/^\d{4}-\d{2}-\d{2}$/;
export function validateOpportunityInput(value:unknown):{data?:OpportunityInput;errors:string[]}{
  if(!value||typeof value!=="object"||Array.isArray(value))return{errors:["Opportunity data must be an object."]};
  const input=value as Partial<OpportunityInput>;const errors:string[]=[];const required:[[keyof OpportunityInput,string]]|[keyof OpportunityInput,string][]=[["title","Title"],["organization","Organization"],["category","Category"],["description","Description"],["eligibility","Eligibility"],["official_source_url","Official source URL"],["last_verified","Last verified date"],["lifecycle_state","Lifecycle state"],["lifecycle_confidence","Lifecycle confidence"],["lifecycle_reason","Lifecycle reason"],["lifecycle_review_note","Lifecycle review note"]];
  for(const[field,label]of required)if(typeof input[field]!=="string"||!String(input[field]).trim())errors.push(`${label} is required.`);
  const limits:Partial<Record<keyof OpportunityInput,number>>={title:200,organization:200,category:120,description:5000,eligibility:3000,official_source_url:2048};for(const[field,max]of Object.entries(limits)as[keyof OpportunityInput,number][])if(typeof input[field]==="string"&&String(input[field]).length>max)errors.push(`${String(field).replaceAll("_"," ")} is too long.`);
  try{if(input.official_source_url&&new URL(input.official_source_url).protocol!=="https:")errors.push("Official source URL must use HTTPS.")}catch{errors.push("Official source URL is invalid.")}
  const validDate=(value:string|undefined|null)=>{if(!value)return true;if(!date.test(value))return false;const parsed=new Date(`${value}T00:00:00Z`);return!Number.isNaN(parsed.getTime())&&parsed.toISOString().slice(0,10)===value};if(!opportunityTypes.includes(input.type as never))errors.push("Opportunity type is invalid.");if(!["National","School Specific"].includes(input.school_scope as OpportunityScope))errors.push("School scope is invalid.");if(!statuses.includes(input.verification_status as VerificationStatus))errors.push("Verification status is invalid.");if(!lifecycleStates.includes(input.lifecycle_state as OpportunityLifecycleState))errors.push("Lifecycle state is invalid.");if(!lifecycleConfidence.includes(input.lifecycle_confidence as OpportunityLifecycleConfidence))errors.push("Lifecycle confidence is invalid.");if(!lifecycleReasons.includes(input.lifecycle_reason as OpportunityLifecycleReason))errors.push("Lifecycle reason is invalid.");if(input.recurrence_type!==null&&!recurrenceTypes.includes(input.recurrence_type as OpportunityRecurrenceType))errors.push("Recurrence type is invalid.");if(typeof input.lifecycle_review_note==="string"&&(input.lifecycle_review_note.trim().length<8||input.lifecycle_review_note.length>1000))errors.push("Lifecycle review note must be between 8 and 1,000 characters.");if(!validDate(input.last_verified))errors.push("Last verified date must use a valid YYYY-MM-DD date.");if(!validDate(input.deadline))errors.push("Deadline must use a valid YYYY-MM-DD date.");if(!validDate(input.opening_date))errors.push("Opening date must use a valid YYYY-MM-DD date.");if(input.estimated_value!==null&&(!Number.isFinite(input.estimated_value)||Number(input.estimated_value)<0||Number(input.estimated_value)>1_000_000_000))errors.push("Estimated value must be a realistic positive number or unknown.");if(input.school_scope==="School Specific"&&!input.schools?.length)errors.push("Select at least one school for a school-specific opportunity.");if(Array.isArray(input.schools)&&(input.schools.length>20||input.schools.some((school)=>typeof school!=="string"||school.length>160)))errors.push("School restrictions are invalid.");if(Array.isArray(input.tags)&&(input.tags.length>50||input.tags.some((tag)=>typeof tag!=="string"||tag.length>80)))errors.push("Tags are invalid.");
  return errors.length?{errors}:{data:{...input,title:input.title!.trim(),organization:input.organization!.trim(),category:input.category!.trim(),description:input.description!.trim(),eligibility:input.eligibility!.trim(),official_source_url:input.official_source_url!.trim(),type:input.type!,school_scope:input.school_scope!,schools:Array.isArray(input.schools)?[...new Set(input.schools.map((school)=>school.trim()).filter(Boolean))]:[],verification_status:input.verification_status!,last_verified:input.last_verified!,deadline:input.deadline||null,estimated_value:input.estimated_value===null?null:Number(input.estimated_value),tags:Array.isArray(input.tags)?[...new Set(input.tags.map((tag)=>tag.trim()).filter(Boolean))]:[],lifecycle_state:input.lifecycle_state!,lifecycle_confidence:input.lifecycle_confidence!,lifecycle_reason:input.lifecycle_reason!,lifecycle_review_note:input.lifecycle_review_note!.trim(),opening_date:input.opening_date||null,recurrence_type:input.recurrence_type??null},errors:[]};
}

export function createOpportunity(id:string,input:OpportunityInput):Opportunity{return{id,title:input.title,type:input.type,category:input.category,description:input.description,organization:input.organization,school_scope:input.school_scope,schools:input.schools,majors:["Any Major"],academic_years:["Any Year"],eligibility:input.eligibility,estimated_value:input.estimated_value,application_deadline:input.deadline,deadline:input.deadline,recurring:Boolean(input.recurrence_type),location:"Varies",remote:null,paid:null,tags:input.tags,official_source:input.official_source_url,official_source_url:input.official_source_url,verification_status:input.verification_status,last_verified:input.last_verified,reviewer_notes:"Managed through the UnlockED content system.",estimated_value_note:input.estimated_value===null?"Unknown — no verified dollar value is documented by the official source.":"Value entered by an authorized UnlockED reviewer.",date_added:new Date().toISOString().slice(0,10),difficulty:null,prestige:null,icon:null,featured:false,hidden_gem:false,metadata:{deadlineType:input.lifecycle_state==="rolling"?"rolling":input.deadline?"fixed":input.lifecycle_state==="closed"?"current_cycle_closed":"not_announced",reviewScore:input.verification_status==="verified"?90:50,claimUrl:input.official_source_url}}}
