import { opportunityTypes, type Opportunity, type OpportunityScope, type VerificationStatus } from "@/data/opportunities";

export type OpportunityInput = Pick<Opportunity,"title"|"organization"|"type"|"category"|"description"|"eligibility"|"school_scope"|"schools"|"verification_status"|"last_verified"|"tags"> & { official_source_url:string; deadline:string|null; estimated_value:number|null };
const statuses:VerificationStatus[]=["verified","needs_review","expired","incomplete","community_reported"];
const date=/^\d{4}-\d{2}-\d{2}$/;
export function validateOpportunityInput(value:unknown):{data?:OpportunityInput;errors:string[]}{
  const input=value as Partial<OpportunityInput>;const errors:string[]=[];const required:[[keyof OpportunityInput,string]]|[keyof OpportunityInput,string][]=[["title","Title"],["organization","Organization"],["category","Category"],["description","Description"],["eligibility","Eligibility"],["official_source_url","Official source URL"],["last_verified","Last verified date"]];
  for(const[field,label]of required)if(typeof input[field]!=="string"||!String(input[field]).trim())errors.push(`${label} is required.`);
  try{if(input.official_source_url&&new URL(input.official_source_url).protocol!=="https:")errors.push("Official source URL must use HTTPS.")}catch{errors.push("Official source URL is invalid.")}
  if(!opportunityTypes.includes(input.type as never))errors.push("Opportunity type is invalid.");if(!["National","School Specific"].includes(input.school_scope as OpportunityScope))errors.push("School scope is invalid.");if(!statuses.includes(input.verification_status as VerificationStatus))errors.push("Verification status is invalid.");if(input.last_verified&&!date.test(input.last_verified))errors.push("Last verified date must use YYYY-MM-DD.");if(input.deadline&&!date.test(input.deadline))errors.push("Deadline must use YYYY-MM-DD.");if(input.estimated_value!==null&&(!Number.isFinite(input.estimated_value)||Number(input.estimated_value)<0))errors.push("Estimated value must be a positive number or unknown.");if(input.school_scope==="School Specific"&&!input.schools?.length)errors.push("Select at least one school for a school-specific opportunity.");
  return errors.length?{errors}:{data:{...input,title:input.title!.trim(),organization:input.organization!.trim(),category:input.category!.trim(),description:input.description!.trim(),eligibility:input.eligibility!.trim(),official_source_url:input.official_source_url!.trim(),type:input.type!,school_scope:input.school_scope!,schools:Array.isArray(input.schools)?input.schools:[],verification_status:input.verification_status!,last_verified:input.last_verified!,deadline:input.deadline||null,estimated_value:input.estimated_value===null?null:Number(input.estimated_value),tags:Array.isArray(input.tags)?[...new Set(input.tags.map((tag)=>String(tag).trim()).filter(Boolean))]:[]},errors:[]};
}

export function createOpportunity(id:string,input:OpportunityInput):Opportunity{return{id,title:input.title,type:input.type,category:input.category,description:input.description,organization:input.organization,school_scope:input.school_scope,schools:input.schools,majors:["Any Major"],academic_years:["Any Year"],eligibility:input.eligibility,estimated_value:input.estimated_value,application_deadline:input.deadline,deadline:input.deadline,recurring:false,location:"Varies",remote:null,paid:null,tags:input.tags,official_source:input.official_source_url,official_source_url:input.official_source_url,verification_status:input.verification_status,last_verified:input.last_verified,reviewer_notes:"Managed through the UnlockED content system.",estimated_value_note:input.estimated_value===null?"Unknown — no verified dollar value is documented by the official source.":"Value entered by an authorized UnlockED reviewer.",date_added:new Date().toISOString().slice(0,10),difficulty:null,prestige:null,icon:null,featured:false,hidden_gem:false,metadata:{deadlineType:input.deadline?"fixed":"not_announced",reviewScore:input.verification_status==="verified"?90:50,claimUrl:input.official_source_url}}}
