import assert from "node:assert/strict";
import http from "node:http";
import net from "node:net";
import next from "next";
import { chromium, type BrowserContext, type Page } from "playwright";
import { opportunities } from "../data/opportunities";

type StoredValue = { value: unknown; expiresAt?: number }; const store = new Map<string, StoredValue>();
const live = (key: string) => { const item = store.get(key); if (item?.expiresAt && item.expiresAt <= Date.now()) { store.delete(key); return undefined; } return item; };
async function listen(server: net.Server, port = 0) { await new Promise<void>((resolve, reject) => server.once("error", reject).listen(port, "127.0.0.1", resolve)); return (server.address() as net.AddressInfo).port; }
async function freePort() { const server = net.createServer(); const port = await listen(server); await new Promise<void>((resolve) => server.close(() => resolve())); return port; }
function kvServer() { return http.createServer(async (request, response) => { const chunks: Buffer[] = []; for await (const chunk of request) chunks.push(Buffer.from(chunk)); const command = JSON.parse(Buffer.concat(chunks).toString("utf8")) as unknown[]; const [operation, rawKey, ...rest] = command; const key = String(rawKey); let result: unknown = null; if (operation === "GET") result = live(key)?.value ?? null; else if (operation === "SET") { if (!rest.includes("NX") || !live(key)) { const expiry = rest.indexOf("EX"); store.set(key, { value: rest[0], expiresAt: expiry >= 0 ? Date.now() + Number(rest[expiry + 1]) * 1000 : undefined }); result = "OK"; } } else if (operation === "DEL") result = store.delete(key) ? 1 : 0; else if (operation === "EVAL") { const lockKey = String(command[3]); if (live(lockKey)?.value === command[4]) { store.delete(lockKey); result = 1; } } else if (["SADD","LPUSH","LTRIM"].includes(String(operation))) result = 1; else if (["SMEMBERS","LRANGE"].includes(String(operation))) result = []; response.writeHead(200, { "Content-Type": "application/json" }); response.end(JSON.stringify({ result })); }); }
async function install(context: BrowserContext, origin: string, token: string) { await context.addCookies([{ name: "unlocked_session", value: token, url: origin, httpOnly: true, sameSite: "Lax", expires: Math.floor(Date.now() / 1000) + 3600 }]); await context.route("**/*", (route) => new URL(route.request().url()).origin === origin ? route.continue() : route.fulfill({ status: 204, body: "" })); }
function observe(page: Page) { const errors: string[] = []; page.on("console", (message) => { if (message.type() === "error" && !message.text().includes("_vercel")) errors.push(message.text()); }); page.on("pageerror", (error) => errors.push(error.message)); return () => assert.deepEqual(errors, [], `Browser errors: ${errors.join(" | ")}`); }
async function noOverflow(page: Page, label: string) { const amount = await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth); assert.ok(amount <= 1, `${label} has ${amount}px horizontal overflow`); }

const kv = kvServer(); const kvPort = await listen(kv); process.env.AUTH_SECRET = "passport-browser-secret-with-sufficient-length"; process.env.KV_REST_API_URL = `http://127.0.0.1:${kvPort}`; process.env.KV_REST_API_TOKEN = "passport-browser-token"; const appPort = await freePort(); process.env.NEXT_PUBLIC_APP_URL = `http://127.0.0.1:${appPort}`;
const { createSession, mergeAccountData, upsertUser } = await import("../lib/auth-store"); const item = opportunities[0]!; const now = "2026-09-04T12:00:00.000Z"; const user = await upsertUser({ googleSub: "passport-browser-owner", email: "passport@example.test", name: "Avery Chen" });
await mergeAccountData(user.id, { profile: { firstName: "Avery", lastName: "Chen", schoolSlug: "university-of-chicago", schoolName: "University of Chicago", major: "Mathematics", secondaryMajor: "Computer Science", graduationYear: "2030", year: "First year", careerGoal: "Quantitative research", interests: "Statistics", specificCareerInterests: ["Quantitative Trading"], onboardingCompletedAt: now }, onboardingComplete: true, firstLaunchComplete: true, accomplishments: { "manual:research": { id: "manual:research", source: "manual", canonicalOpportunityId: item.id, snapshot: { title: "Research Prize", organization: "Student Lab", capturedAt: now }, kind: "research", outcome: "awarded", outcomeDate: "2026-05-10", description: "Recognized for empirical work.", notes: "This note must stay private.", skills: ["Python", "Statistics"], hidden: false, createdAt: now, updatedAt: now, version: 0 } }, tracker: { [item.id]: { id: item.id, status: "Accepted", savedAt: now, updatedAt: now, version: 0, history: [] } }, activity: { viewed: [], saved: [item.id], claimed: [], tracked: { [item.id]: { id: item.id, status: "Accepted", savedAt: now, updatedAt: now, version: 0, history: [] } } } });
const session = await createSession(user); const app = next({ dev: true, dir: process.cwd(), hostname: "127.0.0.1", port: appPort }); await app.prepare(); const server = http.createServer((request, response) => app.getRequestHandler()(request, response)); await listen(server, appPort); const origin = `http://127.0.0.1:${appPort}`; const browser = await chromium.launch({ headless: true }); let failure: unknown;
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: "reduce" }); await install(context, origin, session.token); const page = await context.newPage(); const noErrors = observe(page); await page.goto(`${origin}/passport`, { waitUntil: "domcontentloaded", timeout: 60000 }); await page.getByRole("heading", { name: "Your college journey, in one place." }).waitFor(); await page.getByText("Research Prize").first().waitFor(); await noOverflow(page, "private Passport desktop");
  const result = await page.evaluate(async ({ opportunityId }) => { const read = await fetch("/api/passport").then((response) => response.json()); const passport = read.passport; passport.sharingEnabled = true; passport.showSchool = true; passport.showAcademicDetails = true; passport.showCareerInterests = true; passport.visibleAccomplishmentIds = ["manual:research"]; passport.highlightIds = ["manual:research"]; passport.collections = [{ id: "collection:quant", title: "Quant opportunities to watch", description: "A focused starting point.", opportunityIds: [opportunityId], sharingEnabled: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }]; const response = await fetch("/api/passport", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ passport }) }); return await response.json(); }, { opportunityId: item.id });
  assert.equal(result.ok, true); assert.match(result.shareUrl, /^\/p\/[A-Za-z0-9_-]+$/); const publicToken = result.passport.shareToken; const collectionToken = result.passport.collections[0].shareToken;
  await page.goto(`${origin}/p/${publicToken}`, { waitUntil: "domcontentloaded" }); await page.getByRole("heading", { name: "Avery Chen" }).waitFor(); await page.getByText("Research Prize").first().waitFor(); assert.equal(await page.getByText("This note must stay private.").count(), 0); await page.screenshot({ path: "/tmp/unlocked-passport-public.png", fullPage: true }); await page.getByRole("link", { name: /Explore opportunity/ }).first().click(); await page.getByText("You can understand this opportunity before creating an account.").waitFor(); await noOverflow(page, "public opportunity desktop"); const clickStats = await page.evaluate(() => fetch("/api/passport").then((response) => response.json())); assert.equal(clickStats.stats.opportunityClicks, 1, "Passport should count anonymous opportunity clicks");
  await page.goto(`${origin}/c/${collectionToken}`, { waitUntil: "domcontentloaded" }); await page.getByRole("heading", { name: "Quant opportunities to watch" }).waitFor(); await page.getByText(item.title).waitFor(); await page.getByRole("button", { name: "Copy to my collections" }).click(); await page.getByRole("button", { name: "Saved to my collections" }).waitFor(); noErrors(); await context.close();
  for (const width of [640, 390]) { const mobile = await browser.newContext({ viewport: { width, height: 844 }, reducedMotion: "reduce" }); const page = await mobile.newPage(); await page.goto(`${origin}/p/${publicToken}`, { waitUntil: "domcontentloaded" }); await page.getByRole("heading", { name: "Avery Chen" }).waitFor(); await noOverflow(page, `public Passport ${width}`); await page.goto(`${origin}/c/${collectionToken}`, { waitUntil: "domcontentloaded" }); await noOverflow(page, `public collection ${width}`); await mobile.close(); }
  console.log("Opportunity Passport browser checks passed", { viewports: [1440, 640, 390], states: ["private", "published", "milestone", "collection", "public-opportunity"] });
} catch (error) { failure = error; } finally { await browser.close(); server.closeAllConnections(); await Promise.race([new Promise<void>((resolve) => server.close(() => resolve())), new Promise<void>((resolve) => setTimeout(resolve, 2000))]); await Promise.race([app.close(), new Promise<void>((resolve) => setTimeout(resolve, 5000))]); kv.closeAllConnections(); await Promise.race([new Promise<void>((resolve) => kv.close(() => resolve())), new Promise<void>((resolve) => setTimeout(resolve, 2000))]); }
if (failure) { console.error("Opportunity Passport browser checks failed", failure); process.exit(1); }
process.exit(0);
