import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { deadlineLabel, getOpportunity, opportunities } from "@/data/opportunities";
import { ArrowIcon } from "@/components/icons";

export function generateStaticParams(){return opportunities.map(({id})=>({id}))}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const item=getOpportunity((await params).id);if(!item)return{title:"Opportunity not found"};return{title:item.title,description:item.description,alternates:{canonical:`/opportunities/${item.id}`}}}
export default async function Page({params}:{params:Promise<{id:string}>}){const item=getOpportunity((await params).id);if(!item)notFound();const detail=item.type==="Career"?deadlineLabel(item):item.type==="Benefit"?item.metadata.valueLabel??"Unknown":item.metadata.studentOffer??"See official source";return <><section className="border-b-2 border-ink bg-white px-5 py-12 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/opportunities" className="text-sm font-bold text-forest">← All opportunities</Link><div className="mt-8 grid gap-8 border-t border-ink/20 pt-8 md:grid-cols-[1fr_240px]"><div><div className="flex flex-wrap gap-3"><span className="rule-label text-forest">{item.type}</span><span className="rule-label text-ink/40">{item.category}</span><span className="rule-label text-trust">{item.verification_status==="verified_recently"?"Verified Recently":"Needs Review"}</span></div><p className="mt-5 text-sm font-bold uppercase tracking-widest text-ink/40">{item.organization}</p><h1 className="mt-2 font-editorial text-5xl font-bold">{item.title}</h1><p className="mt-5 text-lg leading-8 text-ink/60">{item.description}</p></div><div className="border-l-2 border-ink pl-6"><p className="rule-label text-ink/40">{item.type==="Career"?"Deadline":item.type==="Benefit"?"Value":"Student access"}</p><p className="mt-3 font-editorial text-2xl font-bold text-forest">{detail}</p></div></div></div></section><section className="px-5 py-12 sm:px-8"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[1fr_300px]"><div className="border-y-2 border-ink bg-white p-6"><h2 className="font-editorial text-2xl font-bold">Eligibility</h2><p className="mt-4 leading-7 text-ink/60">{item.eligibility}</p><dl className="mt-8 grid gap-5 border-t border-ink/20 pt-6 sm:grid-cols-2"><div><dt className="rule-label text-ink/35">Majors</dt><dd className="mt-2 text-sm">{item.majors.join(", ")}</dd></div><div><dt className="rule-label text-ink/35">Academic years</dt><dd className="mt-2 text-sm">{item.academic_years.join(", ")}</dd></div><div><dt className="rule-label text-ink/35">Scope</dt><dd className="mt-2 text-sm">{item.school_scope}</dd></div><div><dt className="rule-label text-ink/35">Location</dt><dd className="mt-2 text-sm">{item.location}</dd></div><div><dt className="rule-label text-ink/35">Paid</dt><dd className="mt-2 text-sm">{item.paid===null?"Varies":item.paid?"Paid":"Unpaid"}</dd></div><div><dt className="rule-label text-ink/35">Remote</dt><dd className="mt-2 text-sm">{item.remote===null?"Varies":item.remote?"Remote":"In person"}</dd></div></dl></div><aside className="bg-ink p-6 text-white"><p className="rule-label text-white/45">Last verified</p><p className="mt-2 font-bold">{item.last_verified}</p><a href={item.official_source} target="_blank" rel="noreferrer" className="mt-7 flex items-center justify-center gap-2 bg-lime px-5 py-3 font-bold text-ink">Official source <ArrowIcon/></a></aside></div></section></>}
