import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { deadlineLabel, getOpportunity, opportunities } from "@/data/opportunities";
import { ArrowIcon } from "@/components/icons";
import { StatusBadge } from "@/components/status-badge";

export function generateStaticParams(){return opportunities.map(({id})=>({id}))}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const item=getOpportunity((await params).id);if(!item)return{title:"Opportunity not found"};return{title:item.title,description:item.description,alternates:{canonical:`/opportunities/${item.id}`}}}

export default async function Page({params}:{params:Promise<{id:string}>}){
  const item=getOpportunity((await params).id);if(!item)notFound();
  const deadlineType=item.type==="Career"||item.type==="Research";
  const detail=deadlineType?deadlineLabel(item):item.type==="Scholarship"?item.metadata.awardAmountLabel??"Amount varies":item.type==="Benefit"?item.metadata.valueLabel??"Unknown":item.metadata.studentOffer??"See official source";
  const detailLabel=deadlineType?"Deadline":item.type==="Scholarship"?"Award amount":item.type==="Benefit"?"Value":"Student access";
  return <>
    <section className="border-b-2 border-ink bg-white px-5 py-12 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/opportunities" className="text-sm font-bold text-forest">← All opportunities</Link><div className="mt-8 grid gap-8 border-t border-ink/20 pt-8 md:grid-cols-[1fr_240px]"><div><div className="flex flex-wrap gap-3"><span className="rule-label text-forest">{item.type}</span><span className="rule-label text-ink/40">{item.category}</span><StatusBadge status={item.verification_status}/></div><p className="mt-5 text-sm font-bold uppercase tracking-widest text-ink/40">{item.organization}</p><h1 className="mt-2 font-editorial text-4xl font-bold sm:text-5xl">{item.title}</h1><p className="mt-5 text-lg leading-8 text-ink/60">{item.description}</p></div><div className="border-t-2 border-ink pt-5 md:border-l-2 md:border-t-0 md:pl-6 md:pt-0"><p className="rule-label text-ink/40">{detailLabel}</p><p className="mt-3 font-editorial text-2xl font-bold text-forest">{detail}</p>{item.type==="Scholarship"&&<><p className="mt-6 rule-label text-ink/40">Deadline</p><p className="mt-2 font-bold">{deadlineLabel(item)}</p></>}</div></div></div></section>
    <section className="px-5 py-12 sm:px-8"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[1fr_300px]"><div className="border-y-2 border-ink bg-white p-6"><h2 className="font-editorial text-2xl font-bold">Who can apply or claim</h2><p className="mt-4 leading-7 text-ink/60">{item.eligibility}</p>{item.type==="Scholarship"&&<div className="mt-8 border-t border-ink/20 pt-6"><h2 className="font-editorial text-xl font-bold">Application requirements</h2><ul className="mt-4 space-y-2 text-sm text-ink/60">{item.metadata.applicationRequirements?.map((requirement)=><li key={requirement}>— {requirement}</li>)}</ul><p className="mt-5 text-sm"><span className="font-bold">Renewable:</span> {item.metadata.renewable===null?"Varies by award":item.metadata.renewable?"Yes":"One-time"}</p></div>}<dl className="mt-8 grid gap-5 border-t border-ink/20 pt-6 sm:grid-cols-2"><div><dt className="rule-label text-ink/35">Majors</dt><dd className="mt-2 text-sm">{item.majors.join(", ")}</dd></div><div><dt className="rule-label text-ink/35">Academic years</dt><dd className="mt-2 text-sm">{item.academic_years.join(", ")}</dd></div><div><dt className="rule-label text-ink/35">Scope</dt><dd className="mt-2 text-sm">{item.school_scope}</dd></div><div><dt className="rule-label text-ink/35">Location</dt><dd className="mt-2 text-sm">{item.location}</dd></div><div><dt className="rule-label text-ink/35">Paid</dt><dd className="mt-2 text-sm">{item.paid===null?"Varies":item.paid?"Paid":"Unpaid"}</dd></div><div><dt className="rule-label text-ink/35">Remote</dt><dd className="mt-2 text-sm">{item.remote===null?"Varies":item.remote?"Remote":"In person"}</dd></div>{item.type==="Research"&&<><div><dt className="rule-label text-ink/35">Department</dt><dd className="mt-2 text-sm">{item.metadata.department}</dd></div><div><dt className="rule-label text-ink/35">Research area</dt><dd className="mt-2 text-sm">{item.metadata.researchArea}</dd></div><div><dt className="rule-label text-ink/35">Professor</dt><dd className="mt-2 text-sm">{item.metadata.professor??"Varies by project"}</dd></div><div><dt className="rule-label text-ink/35">Term</dt><dd className="mt-2 text-sm">{item.metadata.semesters?.join(", ")}</dd></div></>}</dl></div><aside className="bg-ink p-6 text-white"><p className="rule-label text-white/45">Last verified</p><p className="mt-2 font-bold">{item.last_verified}</p><a href={item.official_source} target="_blank" rel="noreferrer" className="mt-7 flex items-center justify-center gap-2 bg-lime px-5 py-3 font-bold text-ink">Official source <ArrowIcon/></a><Link href={`/contact?opportunity=${encodeURIComponent(item.title)}`} className="mt-4 flex min-h-11 items-center justify-center border border-white/30 px-4 text-center text-xs font-bold uppercase tracking-wider text-white/70 hover:border-white hover:text-white">Report outdated information</Link></aside></div></section>
  </>
}
