import type { Metadata } from "next";
import type { ReactNode } from "react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { deadlineLabel, getOpportunity, getRelatedOpportunities, opportunities, type Opportunity } from "@/data/opportunities";
import { schools } from "@/data/seed";
import { StatusBadge } from "@/components/status-badge";
import { OpportunityActivityActions } from "@/components/opportunity-activity";
import { ArrowIcon, SparkIcon } from "@/components/icons";

export function generateStaticParams(){return opportunities.map(({id})=>({id}))}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const item=getOpportunity((await params).id);if(!item)return{title:"Opportunity not found"};const title=`${item.title}: Eligibility, Value & How to Apply`;const description=`A verified guide to ${item.title} from ${item.organization}, including eligibility, value, timeline, official source, and application guidance.`;return{title,description,alternates:{canonical:`/opportunities/${item.id}`},openGraph:{title,description,url:`/opportunities/${item.id}`,type:"article"}}}

const unknown = (label:string) => `Not documented by the official source reviewed by UnlockED. Check the current official page for ${label}.`;
const formatMoney = (value:number) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);

function applicationSteps(item:Opportunity){
  if(item.metadata.claimSteps?.length)return item.metadata.claimSteps;
  const materials=item.metadata.applicationRequirements?.length?`Prepare the documented materials: ${item.metadata.applicationRequirements.join(", ")}.`:"Review the official page for required materials; UnlockED has not documented a complete materials list.";
  return ["Open the current official opportunity page linked in this guide.","Confirm that you meet the current eligibility rules and check whether a deadline has been published.",materials,"Follow the provider’s current application or access instructions. UnlockED has not verified a more specific submission sequence.","Retain the provider’s confirmation and monitor the account or contact method used to apply."];
}

function valueLabel(item:Opportunity){if(item.estimated_value)return `${formatMoney(item.estimated_value)}+`;if(item.type==="Scholarship")return item.metadata.awardAmountLabel??"Amount not documented";if(item.type==="Benefit")return item.metadata.valueLabel??"Value not documented";return "No verified dollar value"}
function renewal(item:Opportunity){if(item.metadata.renewalNotes)return item.metadata.renewalNotes;if(item.type==="Scholarship"&&item.metadata.renewable!==undefined)return item.metadata.renewable===null?"Renewal varies by award; confirm on the official source.":item.metadata.renewable?"The catalog marks this award renewable; confirm current renewal requirements on the official source.":"The catalog marks this as a one-time award.";if(item.recurring)return"The opportunity is marked recurring, but its recurrence schedule is not documented.";return unknown("renewal or recurrence terms")}
function whyThisMatters(item:Opportunity){
  const audience=`${item.majors.join(", ")} students in ${item.academic_years.join(", ").toLowerCase()}`;
  const skills=item.type==="AI"?`Using this tool may help students practice ${item.category.toLowerCase()} workflows, but skill development depends on how the tool is used.`:item.type==="Career"?`Participation may help students practice skills connected to ${item.category.toLowerCase()}, although exact responsibilities vary by role and are not fully documented in the catalog.`:item.type==="Research"?`This program may support practice in research methods and technical communication; the exact skills depend on the assigned project and department.`:item.type==="Scholarship"?`The award does not guarantee a skill outcome, though its documented application requirements may give applicants practice preparing academic materials.`:item.category==="Software"?`Access may help students build familiarity with ${item.organization} tools, but no specific learning outcome is guaranteed.`:`No specific skill-development outcome is documented for this ${item.type.toLowerCase()}.`;
  const reason=item.estimated_value?`Students should care because eligible participation may provide ${formatMoney(item.estimated_value)} in documented value.`:`Students should care if the documented access, experience, or resource directly supports their current academic or career priorities; no verified dollar value is available.`;
  const impact=item.type==="Scholarship"?`Long-term impact depends on receiving the award and how the funds are used; an award may reduce education costs but is not guaranteed.`:item.type==="Benefit"?`The long-term impact is primarily access or savings and varies with actual use, continued eligibility, and provider terms.`:item.type==="AI"?`Any academic or productivity impact varies by use case, course rules, and the provider’s current access limits.`:`Career, academic, or networking impact varies by selection, participation, project quality, and the experience offered by ${item.organization}.`;
  return[skills,reason,`${audience} who meet the stated eligibility rules are the clearest potential beneficiaries.`,impact];
}

export default async function Page({params}:{params:Promise<{id:string}>}){
  const item=getOpportunity((await params).id);if(!item)notFound();
  const related=getRelatedOpportunities(item,5);
  const schoolNames=item.schools.map((slug)=>schools.find((school)=>school.slug===slug)?.name??slug);
  const requirements=[item.eligibility,...(item.metadata.applicationRequirements??[]),...(item.metadata.eligibilityNotes??[])];
  const gpa=requirements.find((value)=>/\bgpa\b/i.test(value))??unknown("GPA requirements");
  const citizenship=requirements.find((value)=>/citizen|residen|nationality|international|country/i.test(value))??unknown("citizenship or residency requirements");
  const prerequisites=item.metadata.applicationRequirements?.length?item.metadata.applicationRequirements.join("; "):unknown("prerequisites");
  const faq=[
    {q:`Is ${item.title} currently verified?`,a:`UnlockED lists this opportunity as ${item.verification_status.replaceAll("_"," ")} and last reviewed it on ${item.last_verified}. Always confirm current terms on the official source.`},
    {q:`Who is ${item.title} for?`,a:item.eligibility},
    {q:`What is ${item.title} worth?`,a:item.estimated_value?`The catalog contains a documented or reasonably calculated value of ${formatMoney(item.estimated_value)}. Actual value depends on eligibility and use.`:"No verified dollar value is currently documented."},
    {q:`When is the deadline?`,a:item.application_deadline?`The documented deadline is ${deadlineLabel(item)}.`:unknown("the current deadline")},
    {q:"Where should I apply or claim it?",a:`Use the official ${item.organization} source linked on this page. UnlockED does not accept applications or determine eligibility.`},
  ];
  const jsonLd={"@context":"https://schema.org","@type":"Article",headline:item.title,description:item.description,dateModified:item.last_verified,author:{"@type":"Organization",name:"UnlockED"},publisher:{"@type":"Organization",name:"UnlockED"},mainEntityOfPage:`https://unlocked.education/opportunities/${item.id}`};
  const faqLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(({q,a})=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqLd)}}/>
    <header className="border-b-2 border-ink bg-white px-5 py-10 sm:px-8 sm:py-14"><div className="mx-auto max-w-6xl"><Link href="/opportunities" className="text-sm font-bold text-forest">← Student opportunity directory</Link><div className="mt-7 grid gap-8 border-t border-ink/20 pt-7 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><span className="rule-label text-forest">{item.type}</span><span className="rule-label text-ink/40">{item.category}</span><StatusBadge status={item.verification_status}/></div><p className="mt-5 text-sm font-bold uppercase tracking-widest text-ink/40">{item.organization}</p><h1 className="mt-2 font-editorial text-4xl font-bold leading-tight sm:text-5xl">{item.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-ink/60">{item.description}</p></div><aside className="border-t-2 border-ink pt-5 lg:border-l-2 lg:border-t-0 lg:pl-6 lg:pt-0"><p className="rule-label text-ink/40">Estimated value</p><p className="mt-2 font-editorial text-3xl font-bold text-forest">{valueLabel(item)}</p><p className="mt-6 rule-label text-ink/40">Last verified</p><p className="mt-2 font-bold">{item.last_verified}</p><OpportunityActivityActions opportunityId={item.id} type={item.type} officialSource={item.official_source}/></aside></div></div></header>

    <main className="px-5 py-10 sm:px-8 sm:py-14"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[minmax(0,1fr)_260px]"><article className="space-y-12">
      <GuideSection eyebrow="Overview" title={`What ${item.title} offers`}><div className="grid gap-5 sm:grid-cols-3"><Fact title="What it is" text={item.description}/><Fact title="Why it matters" text={item.estimated_value?`It may provide ${formatMoney(item.estimated_value)} in documented value for eligible students.`:`It gives eligible students access to a verified ${item.category.toLowerCase()} opportunity from ${item.organization}; no dollar value is documented.`}/><Fact title="Who should care" text={`${item.majors.join(", ")} students in ${item.academic_years.join(", ").toLowerCase()} who meet the stated eligibility rules.`}/></div></GuideSection>

      <section aria-labelledby="why-this-matters"><div className="border-y-2 border-ink bg-white p-5 sm:p-7"><div className="flex items-center gap-3 text-forest"><span className="grid h-9 w-9 shrink-0 place-items-center border border-forest/30 bg-paper"><SparkIcon className="h-5 w-5"/></span><div><p className="rule-label">Student impact</p><h2 id="why-this-matters" className="mt-1 font-editorial text-3xl font-bold text-ink">Why This Matters</h2></div></div><div className="mt-5 space-y-3 border-l-2 border-gold pl-4">{whyThisMatters(item).map((sentence)=><p key={sentence} className="text-sm leading-6 text-ink/65">{sentence}</p>)}</div></div></section>

      <GuideSection eyebrow="Eligibility" title="Who can apply or claim"><p className="leading-7 text-ink/65">{item.eligibility}</p><dl className="mt-6 grid border-l border-t border-ink/15 sm:grid-cols-2"><Detail label="Eligible schools" value={item.school_scope==="National"?"National opportunity; no school list restriction is recorded. Provider restrictions may still apply.":schoolNames.join(", ")||unknown("eligible schools")}/><Detail label="Eligible majors" value={item.majors.join(", ")}/><Detail label="Academic years" value={item.academic_years.join(", ")}/><Detail label="GPA requirements" value={gpa}/><Detail label="Citizenship / location" value={citizenship}/><Detail label="Prerequisites" value={prerequisites}/></dl></GuideSection>

      <GuideSection eyebrow="How to claim or apply" title="A clear path to the official process"><ol className="mt-2 border-y-2 border-ink bg-white">{applicationSteps(item).map((step,index)=><li key={`${index}-${step}`} className="grid grid-cols-[36px_1fr] gap-4 border-b border-ink/15 p-4 last:border-b-0 sm:p-5"><span className="font-mono text-xs font-bold text-forest">{String(index+1).padStart(2,"0")}</span><p className="text-sm leading-6 text-ink/65">{step}</p></li>)}</ol><p className="mt-4 text-xs leading-5 text-ink/40">Application processes can change. The official provider page controls current requirements and submission steps.</p></GuideSection>

      <GuideSection eyebrow="Estimated value" title="What the opportunity may be worth"><dl className="grid border-l border-t border-ink/15 sm:grid-cols-2"><Detail label="Dollar value" value={valueLabel(item)}/><Detail label="Time savings" value={unknown("time-savings estimates")}/><Detail label="Career impact" value={item.prestige?`${item.prestige} editorial prestige estimate. This is not a provider guarantee.`:unknown("career-impact estimates")}/><Detail label="Difficulty" value={item.difficulty??unknown("selectivity or difficulty")}/></dl></GuideSection>

      <GuideSection eyebrow="Timeline" title="Dates and renewal information"><dl className="grid border-l border-t border-ink/15 sm:grid-cols-2"><Detail label="Opens" value={unknown("the opening date")}/><Detail label="Deadline" value={item.application_deadline?deadlineLabel(item):deadlineLabel(item)}/><Detail label="Decision timeline" value={unknown("the decision or approval timeline")}/><Detail label="Renewal / recurrence" value={renewal(item)}/></dl></GuideSection>

      <GuideSection eyebrow="Frequently asked questions" title={`Questions students ask about ${item.title}`}><div className="border-t-2 border-ink">{faq.map(({q,a})=><details key={q} className="border-b border-ink/20 bg-white p-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 text-sm leading-6 text-ink/60">{a}</p></details>)}</div></GuideSection>

      <GuideSection eyebrow="Similar opportunities" title="Continue exploring verified options"><div className="grid border-l border-t border-ink/15 sm:grid-cols-2">{related.map((candidate)=><Link key={candidate.id} href={`/opportunities/${candidate.id}`} className="group border-b border-r border-ink/15 bg-white p-5"><div className="flex flex-wrap items-center gap-2"><span className="rule-label text-forest">{candidate.type}</span><StatusBadge status={candidate.verification_status}/></div><h3 className="mt-3 font-editorial text-xl font-bold group-hover:text-forest">{candidate.title}</h3><p className="mt-2 text-xs font-bold uppercase tracking-wider text-ink/35">{candidate.organization}</p><p className="mt-3 line-clamp-2 text-sm leading-6 text-ink/50">{candidate.description}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider">Read guide <ArrowIcon/></span></Link>)}</div></GuideSection>
    </article>

    <aside className="h-fit border-y-2 border-ink bg-white p-5 lg:sticky lg:top-6"><p className="rule-label text-forest">Trust & verification</p><StatusBadge status={item.verification_status}/><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-ink/40">Official provider</dt><dd className="mt-1 font-bold">{item.organization}</dd></div><div><dt className="text-ink/40">Last verified</dt><dd className="mt-1 font-bold">{item.last_verified}</dd></div><div><dt className="text-ink/40">Source</dt><dd className="mt-1 break-words text-xs text-ink/55">{item.official_source}</dd></div></dl><a href={item.official_source} target="_blank" rel="noreferrer" className="mt-6 flex min-h-11 items-center justify-center gap-2 bg-ink px-4 text-xs font-bold uppercase tracking-wider text-white">Official source <ArrowIcon/></a><Link href={`/contact?opportunity=${encodeURIComponent(item.title)}`} className="mt-3 flex min-h-11 items-center justify-center border border-ink/20 px-4 text-center text-xs font-bold uppercase tracking-wider text-ink/60">Report outdated information</Link><p className="mt-4 text-[11px] leading-5 text-ink/40">UnlockED summarizes official information but does not administer this opportunity or determine eligibility.</p></aside>
    </div></main>
  </>
}

function GuideSection({eyebrow,title,children}:{eyebrow:string;title:string;children:ReactNode}){return <section><p className="rule-label text-forest">{eyebrow}</p><h2 className="mt-2 font-editorial text-3xl font-bold">{title}</h2><div className="mt-5">{children}</div></section>}
function Fact({title,text}:{title:string;text:string}){return <div className="border-t-2 border-ink pt-4"><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-ink/60">{text}</p></div>}
function Detail({label,value}:{label:string;value:string}){return <div className="border-b border-r border-ink/15 bg-white p-4"><dt className="rule-label text-ink/35">{label}</dt><dd className="mt-2 text-sm leading-6 text-ink/65">{value}</dd></div>}
