import "server-only";
import type { RecommendationCoaching } from "./types";

type CoachingSeed = Partial<RecommendationCoaching> & Pick<RecommendationCoaching, "recommendation" | "learnMore" | "whyThis" | "whatHappensNext" | "howDoIStart" | "successEvidence">;

function coaching(seed: CoachingSeed): RecommendationCoaching {
  const defaultAlternatives: RecommendationCoaching["alternatives"] = [
    { title: "Smaller version", whyChoose: "Use this when time is limited.", advantages: "Lower friction and faster evidence.", tradeoffs: "Less depth than the full recommendation.", bestFit: "Students with one or two hours this week.", timeCommitment: "1-2 hours this week.", unlocks: "A first piece of completion evidence." },
    { title: "Campus-supported path", whyChoose: "Use this when guidance or accountability would help.", advantages: "More feedback and structure.", tradeoffs: "May depend on office hours, club calendars, or staff availability.", bestFit: "Students who want reviewed work.", timeCommitment: "2-4 hours per week.", unlocks: "Reviewed work and a stronger next draft." },
    { title: "Opportunity-first path", whyChoose: "Use this when a verified deadline is close.", advantages: "Keeps urgent options alive.", tradeoffs: "May be less polished than building evidence first.", bestFit: "Students facing a near-term deadline.", timeCommitment: "Varies by official requirement.", unlocks: "A submitted or saved application path." },
  ];
  const defaultInfo: RecommendationCoaching["informationDrawer"] = {
    whatIsThis: seed.learnMore,
    whyItMatters: seed.whyThis,
    whoBenefitsMost: "Students whose current profile is missing visible evidence in this area.",
    skillsDeveloped: ["Planning", "Follow-through", "Communication"],
    difficulty: "Moderate",
    typicalTimeCommitment: "2-6 focused hours per week.",
    commonMisconceptions: ["This is not a prediction of admission, hiring, or funding.", "A smaller completed version is usually better than an ambitious unfinished one."],
    examples: ["A reviewed resume", "A finished project", "A documented experience", "A verified application plan"],
    relatedCareers: ["Software Engineering", "Research", "Finance", "Medicine", "Consulting"],
    relatedOpportunities: ["Internships", "Research", "Campus Jobs", "Scholarships", "Competitions"],
  };
  const base: RecommendationCoaching = {
    title: seed.recommendation,
    whyNow: "This is ranked now because it closes a current readiness gap before later application steps depend on it.",
    whyBeforeOthers: "It comes before lower-ranked options because it unlocks evidence or prerequisites used by later recommendations.",
    whyRankedAboveAlternatives: "It is ranked above alternatives because it most directly addresses the current readiness gap with the available time and profile evidence.",
    notRankedFirst: "Other recommendations were not ranked first because they either depend on this evidence, require more time, or have weaker fit with the current profile.",
    alternativePaths: ["Choose a smaller version of the same action.", "Use a campus office, course project, or club role to create equivalent evidence.", "Delay this only if a verified deadline requires immediate attention."],
    alternatives: defaultAlternatives,
    informationDrawer: defaultInfo,
    unlockChain: ["Foundation", "Visible evidence", "Stronger applications", "Interview or selection readiness"],
    trustBasis: ["Prerequisite relationships", "Academic guidance", "Recruiting norms"],
    simpleExplanation: seed.whyThis,
    whyThisApplies: seed.whyThis,
    prerequisites: ["Current profile evidence", "One focused work block"],
    estimatedTime: defaultInfo.typicalTimeCommitment,
    difficulty: defaultInfo.difficulty,
    skillsDeveloped: defaultInfo.skillsDeveloped,
    evidenceProduced: seed.successEvidence,
    firstStep: seed.howDoIStart[0] ?? "Choose the smallest concrete next step.",
    completionChecklist: seed.howDoIStart,
    supportingKnowledgeSourceIds: ["advisor.rules.core", "advisor.dependencies.core"],
    impactLabel: "High impact",
    ...seed,
  };
  const informationDrawer = { ...defaultInfo, ...(seed.informationDrawer ?? {}) };
  const alternatives = (seed.alternatives ?? defaultAlternatives).map((item, index) => ({
    ...defaultAlternatives[Math.min(index, defaultAlternatives.length - 1)],
    ...item,
  }));
  return {
    ...base,
    title: seed.title ?? seed.recommendation,
    simpleExplanation: seed.simpleExplanation ?? seed.whyThis,
    whyThisApplies: seed.whyThisApplies ?? seed.whyThis,
    whyRankedAboveAlternatives: seed.whyRankedAboveAlternatives ?? seed.whyBeforeOthers ?? base.whyRankedAboveAlternatives,
    prerequisites: seed.prerequisites ?? base.prerequisites,
    estimatedTime: seed.estimatedTime ?? informationDrawer.typicalTimeCommitment,
    difficulty: seed.difficulty ?? informationDrawer.difficulty,
    skillsDeveloped: seed.skillsDeveloped ?? informationDrawer.skillsDeveloped,
    evidenceProduced: seed.evidenceProduced ?? seed.successEvidence,
    firstStep: seed.firstStep ?? seed.howDoIStart[0] ?? base.firstStep,
    completionChecklist: seed.completionChecklist ?? seed.howDoIStart,
    supportingKnowledgeSourceIds: seed.supportingKnowledgeSourceIds ?? base.supportingKnowledgeSourceIds,
    alternatives,
    informationDrawer,
  };
}

const fallbackActionCoaching: RecommendationCoaching = coaching({
  recommendation: "Based on the current profile, the highest-impact next step is to create one piece of visible completion evidence.",
  learnMore: "This recommendation is tied to a reviewed readiness signal in the Advisor Brain framework.",
  whyThis: "The advisor prioritizes actions that create visible evidence and unblock later applications.",
  whatHappensNext: "After you complete this, the advisor can move you toward more selective opportunities.",
  howDoIStart: ["Write down the smallest concrete version of the action.", "Set one work block this week.", "Save evidence when it is complete."],
  successEvidence: "Inspectable output or verified completion evidence.",
});

export const actionKnowledge: Record<string, RecommendationCoaching> = {
  probability: coaching({
    recommendation: "Based on your current profile, the highest-impact next step is to strengthen probability before moving deeper into quantitative projects or interviews.",
    learnMore: "Probability is a core filter for quantitative finance, research, analytics, and many technical interviews.",
    whyThis: "A stronger probability foundation makes later projects and interview preparation more productive.",
    whyBeforeOthers: "It comes before more advanced quantitative work because weak probability makes projects and interview practice less useful.",
    alternativePaths: ["Take a formal probability course.", "Complete a structured online module with problem sets.", "Use a statistics or modeling project that clearly applies probability."],
    whatHappensNext: "Once this foundation is stronger, quantitative projects and selective applications become more credible.",
    howDoIStart: ["Pick one course or module.", "Solve a small set of problems twice per week.", "Save completed work as evidence."],
    successEvidence: "Completed course/module plus solved problem set or project.",
    informationDrawer: { skillsDeveloped: ["Probability", "Quantitative reasoning", "Problem solving"], difficulty: "High", typicalTimeCommitment: "4-6 focused hours per week.", relatedCareers: ["Quantitative Trading", "Data Science", "Research"], relatedOpportunities: ["Research", "Competitions", "Internships"], whatIsThis: "Probability study builds the foundation for reasoning under uncertainty.", whyItMatters: "Many quantitative roles use probability as a signal of preparation.", whoBenefitsMost: "Students targeting quantitative finance, analytics, data science, or research.", commonMisconceptions: ["Watching explanations is not the same as solving problems.", "A transcript alone is weaker than saved problem sets or applied work."], examples: ["Completed problem set", "Simulation notebook", "Short probability write-up"] },
    unlockChain: ["Probability", "Monte Carlo Project", "Research Experience", "Resume Update", "Quant Internship", "Interview Preparation"],
    trustBasis: ["Employer expectations", "Prerequisite relationships", "Recruiting norms"],
  }),
  statistics: coaching({
    recommendation: "Based on your current profile, the strongest next step is to complete one applied statistics analysis that you can explain clearly.",
    learnMore: "Statistics turns raw data into defensible claims, which matters across research, data, finance, healthcare, and policy paths.",
    whyThis: "Applied statistics helps you explain uncertainty and makes project work more credible.",
    alternativePaths: ["Use a class project.", "Analyze a public dataset.", "Join a research or lab project with a statistical component."],
    whatHappensNext: "A completed analysis can support research, internship, and scholarship applications.",
    howDoIStart: ["Choose a small dataset.", "Ask one clear question.", "Write a short summary with limitations."],
    successEvidence: "Completed analysis demonstrating inference and uncertainty.",
    unlockChain: ["Statistics", "Applied analysis", "Research or project evidence", "Resume update", "Stronger applications"],
  }),
  programming: coaching({
    recommendation: "Based on your current profile, the highest-impact next step is to build one working, documented programming project.",
    learnMore: "Programming is useful evidence when a student can show working, tested, documented code.",
    whyThis: "A finished technical artifact gives applications something concrete to evaluate beyond coursework.",
    alternativePaths: ["Build a small independent project.", "Contribute to a team project.", "Automate a task for a club, class, or campus office."],
    whatHappensNext: "A working project can unlock research, technical internships, campus developer roles, and stronger interview stories.",
    howDoIStart: ["Choose one narrow problem.", "Build the smallest working version.", "Add a README that explains what it does."],
    successEvidence: "Working, tested, documented code.",
    unlockChain: ["Programming", "Finished Project", "Technical Resume", "Research or Internship", "Interview Story"],
    trustBasis: ["Employer expectations", "Prerequisite relationships", "Recruiting norms"],
  }),
  quant_project: coaching({
    recommendation: "Based on your current profile, the best next move is to complete one quantitative project with code, results, and limitations.",
    learnMore: "A quantitative project shows that you can turn math, data, and judgment into an inspectable result.",
    whyThis: "Selective quantitative opportunities often reward proof of independent problem-solving.",
    alternativePaths: ["Backtest a simple strategy.", "Simulate a probability problem.", "Write up a data-driven finance or sports model."],
    whatHappensNext: "The project can become a resume bullet, interview story, or research starting point.",
    howDoIStart: ["Pick a question with public data.", "Define a simple baseline.", "Write down results and limitations."],
    successEvidence: "Finished report, code, results, and limitations.",
    unlockChain: ["Math or coding foundation", "Monte Carlo Project", "Research Experience", "Resume Update", "Quant Internship"],
  }),
  finished_projects: coaching({
    recommendation: "Based on your current profile, the highest-impact next step is to finish one substantial technical project before starting another.",
    learnMore: "Finished projects matter because they show follow-through, not just interest.",
    whyThis: "A complete project gives reviewers proof that you can scope, build, and explain work.",
    alternativePaths: ["Finish an old class project.", "Polish a hackathon project.", "Create a small portfolio piece from scratch."],
    whatHappensNext: "A finished artifact can support internships, research roles, and technical club applications.",
    howDoIStart: ["Pick one unfinished project.", "Define what 'done' means.", "Ship a README and one visible demo or result."],
    successEvidence: "Deployed or inspectable project with README and tests.",
    unlockChain: ["Project scope", "Finished artifact", "Resume evidence", "Internship or research application"],
  }),
  data_structures: coaching({
    recommendation: "Based on your current profile, the next priority is to learn data structures through a small implemented example set.",
    learnMore: "Data structures are the foundation for many software interviews and for writing code that handles real constraints.",
    whyThis: "Your profile points toward software roles, and data structures are still below the level needed for later interview preparation.",
    whyBeforeOthers: "It comes before heavier interview practice because practice is less useful before arrays, maps, stacks, queues, trees, and graphs feel usable.",
    alternativePaths: ["Complete a course module.", "Implement common structures in one repository.", "Use class assignments and add explanations after grading."],
    alternatives: [
      { title: "Implementation notebook", whyChoose: "Use this when you learn by building.", advantages: "Creates visible proof and reinforces concepts.", tradeoffs: "Takes more effort than watching lectures.", bestFit: "CS students without a finished technical artifact.", timeCommitment: "3-5 hours per week.", unlocks: "Algorithms practice and stronger project explanations." },
      { title: "Course-first path", whyChoose: "Use this when your class already covers the topic.", advantages: "Fits existing workload.", tradeoffs: "May not produce public evidence unless documented.", bestFit: "Students currently taking CS2 or data structures.", timeCommitment: "Course time plus 1 extra hour weekly.", unlocks: "Reviewed coursework evidence." },
      { title: "Interview-lite drills", whyChoose: "Use this when recruiting is close.", advantages: "Connects concepts to common interview tasks.", tradeoffs: "Can become shallow if fundamentals are weak.", bestFit: "Students with some data structures exposure.", timeCommitment: "2-4 hours per week.", unlocks: "Algorithm readiness." }
    ],
    whatHappensNext: "Once data structures are usable, algorithm practice and technical interviews become more productive.",
    howDoIStart: ["Pick three structures you do not know well.", "Implement each with one test.", "Write one sentence on when to use it."],
    successEvidence: "A small repository or notebook with implemented structures, tests, and usage notes.",
    informationDrawer: { skillsDeveloped: ["Data structures", "Testing", "Technical explanation"], difficulty: "Moderate", typicalTimeCommitment: "3-5 focused hours per week.", relatedCareers: ["Software Engineering", "Data Engineering", "AI Infrastructure"], relatedOpportunities: ["Internships", "Campus developer jobs", "Competitions"], whatIsThis: "Data structures are reusable ways to organize information in code.", whyItMatters: "They show up in interviews, coursework, and real systems.", whoBenefitsMost: "CS students preparing for projects or technical recruiting.", commonMisconceptions: ["Memorizing names is not enough.", "The goal is knowing when and why to use each structure."], examples: ["Hash map demo", "Queue simulation", "Graph traversal notebook"] },
    unlockChain: ["Data structures", "Algorithms", "Interview preparation", "Technical internship applications"],
    supportingKnowledgeSourceIds: ["advisor.rules.software-engineering", "advisor.prerequisites.data-structures"],
    impactLabel: "Foundational",
  }),
  algorithms: coaching({
    recommendation: "Based on your current profile, the next step is to practice algorithms with explanations, not just solved answers.",
    learnMore: "Algorithms practice matters when a student can explain tradeoffs, complexity, and edge cases.",
    whyThis: "Your software path needs stronger problem-solving evidence before interview-heavy recommendations become useful.",
    alternativePaths: ["Use a structured problem set.", "Pair with a peer and explain solutions aloud.", "Connect algorithms to an existing project."],
    whatHappensNext: "Better algorithm reasoning unlocks interview preparation and more selective technical applications.",
    howDoIStart: ["Choose one topic.", "Solve three problems slowly.", "Write the reasoning and edge cases after each solution."],
    successEvidence: "A practice log with solved problems, explanations, and mistakes fixed.",
    informationDrawer: { skillsDeveloped: ["Algorithmic reasoning", "Complexity analysis", "Technical communication"], difficulty: "High", typicalTimeCommitment: "3-6 focused hours per week.", relatedCareers: ["Software Engineering", "Quantitative Development", "Data Engineering"], relatedOpportunities: ["Internships", "Competitions", "Interview prep programs"], whatIsThis: "Algorithm practice builds repeatable problem-solving patterns.", whyItMatters: "Many technical interviews test reasoning under constraints.", whoBenefitsMost: "Students with data structures exposure who are preparing for interviews.", commonMisconceptions: ["Grinding many problems is less useful than reviewing mistakes.", "Explaining the solution matters as much as passing tests."], examples: ["Two-pointer practice log", "Graph traversal explanation", "Dynamic programming notes"] },
    unlockChain: ["Data structures", "Algorithms", "Mock interviews", "Technical interviews"],
    supportingKnowledgeSourceIds: ["advisor.rules.software-engineering", "advisor.prerequisites.algorithms"],
  }),
  team_project: coaching({
    recommendation: "Based on your current profile, the next useful step is to complete one team-based technical project with a clear personal contribution.",
    learnMore: "Team projects show collaboration, ownership, and communication in ways solo coursework often cannot.",
    whyThis: "Your software profile needs evidence that you can work with others and explain your part of a shared build.",
    alternativePaths: ["Join a club build team.", "Extend a hackathon project with teammates.", "Contribute a scoped feature to an open-source or campus project."],
    whatHappensNext: "A team project creates stronger interview stories and a more credible project section.",
    howDoIStart: ["Find one team with a real deliverable.", "Choose a small owned feature.", "Document your contribution before the project ends."],
    successEvidence: "A shared project with a visible personal contribution and explanation.",
    informationDrawer: { skillsDeveloped: ["Collaboration", "Scope ownership", "Technical communication"], difficulty: "Moderate", typicalTimeCommitment: "2-5 focused hours per week.", relatedCareers: ["Software Engineering", "Product", "Engineering"], relatedOpportunities: ["Student organizations", "Hackathons", "Campus jobs"], whatIsThis: "A team project is a shared deliverable where your contribution can be inspected.", whyItMatters: "Most real technical work happens with other people and constraints.", whoBenefitsMost: "Students with solo coursework but little collaboration evidence.", commonMisconceptions: ["Being on a team is not enough; your contribution must be clear.", "A small shipped feature beats a vague large idea."], examples: ["Club website feature", "Robotics subsystem", "Open-source issue"] },
    unlockChain: ["Team role", "Owned feature", "Project explanation", "Internship interview story"],
    supportingKnowledgeSourceIds: ["advisor.rules.software-engineering", "advisor.evidence.team-projects"],
  }),
  relevant_experience: coaching({
    recommendation: "Based on your current profile, the highest-impact next step is to secure one relevant role with defined responsibilities.",
    learnMore: "Relevant experience can come from internships, research, campus jobs, volunteering, clubs, or client work.",
    whyThis: "A defined role creates evidence of reliability, responsibility, and applied learning.",
    alternativePaths: ["Apply for a campus job.", "Join a research group.", "Take a club role with real deliverables."],
    whatHappensNext: "Experience helps future recommendations shift from developmental to target opportunities.",
    howDoIStart: ["Find three realistic roles.", "Check eligibility and deadlines.", "Apply or contact the owner this week."],
    successEvidence: "Confirmed role with defined responsibilities.",
    unlockChain: ["Resume ready", "Applications submitted", "Interview preparation", "Selection process"],
  }),
  resume_ready: coaching({
    recommendation: "Based on your current profile, the most practical next step is to create and review a role-specific one-page resume.",
    learnMore: "A role-specific one-page resume helps students act quickly when deadlines appear.",
    whyThis: "Many opportunities close before students expect; a ready resume lowers friction.",
    alternativePaths: ["Use your career center.", "Ask a trusted older student for review.", "Adapt a clean one-page template."],
    whatHappensNext: "Once complete, the advisor can prioritize applications that require quick turnaround.",
    howDoIStart: ["Draft one page.", "Tailor the heading and bullets to your goal.", "Get one review before applying."],
    successEvidence: "Reviewed one-page resume tailored to the career.",
    unlockChain: ["Resume ready", "Applications", "Interview preparation", "Interview feedback", "Stronger next cycle"],
  }),
  interview_prep: coaching({
    recommendation: "Based on your current profile, the next high-value step is to begin interview preparation with feedback.",
    learnMore: "Interview preparation is most valuable when it includes feedback, not just solo practice.",
    whyThis: "Feedback exposes gaps that are hard to see alone and improves future application outcomes.",
    alternativePaths: ["Use a mock interview.", "Practice with a peer.", "Record yourself explaining one project."],
    whatHappensNext: "The advisor can recommend more selective opportunities once preparation evidence improves.",
    howDoIStart: ["Pick one interview format.", "Schedule one practice session.", "Write down feedback and next fixes."],
    successEvidence: "Completed mock interview with feedback log.",
    unlockChain: ["Career fit", "Clinical exposure", "Reflection", "Letters and application planning"],
  }),
  clinical_exposure: coaching({
    recommendation: "Based on your current profile, the highest-impact next step is to gain sustained healthcare exposure.",
    learnMore: "Clinical exposure helps students test whether healthcare work fits their values and day-to-day interests.",
    whyThis: "Medical pathways require sustained, reflective experience, not just academic interest.",
    alternativePaths: ["Volunteer in a healthcare setting.", "Shadow where appropriate.", "Work in a patient-facing campus or community role."],
    whatHappensNext: "Strong exposure supports future service, research, and application planning.",
    howDoIStart: ["Identify local options.", "Confirm requirements.", "Commit to a consistent schedule."],
    successEvidence: "Sustained healthcare exposure plus reflection.",
    unlockChain: ["Service role", "Sustained responsibility", "Reflection", "Application narrative"],
  }),
  service_experience: coaching({
    recommendation: "Based on your current profile, the strongest next step is to begin one sustained service commitment.",
    learnMore: "Service experience demonstrates sustained responsibility and connection to real communities.",
    whyThis: "Many health, education, policy, and nonprofit paths value consistency over scattered activities.",
    alternativePaths: ["Choose a campus service program.", "Volunteer with a local organization.", "Take a recurring support role."],
    whatHappensNext: "Consistent service can become a strong narrative and a source of references.",
    howDoIStart: ["Choose one organization.", "Ask for a recurring role.", "Track hours and responsibilities."],
    successEvidence: "Ongoing commitment with defined responsibility.",
    unlockChain: ["Timeline", "Materials plan", "Verified deadlines", "Application season"],
  }),
  application_timeline_ready: coaching({
    recommendation: "Based on your current profile, the next priority is to build a verified application timeline before materials become urgent.",
    learnMore: "A verified timeline prevents missed deadlines and keeps requirements from piling up late.",
    whyThis: "Application-heavy paths reward early planning because materials often depend on other people or documents.",
    alternativePaths: ["Use a spreadsheet.", "Use a calendar.", "Ask an advisor to verify your timeline."],
    whatHappensNext: "Once the timeline is clear, the advisor can prioritize the highest-risk upcoming items.",
    howDoIStart: ["List target programs.", "Add deadlines from official sources.", "Mark prerequisites and material owners."],
    successEvidence: "Verified calendar with sources and milestones.",
    unlockChain: ["Verified timeline", "Materials checklist", "Letters or documents", "Application season"],
  }),
  career_fit_explored: coaching({
    recommendation: "Based on your current profile, the best next step is to run a short career-fit sprint before committing to a narrow path.",
    learnMore: "A career-fit sprint compares a few paths through conversations, role descriptions, and one small test activity instead of guessing from job titles.",
    whyThis: "Your profile shows exploration is still unresolved, so the advisor is prioritizing evidence about fit before specialized applications.",
    whyNow: "Early exploration is useful now because it prevents you from spending a semester building evidence for a path you may not actually want.",
    whyBeforeOthers: "It comes before heavier applications because choosing a direction makes future projects, clubs, and opportunities easier to evaluate.",
    whyRankedAboveAlternatives: "It is ranked above narrower skill work because your current profile needs a clearer direction before specialization.",
    alternativePaths: ["Interview two older students in different paths.", "Shadow a campus role or attend two career events.", "Complete one tiny project in each of two interest areas."],
    alternatives: [
      { title: "Two-advisor conversation sprint", whyChoose: "Use this when you need outside perspective quickly.", advantages: "Fast, low-cost, and grounded in real student experience.", tradeoffs: "Less concrete than producing a project artifact.", bestFit: "Undecided or cross-interest students.", timeCommitment: "2-3 hours total.", unlocks: "A ranked list of two paths to test next." },
      { title: "Mini project comparison", whyChoose: "Use this when you learn by doing.", advantages: "Produces visible evidence and clarifies what work feels like.", tradeoffs: "Takes more effort than conversations.", bestFit: "Students comparing technical, creative, or analytics paths.", timeCommitment: "3-5 hours over two weeks.", unlocks: "A small artifact and clearer direction." },
      { title: "Campus role sampling", whyChoose: "Use this when clubs or campus offices are accessible.", advantages: "Adds community and accountability.", tradeoffs: "Depends on campus timing and availability.", bestFit: "Students who want a low-risk real-world setting.", timeCommitment: "1-3 hours per week.", unlocks: "A role, mentor, or next application target." }
    ],
    whatHappensNext: "After the sprint, the advisor can recommend one path-specific artifact, role, or application instead of broad exploration.",
    howDoIStart: ["Choose two paths to compare.", "Find one person or event for each path.", "Write down what evidence would make one path more convincing."],
    successEvidence: "A one-page comparison with two paths, what you learned, and the next path to test.",
    informationDrawer: { skillsDeveloped: ["Career research", "Decision-making", "Reflection"], difficulty: "Low", typicalTimeCommitment: "2-4 focused hours over one to two weeks.", relatedCareers: ["Business", "Technology", "Research", "Policy", "Healthcare"], relatedOpportunities: ["Career resources", "Student organizations", "Campus jobs", "Research"], whatIsThis: "A career-fit sprint is a short structured comparison of possible directions.", whyItMatters: "It keeps early students from confusing interest with fit before investing heavily.", whoBenefitsMost: "Undecided students or students split between several fields.", commonMisconceptions: ["You do not need to choose your whole career.", "Exploration should still produce evidence, not just browsing."], examples: ["Two informational interviews", "A career event reflection", "A mini project comparison"] },
    unlockChain: ["Career-fit sprint", "Path selection", "Targeted evidence", "Relevant opportunity search"],
    supportingKnowledgeSourceIds: ["advisor.rules.general-exploration", "advisor.pathways.exploration"],
    impactLabel: "Foundational",
  }),
  research_or_inquiry: coaching({
    recommendation: "Based on your current profile, the strongest next step is to join or create one inquiry-based experience tied to a real question.",
    learnMore: "Research or inquiry work can happen through labs, faculty projects, policy work, market research, independent studies, or structured campus programs.",
    whyThis: "Your profile would benefit from evidence that you can investigate a question, handle ambiguity, and explain what you learned.",
    whyBeforeOthers: "It ranks ahead of broader applications because a defined inquiry experience can strengthen multiple future paths.",
    alternativePaths: ["Email a faculty member about a small role.", "Use a class paper as a research sample.", "Join a campus organization project with data or interviews."],
    alternatives: [
      { title: "Faculty-assisted research role", whyChoose: "Use this when a department or lab has accessible openings.", advantages: "Mentorship and credible context.", tradeoffs: "May take time to secure.", bestFit: "Students considering graduate, clinical, policy, or research paths.", timeCommitment: "3-6 hours per week.", unlocks: "Research experience and possible recommendation context." },
      { title: "Class-to-sample path", whyChoose: "Use this when time or access is limited.", advantages: "Uses work you are already doing.", tradeoffs: "May carry less weight than a formal role.", bestFit: "Busy students with writing or analysis coursework.", timeCommitment: "1-3 extra hours per week.", unlocks: "A writing sample or analysis artifact." },
      { title: "Organization inquiry project", whyChoose: "Use this when campus groups have real questions to answer.", advantages: "Applied, practical, and visible.", tradeoffs: "Less formal academic supervision.", bestFit: "Students in marketing, psychology, policy, or business exploration.", timeCommitment: "2-4 hours per week.", unlocks: "Applied project evidence." }
    ],
    whatHappensNext: "A completed inquiry experience can become an application story, writing sample, research lead, or recommendation context.",
    howDoIStart: ["Choose one question you would actually want to investigate.", "Find a class, faculty member, or organization connected to it.", "Ask for a small, clearly scoped contribution."],
    successEvidence: "A defined research role, writing sample, analysis, or project summary.",
    informationDrawer: { skillsDeveloped: ["Research judgment", "Analysis", "Written explanation"], difficulty: "Moderate", typicalTimeCommitment: "2-6 focused hours per week.", relatedCareers: ["Research", "Clinical Psychology", "Medicine", "Policy", "Marketing Analytics"], relatedOpportunities: ["Research", "Fellowships", "Campus jobs", "Competitions"], whatIsThis: "Inquiry work means investigating a real question with evidence and a clear output.", whyItMatters: "It shows curiosity, discipline, and the ability to work through uncertainty.", whoBenefitsMost: "Students considering graduate school, research, healthcare, policy, analytics, or strategy roles.", commonMisconceptions: ["Research is not only lab work.", "A small defined contribution is better than a vague affiliation."], examples: ["Literature review", "Dataset analysis", "Interview summary", "Lab assistant role"] },
    unlockChain: ["Question", "Inquiry experience", "Evidence artifact", "Stronger applications"],
    supportingKnowledgeSourceIds: ["advisor.rules.research-inquiry", "advisor.pathways.graduate-school"],
  }),
  reflection_quality: coaching({
    recommendation: "Based on your current profile, the next useful step is to write a short reflection that connects your experiences to a direction.",
    learnMore: "Reflection quality matters when students need to explain why an opportunity, graduate path, or career direction fits them.",
    whyThis: "Your profile has interests, but the advisor needs clearer evidence that you can explain what those experiences mean.",
    alternativePaths: ["Write a one-page reflection.", "Record a two-minute explanation and transcribe the strongest points.", "Ask an advisor or mentor to review your story."],
    whatHappensNext: "Clearer reflection improves essays, interviews, advisor meetings, and path selection.",
    howDoIStart: ["Pick one experience.", "Write what you did, what changed, and what you want to test next.", "Keep the strongest three sentences."],
    successEvidence: "A concise reflection connecting one experience to a next step.",
    informationDrawer: { skillsDeveloped: ["Reflection", "Communication", "Career reasoning"], difficulty: "Low", typicalTimeCommitment: "1-2 focused hours.", relatedCareers: ["Graduate School", "Clinical Psychology", "Medicine", "Policy", "Education"], relatedOpportunities: ["Fellowships", "Research", "Leadership programs", "Scholarships"], whatIsThis: "A reflection converts experience into an explanation that another person can evaluate.", whyItMatters: "Applications and interviews often reward clear reasoning, not just activity lists.", whoBenefitsMost: "Students preparing for advising meetings, essays, interviews, or competitive programs.", commonMisconceptions: ["Reflection is not filler.", "A specific honest explanation is stronger than polished generic motivation."], examples: ["Short advising memo", "Interview story draft", "Scholarship essay outline"] },
    unlockChain: ["Experience", "Reflection", "Advisor feedback", "Application narrative"],
    supportingKnowledgeSourceIds: ["advisor.rules.reflection", "advisor.pathways.application-narrative"],
    impactLabel: "Helpful",
  }),
};

export function coachingForSignal(signal: string): RecommendationCoaching {
  return actionKnowledge[signal] ?? fallbackActionCoaching;
}

export function coachingForOpportunityClassification(classification: "target" | "stretch" | "developmental"): RecommendationCoaching {
  if (classification === "target") return {
    ...coaching({
    recommendation: "Based on your profile, this is a practical target opportunity to review now.",
    learnMore: "Target opportunities match the current profile strongly enough to be practical next applications.",
    whyThis: "The advisor sees enough eligibility, timing, and fit evidence to treat this as a realistic shortlist item.",
    alternativePaths: ["Apply to a similar opportunity with a later deadline.", "Save this and compare it with another target match."],
    whatHappensNext: "Confirm details on the official source, then decide whether to save or apply.",
    howDoIStart: ["Open the official listing.", "Verify eligibility and deadline.", "Prepare the required materials."],
    successEvidence: "Application started or saved with verified requirements.",
    trustBasis: ["Verified opportunity source", "Recruiting norms"],
    }),
  };
  if (classification === "stretch") return {
    ...coaching({
    recommendation: "Based on your profile, this is a stretch opportunity worth considering with a clear gap plan.",
    learnMore: "Stretch opportunities may be worth pursuing, but one or more readiness signals are still developing.",
    whyThis: "The advisor sees meaningful fit plus a gap that may affect competitiveness or preparation.",
    alternativePaths: ["Apply if the deadline is soon.", "Pair this with a developmental opportunity.", "Close the readiness gap first if timing allows."],
    whatHappensNext: "Use the opportunity to clarify which evidence you need to strengthen.",
    howDoIStart: ["Check eligibility.", "Identify the weakest requirement.", "Decide whether to apply now or build evidence first."],
    successEvidence: "Eligibility verified and gap plan created.",
    trustBasis: ["Verified opportunity source", "Incomplete profile evidence"],
    }),
  };
  return coaching({
    recommendation: "Based on your profile, this developmental opportunity can build evidence for stronger options later.",
    learnMore: "Developmental opportunities are useful when they build evidence for stronger future applications.",
    whyThis: "The advisor is using this to build readiness rather than treating it as the final goal.",
    alternativePaths: ["Choose a smaller local version.", "Look for a campus role with similar responsibilities.", "Build a project that creates equivalent evidence."],
    whatHappensNext: "Completion should unlock more targeted recommendations later.",
    howDoIStart: ["Review requirements.", "Choose the lowest-friction entry point.", "Save proof of participation or output."],
    successEvidence: "Completed experience or artifact that improves readiness.",
    trustBasis: ["Academic guidance", "Prerequisite relationships"],
  });
}
